import os

SEM8 = {
"sem8-aml": [
  {"q":"AML stands for?","opts":["Advanced Machine Learning","Artificial Machine Logic","Automated Model Layer","Advanced Media Loop"],"ans":0},
  {"q":"Unsupervised Learning: Clustering?","opts":["Predicting labels","Grouping unlabeled data into similar clusters","Predicting prices","Sorting alphabetically"],"ans":1},
  {"q":"Dimensionality Reduction?","opts":["Increasing parameters","Reducing the number of input variables in a dataset (e.g. PCA)","Rounding numbers","Deleting data"],"ans":1},
  {"q":"Principal Component Analysis (PCA)?","opts":["Clustering","Technique for dimensionality reduction using eigenvectors","Classification","Regression"],"ans":1},
  {"q":"Anomaly Detection?","opts":["Finding average","Identifying rare items/events that differ from majority","Finding max","Sorting data"],"ans":1},
  {"q":"Reinforcement Learning (RL) involves?","opts":["Historical data only","Learning through interactions and rewards","Labeled data only","No learning"],"ans":1},
  {"q":"Q-Learning is a type of?","opts":["Supervised learning","Model-free reinforcement learning algorithm","Clustering","Regression"],"ans":1},
  {"q":"Deep Reinforcement Learning?","opts":["RL with Neural Networks","RL with tables only","Standard ML","Pure coding"],"ans":0},
  {"q":"Ensemble Learning?","opts":["Single model","Combining predictions from multiple models to improve performance","Deleting models","Sorting data"],"ans":1},
  {"q":"Bagging (e.g. Random Forest)?","opts":["Sequential models","Parallel training on bootstrap samples","No sampling","Fixed data"],"ans":1},
  {"q":"Boosting (e.g. AdaBoost, XGBoost)?","opts":["Parallel models","Sequential models where each corrects previous errors","Random models","Fast models"],"ans":1},
  {"q":"Stacking in ML?","opts":["Deleting models","Combining different model predictions using a meta-model","LIFO","FIFO"],"ans":1},
  {"q":"Gaussian Mixture Models (GMM)?","opts":["Linear model","Probabilistic model for clustering (soft clustering)","Decision tree","Hash table"],"ans":1},
  {"q":"Expectation-Maximization (EM) algorithm?","opts":["Sorting","Iterative method for finding maximum likelihood estimates in GMM","Searching","Printing"],"ans":1},
  {"q":"Bias-Variance tradeoff: A complex model has?","opts":["High bias","High variance (overfitting)","Low variance","Low logic"],"ans":1},
  {"q":"Bias-Variance tradeoff: A simple model has?","opts":["Low bias","High bias (underfitting)","Low error","High variance"],"ans":1},
  {"q":"Hyperparameter Optimization?","opts":["Training weights","Searching for best parameters (e.g. Grid Search, Bayesian Opt)","Deleting data","Fast loading"],"ans":1},
  {"q":"Bayesian Optimization?","opts":["Random search","Probabilistic model-based optimization for hyperparameters","Linear search","Hashing"],"ans":1},
  {"q":"Markov Chain?","opts":["Linguistic rule","Sequence of events where next state depends only on current state","A crypto chain","A data list"],"ans":1},
  {"q":"Natural Language Processing (NLP)?","opts":["Hardware logic","AI for human language understanding and generation","Pure math","A database"],"ans":1},
  {"q":"Transformer architecture?","opts":["CNN","Self-attention based neural network for sequence tasks","A generator","A CPU design"],"ans":1},
  {"q":"Self-Attention mechanism?","opts":["Looking at all words","Relating different positions of a single sequence to compute representation","Deleting text","Fixed window"],"ans":1},
  {"q":"BERT model?","opts":["One-way model","Bidirectional encoder for language context","Image only","Regression only"],"ans":1},
  {"q":"GPT model?","opts":["Encoder only","Generative transformer (Autoregressive)","Clustering only","Sorting only"],"ans":1},
  {"q":"Active Learning?","opts":["Model learns itself","Model asks for labels for most 'uncertain' points","Model is fast","Model is online"],"ans":1},
  {"q":"Transfer Learning?","opts":["Starting from scratch","Adapting a pre-trained model for a new task","Deleting weights","Moving data"],"ans":1},
  {"q":"Generative Adversarial Networks (GANs)?","opts":["Detectors only","Generator vs. Discriminator networks for creating synthetic data","Simple logic","Search engines"],"ans":1},
  {"q":"Variational Autoencoders (VAEs)?","opts":["Discriminators","Generative models that learn latent representations","Simple classifiers","Sorting engines"],"ans":1},
  {"q":"Explainable AI (XAI)?","opts":["Making AI faster","Techniques to make AI decisions understandable by humans","Secret AI","Complex AI"],"ans":1},
  {"q":"SHAP and LIME?","opts":["Programming languages","Methods for interpreting ML model predictions","Database names","UI tools"],"ans":1},
  {"q":"Graph Neural Networks (GNNs)?","opts":["For images","Used for data structured as graphs (social nets, molecules)","For text only","For hardware"],"ans":1},
  {"q":"Recommendation Systems?","opts":["Deleting info","Predicting user preferences (Collaborative/Content filtering)","Searching web","Managing project"],"ans":1},
  {"q":"Collaborative Filtering?","opts":["Based on item details","Based on user-item interaction similarities","Based on tags","Based on cost"],"ans":1},
  {"q":"Time Series Forecasting?","opts":["Identifying colors","Predicting future values based on historical time-stamped data","Finding labels","Sorting names"],"ans":1},
  {"q":"One-Shot Learning?","opts":["Learning from millions","Learning from a single training example per class","No learning","Random prediction"],"ans":1},
  {"q":"Model Compression: Distillation?","opts":["Deleting nodes","Training a smaller 'student' model to mimic a 'teacher' model","Water treatment","Data entry"],"ans":1},
  {"q":"Precision-Recall Curve?","opts":["Model speed","Evaluating classification performance at various thresholds","Training cost","Memory usage"],"ans":1},
  {"q":"Confusion Matrix?","opts":["Random table","Table showing TP, TN, FP, FN results","A math error","Logic diagram"],"ans":1},
  {"q":"Learning Rate Decay?","opts":["Increasing LR","Gradually reducing learning rate during training","Faster LR","Fixed LR"],"ans":1},
  {"q":"Model Quantization?","opts":["Deleting model","Reducing precision of weights (e.g. Float to Int) for faster inference","Increasing precision","Scaling data"],"ans":1},
  {"q":"Feature Engineering?","opts":["Creating data","Creating new features from raw data to improve model","Writing code","Managing team"],"ans":1},
  {"q":"Overfitting prevention?","opts":["More data","Regularization (L1/L2), Dropout, Early Stopping","Increasing complexity","Less data"],"ans":1},
  {"q":"Stochastic Gradient Descent (SGD)?","opts":["Updates once","Weight updates after every sample/batch","No updates","Global search"],"ans":1},
  {"q":"Loss Function?","opts":["Accuracy measure","Differentiable function to minimize (e.g. LogLoss, MSE)","Binary check","Final report"],"ans":1},
  {"q":"Gradient Descent?","opts":["Global search","Optimization algorithm to find the minimum of a function","Logic check","Database query"],"ans":1},
  {"q":"Cross-Validation?","opts":["Training on all data","Partitioning data into folds to assess generalization","Offline check","Saving result"],"ans":1},
  {"q":"A* Search in AI?","opts":["Uninformed","Informed search using heuristics","Random search","BFS"],"ans":1},
  {"q":"Turing Test?","opts":["Measures speed","Tests if machine can exhibit human-intelligent behavior","Tests memory","Tests logic"],"ans":1},
  {"q":"Neural Network weights?","opts":["Fixed forever","Adjustable parameters that the network 'learns'","Random only","Binary only"],"ans":1},
  {"q":"AutoML?","opts":["Car design","Automating the end-to-end process of applying ML","Manual ML","No ML"],"ans":1}
],
"sem8-cs": [
  {"q":"Cyber Security objective:","opts":["Speed","Confidentiality, Integrity, Availability (CIA)","Cost","Accessibility"],"ans":1},
  {"q":"Malware stands for?","opts":["Malicious Logic","Malicious Software","Many-layered Ware","Main Logic Ware"],"ans":1},
  {"q":"Phishing is a type of?","opts":["Hardware attack","Social engineering attack to steal sensitive info","Logic error","A virus"],"ans":1},
  {"q":"Encryption?","opts":["Deleting data","Encoding info to prevent unauthorized access","Sorting data","Sizing data"],"ans":1},
  {"q":"Symmetric Encryption?","opts":["Two keys","One key for both encryption and decryption","No keys","Public key only"],"ans":1},
  {"q":"Asymmetric Encryption?","opts":["One key","Public and private key pair","Faster than symmetric","No algorithm"],"ans":1},
  {"q":"RSA is?","opts":["Symmetric algorithm","Asymmetric cryptographic algorithm","Hash function","Protocol"],"ans":1},
  {"q":"Hashing?","opts":["Reversible","One-way function producing fixed-length output (digest)","Encryption","Compression"],"ans":1},
  {"q":"Digital Signature?","opts":["Handwritten sign","Mathematical scheme for verifying authenticity/integrity","A logo","A photo"],"ans":1},
  {"q":"Firewall?","opts":["Physical wall","Network security device monitoring/filtering traffic","A type of virus","A browser"],"ans":1},
  {"q":"IDS stands for?","opts":["Intrusion Detection System","Internal Data Script","Input Delivery Service","Interactive Design System"],"ans":0},
  {"q":"IPS stands for?","opts":["Intrusion Prevention System","Internet Protocol Setup","Inbound Process script","Integrated Power System"],"ans":0},
  {"q":"Ransomware?","opts":["Free utility","Malware that demands money for data decryption","A protective software","A browser plugin"],"ans":1},
  {"q":"Trojan Horse?","opts":["Helpful file","Malware disguised as legitimate software","Physical gift","A firewall"],"ans":1},
  {"q":"Spyware?","opts":["Encrypted data","Software for secret surveillance of user activity","Anti-virus","Formatting tool"],"ans":1},
  {"q":"Botnet?","opts":["Small bot","Network of infected computers controlled as a group (zombies)","Fast cluster","Cloud storage"],"ans":1},
  {"q":"DDoS Attack?","opts":["Data Loss","Distributed Denial of Service (overwhelming a target with traffic)","Disk cleanup","Encryption"],"ans":1},
  {"q":"SQL Injection?","opts":["DB backup","Inserting malicious SQL lines into input fields to bypass security","SQL optimization","Index repair"],"ans":1},
  {"q":"Cross-Site Scripting (XSS)?","opts":["Server attack","Injected malicious scripts into trusted websites","VPN attack","Hardware bug"],"ans":1},
  {"q":"Man-in-the-Middle (MitM)?","opts":["Helpful proxy","Attacker intercepts/alters communication between two parties","Shared drive","Admin user"],"ans":1},
  {"q":"VPN stands for?","opts":["Virtual Private Network","Variable Protocol Node","Visual Port Name","Virtual Public Network"],"ans":0},
  {"q":"SSL/TLS?","opts":["Hardware","Cryptographic protocols for secure communication (HTTPS)","Encryption algorithms only","Hashing only"],"ans":1},
  {"q":"Public Key Infrastructure (PKI)?","opts":["Database","System for managing digital certificates and public-key encryption","Private file","Internal tool"],"ans":1},
  {"q":"Authentication vs Authorization?","opts":["They are same","Auth is WHO; Authorization is ACCESS LIMITS","Auth is for databases","They are opposites"],"ans":1},
  {"q":"Two-Factor Authentication (2FA)?","opts":["One password","Using two different pieces of evidence (e.g. pwd + code)","Two usernames","Biometrics only"],"ans":1},
  {"q":"Biometrics?","opts":["Passwords","Physical characteristics (fingerprint, face) for authentication","ID cards","Keys"],"ans":1},
  {"q":"Zero Day vulnerability?","opts":["Safe day","Vulnerability unknown to the vendor/developer","New feature","Final bug"],"ans":1},
  {"q":"Brute Force Attack?","opts":["Physical attack","Trying every possible password combination","Logic puzzle","Social hack"],"ans":1},
  {"q":"Buffer Overflow?","opts":["Full hard drive","Writing more data to a block than it can hold, leading to crashes/exploits","Slow internet","Large RAM"],"ans":1},
  {"q":"Penetration Testing (Ethical Hacking)?","opts":["Illegal hack","Authorized simulated attack to find weaknesses","Writing code","Data entry"],"ans":1},
  {"q":"Vulnerability Scanning?","opts":["Testing speed","Automated check for known security flaws","Manual code review","User interview"],"ans":1},
  {"q":"Endpoint Security?","opts":["Cable security","Protecting individual devices (laptops, mobiles) on a network","Server only","Internet core"],"ans":1},
  {"q":"Cloud Security?","opts":["Local PC safety","Policies/tools for protecting cloud-based data and infra","External HDD","Physical vault"],"ans":1},
  {"q":"Data Breach?","opts":["Normal access","Unauthorized access/release of private information","Hard drive failure","Internet outage"],"ans":1},
  {"q":"Encryption: AES?","opts":["Asymmetric","Advanced Encryption Standard (Symmetric block cipher)","Hash function","Protocol"],"ans":1},
  {"q":"Network Scanning (e.g. Nmap)?","opts":["Scanning documents","Identifying active devices/ports on a network","Reading mail","Printing data"],"ans":1},
  {"q":"Zero Trust Model?","opts":["Trust everyone","Verify everything, trust nothing (never assume network is safe)","No security","Internal trust"],"ans":1},
  {"q":"Identity and Access Management (IAM)?","opts":["File manager","Ensuring the right people have access to the right resources","Login UI only","Database config"],"ans":1},
  {"q":"Cyber Resilience?","opts":["Fixed speed","Ability of system to continue operating during and after a cyber attack","High defense","Fast recovery only"],"ans":1},
  {"q":"Steganography?","opts":["Encryption","Hiding information within another non-secret file (e.g. image)","Hashing","Deletion"],"ans":1},
  {"q":"Packet Sniffing?","opts":["Smelling hardware","Intercepting and logging network traffic packets","File printing","Speed testing"],"ans":1},
  {"q":"Social Engineering?","opts":["Building apps","Psychological manipulation of people into divalging info","Group study","Team building"],"ans":1},
  {"q":"Honey Pot?","opts":["Sweet treat","Decoy system used to lure and observe attackers","Main server","Firewall"],"ans":1},
  {"q":"Security Operations Center (SOC)?","opts":["Building site","Dedicated facility/team monitoring security events 24/7","A server room","An office"],"ans":1},
  {"q":"Intrusion?","opts":["Welcome entry","Unauthorized access or attempted access to a system","Normal login","System update"],"ans":1},
  {"q":"Least Privilege Principle?","opts":["Admin for all","Only providing minimum access rights needed to do a job","No access","Random access"],"ans":1},
  {"q":"Encryption: RSA involves?","opts":["Large primes","Hashing","Symmetric keys","Logic gates"],"ans":0},
  {"q":"Social Media Security?","opts":["Deleting profile","Protecting accounts and personal info on social platforms","Color depth","Fast scrolling"],"ans":1},
  {"q":"IoT Security challenges?","opts":["Too much power","Many low-resource devices, often with weak default security","Small size","No internet"],"ans":1},
  {"q":"Cyber Security is?","opts":["Finite task","Ongoing process of protecting systems, networks, and data","Static setting","One-time fix"],"ans":1}
],
"sem8-qc": [
  {"q":"Quantum Computing is based on?","opts":["Classical bit logic","Quantum mechanics (superposition and entanglement)","Binary gates only","Heat dynamics"],"ans":1},
  {"q":"The basic unit of information in QC?","opts":["Bit","Qubit (Quantum Bit)","Byte","Node"],"ans":1},
  {"q":"Superposition means?","opts":["Only 0","Only 1","State of being in 0 and 1 simultaneously until measured","Fast processing"],"ans":2},
  {"q":"Entanglement?","opts":["Independence","Quantum phenomenon where particles remain connected regardless of distance","Messy wires","Encryption"],"ans":1},
  {"q":"A classical bit can be?","opts":["0 or 1","0 and 1","Any number","Continuous"],"ans":0},
  {"q":"Who proposed the idea of Quantum Computers?","opts":["Bill Gates","Richard Feynman","Ada Lovelace","Steve Jobs"],"ans":1},
  {"q":"Quantum Interference?","opts":["Signal loss","Reinforcement or cancellation of quantum wave functions to find solutions","Noise","Error"],"ans":1},
  {"q":"Quantum Supremacy (Advantage)?","opts":["Better UI","Point where QC performs a task a classical computer cannot in reasonable time","Higher cost","More RAM"],"ans":1},
  {"q":"Decoherence?","opts":["Stability","Loss of quantum state due to environmental noise","Better performance","Initialization"],"ans":1},
  {"q":"To maintain quantum states, QCs often need?","opts":["High heat","Extreme cold (near absolute zero)","Normal room temp","Vacuum only"],"ans":1},
  {"q":"Quantum Gates?","opts":["Classic AND/OR gates","Operations that transform qubits (Hadamard, CNOT, etc.)","Physical doors","Power switches"],"ans":1},
  {"q":"Hadamard Gate (H)?","opts":["Sets to zero","Creates superposition state from basis state","Deletes qubit","Encryption tool"],"ans":1},
  {"q":"CNOT Gate?","opts":["Conditional logic","Controlled-NOT (flips target if control is 1) — creates entanglement","Classic NOT","Logical AND"],"ans":1},
  {"q":"Bloch Sphere?","opts":["Physical globe","Geometrical representation of the pure state space of a qubit","A math book","A screen"],"ans":1},
  {"q":"Shor's Algorithm?","opts":["Sorting","Efficiently finding prime factors (breaks RSA)","Searching","Rendering"],"ans":1},
  {"q":"Grover's Algorithm?","opts":["Encryption","Quadratic speedup for searching unstructured databases","Sorting","Routing"],"ans":1},
  {"q":"Quantum Cryptography (QKD)?","opts":["Symmetric key","Using quantum properties to share secret keys securely","Asymmetric only","Hashing only"],"ans":1},
  {"q":"The 'No-Cloning' Theorem?","opts":["Allows copying","It is impossible to create an identical copy of an unknown quantum state","Allows backup","For hardware only"],"ans":1},
  {"q":"Adiabatic Quantum Computing?","opts":["Search engine","Optimization by evolving a system slowly from easy to complex","Logic gates only","Manual setup"],"ans":1},
  {"q":"Quantum Anealing?","opts":["Classic heat","Process to find global minimum (used in D-Wave systems)","Binary search","Hashing"],"ans":1},
  {"q":"Quantum Parallelism?","opts":["Many CPUs","Processing all possible inputs at once due to superposition","Multi-threading","Cloud computing"],"ans":1},
  {"q":"Universal Quantum Computer?","opts":["Specific task PC","Machine capable of running any quantum algorithm using a universal gate set","Local network","Large server"],"ans":1},
  {"q":"Error Correction in QC?","opts":["Deleting errors","Technique to protect quantum info from noise/decoherence (requires many physical qubits)","Writing better code","Adding RAM"],"ans":1},
  {"q":"Cryogenics in QC?","opts":["Heating","Cooling systems for superconducting qubits","Graphics","Storage"],"ans":1},
  {"q":"Superconducting Qubits?","opts":["Normal wire","Qubits made from superconducting materials (used by IBM, Google)","Fiber optics","Semiconductors"],"ans":1},
  {"q":"Trapped Ion Qubits?","opts":["Solid materials","Qubits using charged atoms suspended in vacuum by electric fields","Liquids","Cloud only"],"ans":1},
  {"q":"QIS stands for?","opts":["Quantum Information Science","Quantum Interface System","Queue Input Script","Quality Integration Service"],"ans":0},
  {"q":"The state of a n-qubit system has how many amplitudes?","opts":["n","2ⁿ","n²","log n"],"ans":1},
  {"q":"Measurement in QC?","opts":["Does nothing","Collapses a qubit state into a classical 0 or 1","Increases energy","Is optional"],"ans":1},
  {"q":"Pauli Matrices (X, Y, Z)?","opts":["Linguistic rules","Mathematic operators representing qubit rotations","Binary values","Color codes"],"ans":1},
  {"q":"Quantum Volume?","opts":["Storage space","Metric measuring the overall performance/complexity of a QC","Physical size","Sound intensity"],"ans":1},
  {"q":"Post-Quantum Cryptography?","opts":["Better RSA","Cryptographic algorithms designed to be secure against quantum attacks","Classical only","No security"],"ans":1},
  {"q":"Quantum Teleportation?","opts":["Moving physical matter","Transmitting quantum information between two locations using entanglement","Fast internet","Time travel"],"ans":1},
  {"q":"Quantum Simulation?","opts":["Video game","Using QC to simulate quantum systems (molecules, materials)","Numerical simulation","Visual only"],"ans":1},
  {"q":"IBM Quantum Experience?","opts":["A museum","Platform for accessing real quantum hardware over the cloud","A game","A textbook"],"ans":1},
  {"q":"Quantum bit 'basis' states?","opts":["0 and 1","True and False","Up and Down","Only 0"],"ans":0},
  {"q":"Potential use of QC?","opts":["Writing email","Drug discovery, cryptography, complex optimization","Browsing web","Editing photos"],"ans":1},
  {"q":"Bra-Ket notation (Dirac notation)?","opts":["Math symbols |ψ>","Programming syntax","Chemical formula","Text format"],"ans":0},
  {"q":"Quantum bit 'phase'?","opts":["Physical color","Angle in the quantum state representation","Speed","Weight"],"ans":1},
  {"q":"Bell State?","opts":["A single qubit","Specific maximally entangled quantum states of two qubits","An alarm","A failure"],"ans":1},
  {"q":"Quantum algorithm designer?","opts":["Bill Gates","Peter Shor / Lov Grover","Grace Hopper","John von Neumann"],"ans":1},
  {"q":"QC logic gates are?","opts":["Irreversible","Unitary (Reversible)","Fixed 0/1","Linear only"],"ans":1},
  {"q":"Quantum sensor?","opts":["Detector","Device using quantum properties for high-sensitivity measurements","Heat sensor only","Light sensor only"],"ans":1},
  {"q":"Qiskit is?","opts":["A language","Open-source SDK for working with quantum computers (IBM)","A browser","A database"],"ans":1},
  {"q":"Cirq?","opts":["A circus","Python library for writing and simulating quantum circuits (Google)","A browser","A compiler"],"ans":1},
  {"q":"Quantum computer cost?","opts":["Cheap","Very expensive and research-heavy at currently","Free","Monthly fee"],"ans":1},
  {"q":"Quantum hardware stability?","opts":["Perfect","Highly sensitive to noise and vibrations","Indestructible","Offline only"],"ans":1},
  {"q":"Classical computer in QC?","opts":["Not needed","Needed for control, read-out, and pre/post processing","Is the CPU","Is the memory"],"ans":1},
  {"q":"Future of QC?","opts":["Full replacement of PCs","Hybrid classical-quantum computing for specific hard tasks","No future","Pure research only"],"ans":1},
  {"q":"Quantum bits are?","opts":["Physical atoms/particles or superconducting circuits","Software simulations","Only math formulas","Users"],"ans":0}
],
"sem8-pm": [
  {"q":"Project Management is the process of?","opts":["Writing code only","Leading a team to achieve project goals within constraints","Selling software","Designing a logo"],"ans":1},
  {"q":"The 'Triple Constraint' includes?","opts":["Team, Tech, Tools","Time, Cost, Scope","Code, Logic, Data","Boss, User, Client"],"ans":1},
  {"q":"PMBOK stands for?","opts":["Project Management Body of Knowledge","Process Management Book of Keys","Project Module Base of Knowledge","Private Management Book"],"ans":0},
  {"q":"Project Manager (PM) is responsible for?","opts":["Coding only","Overall success of the project","Designing only","Testing only"],"ans":1},
  {"q":"Project vs Operations?","opts":["Project is temporary; Operations are ongoing","They are same","Project is bigger","Operations are for hardware"],"ans":0},
  {"q":"Stakeholder?","opts":["Investor only","Anyone impacted by or having interest in the project","Customer only","Developer only"],"ans":1},
  {"q":"Project Lifecycle phases typically:","opts":["Initiation, Planning, Execution, Monitoring/Control, Closing","Setup, Coding, Ending","Draft, Print, Post","Start, Pause, Stop"],"ans":0},
  {"q":"Project Charter?","opts":["Map of office","Document that formally authorizes the project","A test report","A list of employees"],"ans":1},
  {"q":"WBS stands for?","opts":["Work Breakdown Structure","Web Base System","Wide Business Scope","Work Balance Schema"],"ans":0},
  {"q":"WBS involves?","opts":["Writing code","Breaking down project scope into smaller, manageable components (tasks)","Sorting files","Hiring people"],"ans":1},
  {"q":"Gantt Chart is a?","opts":["Calculation tool","Visual schedule tracking tasks over time","Database table","Resource list"],"ans":1},
  {"q":"Critical Path Method (CPM)?","opts":["Safety plan","Sequence of tasks that determines the shortest project duration","Encryption","Sorting logic"],"ans":1},
  {"q":"Slack/Float in project timing?","opts":["Extra time a task can be delayed without affecting finish date","Break time for team","Idle hardware","Missing tasks"],"ans":0},
  {"q":"PERT chart?","opts":["Visual map","Program Evaluation and Review Technique for analyzing tasks","A text file","A UI design"],"ans":1},
  {"q":"Scope Creep?","opts":["Slow progress","Uncontrolled changes/additions to project scope without adjustments in time/cost","Bug count","Team turnover"],"ans":1},
  {"q":"Risk Management Plan?","opts":["Budget for bugs","Identifying, analyzing, and responding to project risks","Test plan","Deployment guide"],"ans":1},
  {"q":"Risk Mitigation?","opts":["Ignoring risks","Reducing the probability or impact of a risk","Accepting the risk","Removing the task"],"ans":1},
  {"q":"Agile Project Management?","opts":["Waterfall only","Iterative approach focusing on flexibility and continuous feedback","Strict planning","No feedback"],"ans":1},
  {"q":"Scrum Master?","opts":["Technical lead","Facilitator for an agile team (removes blockers)","Product owner","Client representative"],"ans":1},
  {"q":"Product Owner?","opts":["Manager","Represents stakeholders and manages the product backlog","Developer","Designer"],"ans":1},
  {"q":"Backlog?","opts":["Archive","Prioritized list of work for the development team","File list","Log file"],"ans":1},
  {"q":"Sprint in Scrum?","opts":["Running fast","Time-boxed iteration (usually 1-4 weeks) to complete work","The final release","A planning meeting"],"ans":1},
  {"q":"KPI stands for?","opts":["Key Performance Indicator","Key Process Inventory","Known Process Index","Keyboard Process Interaction"],"ans":0},
  {"q":"Resource Allocation?","opts":["Buying hardware","Assigning available resources to tasks efficiently","Deleting data","Hiring more people"],"ans":1},
  {"q":"Milestone?","opts":["A physical stone","Significant point or event in the project timeline","A small task","A document"],"ans":1},
  {"q":"Quality Assurance (QA)?","opts":["Finding bugs","Process-oriented approach to ensure project meets standards","Testing code","Fixing bugs"],"ans":1},
  {"q":"Quality Control (QC)?","opts":["Logic check","Product-oriented approach focusing on identifying defects","Managing team","Hiring"],"ans":1},
  {"q":"Budgeting?","opts":["Spending money","Estimating and allocating financial resources for project","Printing reports","Saving time"],"ans":1},
  {"q":"Cost Variance (CV)?","opts":["Total cost","Difference between earned value and actual cost","Profit","Interest"],"ans":1},
  {"q":"ROI stands for?","opts":["Return on Investment","Record of Information","Rate of Inclusion","Resource on Internet"],"ans":0},
  {"q":"Change Management?","opts":["Changing staff","Structured process for transitioning from current to future state/handling scope changes","Deleting logs","Replacing hardware"],"ans":1},
  {"q":"Project Closure?","opts":["Quitting","Finalizing all activities and formally ending the project","Starting a new one","Archiving files only"],"ans":1},
  {"q":"SWOT Analysis?","opts":["Math tool","Strengths, Weaknesses, Opportunities, Threats","Team, Task, Tool, Goal","Process, Plan, People, Profit"],"ans":1},
  {"q":"Feasibility Study?","opts":["Logic check","Evaluating if a project is technically and financially viable","Testing software","Hiring"],"ans":1},
  {"q":"Vendor Management?","opts":["Selling items","Managing relationships and contracts with third-party suppliers","Choosing employees","Database management"],"ans":1},
  {"q":"Communication Plan?","opts":["Emailing daily","Defining who needs what info, when, and how","Phone list","Meeting notes"],"ans":1},
  {"q":"Kanban Board?","opts":["Strict schedule","Visual tool for workflow management (To Do, Doing, Done)","Code editor","Database index"],"ans":1},
  {"q":"Burn-down Chart?","opts":["Visualizing budget","Visualizing work remaining vs time in a sprint","Bug count","CPU usage"],"ans":1},
  {"q":"MoSCoW Method?","opts":["Travel guide","Prioritization: Must-have, Should-have, Could-have, Won't-have","Logical AND","A search algorithm"],"ans":1},
  {"q":"Daily Stand-up?","opts":["Exercise","Short daily meeting to sync team and discuss progress/blockers","One hour report","Weekly meeting"],"ans":1},
  {"q":"Retrospective?","opts":["Starting project","Meeting after sprint to reflect and improve","Beta testing","Code review"],"ans":1},
  {"q":"Critical Success Factors (CSF)?","opts":["Bug count","Elements necessary for an organization or project to achieve its mission","Total cost","Number of users"],"ans":1},
  {"q":"Procurement Management?","opts":["Finding errors","Acquiring goods and services from external sources","Internal hiring","Writing code"],"ans":1},
  {"q":"Ethics in PM?","opts":["Project cost","Adhering to professional standards (honesty, responsibility, fairness)","Speed of work","Using latest tech"],"ans":1},
  {"q":"Team Dynamics?","opts":["Hardware count","Interpersonal relationships and behaviors within a project team","Computer speed","Logic flows"],"ans":1},
  {"q":"Conflict Resolution?","opts":["Ignoring issues","Handling disagreements constructively","Firing employees","Changing rules"],"ans":1},
  {"q":"Leadership Styles?","opts":["Programming types","Autocratic, Democratic, Laissez-faire, Transformational","CPU types","OS versions"],"ans":1},
  {"q":"Project Management Software?","opts":["Notepad","Tools like Jira, Trello, MS Project, Asana","VLC Player","Web browser"],"ans":1},
  {"q":"Waterfall Model?","opts":["Agile","Sequential project management where each phase must be finished before next begins","Cycling model","Iterative"],"ans":1},
  {"q":"Lean Project Management?","opts":["Complex planning","Focusing on maximizing value while minimizing waste","Adding more tasks","No planning"],"ans":1}
],
}

def build_js_block(subject_key, questions):
    lines = [f'  "{subject_key}": [']
    for i, q in enumerate(questions):
        comma = "," if i < len(questions)-1 else ""
        opts = ', '.join(f'"{o}"' for o in q["opts"])
        lines.append(f'    {{')
        lines.append(f'      "question": "{q["q"]}",')
        lines.append(f'      "options": [{opts}],')
        lines.append(f'      "correctAnswer": {q["ans"]}')
        lines.append(f'    }}{comma}')
    lines.append('  ]')
    return '\n'.join(lines)

out_dir = os.path.join(os.path.dirname(__file__), '..', 'frontend', 'assets')
out_file = os.path.join(out_dir, 'quiz_sem8.js')

blocks = []
keys = list(SEM8.keys())
for i, key in enumerate(keys):
    comma = "," if i < len(keys)-1 else ""
    blocks.append(build_js_block(key, SEM8[key]) + comma)

content = 'const quizDataSem8 = {\n' + '\n'.join(blocks) + '\n};\n'
with open(out_file, 'w', encoding='utf-8') as f:
    f.write(content)

for key, qs in SEM8.items():
    assert len(qs) == 50, f"{key} has {len(qs)} questions"
    texts = [q['q'] for q in qs]
    assert len(set(texts)) == 50, f"{key} has duplicate questions"

print(f"[OK] quiz_sem8.js generated with {len(SEM8)} subjects, 50 questions each.")
