import os

SEM4 = {
"sem4-daa": [
  {"q":"DAA stands for?","opts":["Design and Analysis of Algorithms","Data and Algorithm Architecture","Dynamic Algorithm Analysis","Design of Advanced Applications"],"ans":0},
  {"q":"Big-O notation describes?","opts":["Best case","Average case","Upper bound on time complexity","Exact running time"],"ans":2},
  {"q":"Which sorting algorithm has O(n log n) worst case?","opts":["Quick Sort","Bubble Sort","Merge Sort","Insertion Sort"],"ans":2},
  {"q":"Divide and Conquer works by?","opts":["Greedy choices","Breaking problem into subproblems","Dynamic table","Brute force"],"ans":1},
  {"q":"Dynamic Programming solves problems by?","opts":["Dividing equally","Storing results of subproblems (memoization)","Greedy selection","Backtracking"],"ans":1},
  {"q":"Greedy algorithm makes?","opts":["Globally optimal choices","Locally optimal choices at each step","Random choices","Backtracking choices"],"ans":1},
  {"q":"The activity selection problem is solved by?","opts":["Dynamic programming","Divide and conquer","Greedy algorithm","Backtracking"],"ans":2},
  {"q":"Fibonacci sequence using DP vs recursion is faster because?","opts":["DP uses more memory","DP avoids re-computing overlapping subproblems","DP is random","DP sorts first"],"ans":1},
  {"q":"What is the time complexity of Depth First Search?","opts":["O(V)","O(E)","O(V+E)","O(V×E)"],"ans":2},
  {"q":"Kruskal's algorithm uses which data structure?","opts":["Priority queue","Stack","Union-Find","Hash table"],"ans":2},
  {"q":"What is the 0/1 Knapsack problem approach?","opts":["Greedy","Divide and conquer","Dynamic programming","Backtracking"],"ans":2},
  {"q":"NP-Complete problems are?","opts":["Solvable in polynomial time","In NP and as hard as any NP problem","Not solvable","Easier than NP"],"ans":1},
  {"q":"Which is an NP-Complete problem?","opts":["Sorting","Binary search","Travelling Salesman Problem (decision)","Shortest path"],"ans":2},
  {"q":"P vs NP asks whether?","opts":["P=N×P","Every problem verifiable in poly time is solvable in poly time","NP problems are harder than P","P is empty"],"ans":1},
  {"q":"What is the Master Theorem used for?","opts":["Sorting analysis","Solving recurrence relations for divide-and-conquer","Graph algorithms","DP optimization"],"ans":1},
  {"q":"Backtracking is used to solve?","opts":["Sorting","Shortest path","Constraint satisfaction problems like N-Queens","Minimum spanning tree"],"ans":2},
  {"q":"The longest common subsequence (LCS) uses?","opts":["Greedy","Backtracking","Dynamic programming","Divide and conquer"],"ans":2},
  {"q":"Floyd-Warshall finds?","opts":["Single source shortest path","All-pairs shortest paths","Minimum spanning tree","Maximum flow"],"ans":1},
  {"q":"Bellman-Ford works with?","opts":["Positive weights only","No edge weights","Negative weights (detects negative cycles)","Only undirected graphs"],"ans":2},
  {"q":"Complexity class P contains?","opts":["Undecidable problems","Problems solvable in polynomial time","NP-hard problems","Exponential problems"],"ans":1},
  {"q":"What is amortized analysis?","opts":["Worst-case analysis","Average cost per operation over sequence","Best-case analysis","Probabilistic analysis"],"ans":1},
  {"q":"The fractional knapsack is solved by?","opts":["Dynamic programming","Backtracking","Greedy algorithm","Divide and conquer"],"ans":2},
  {"q":"Strassen's algorithm improves?","opts":["Sorting","Graph traversal","Matrix multiplication","String matching"],"ans":2},
  {"q":"Quick Sort partitions around?","opts":["Median always","Random element always","A pivot element","Smallest element"],"ans":2},
  {"q":"Randomized algorithms use?","opts":["Fixed choices","Random choices to improve average performance","Greedy choices","Dynamic programming"],"ans":1},
  {"q":"What is the optimal substructure property?","opts":["Optimal solution contains optimal solutions to subproblems","Problem can be divided","No overlapping subproblems","Greedy works"],"ans":0},
  {"q":"Overlapping subproblems means?","opts":["Subproblems are independent","Same subproblems solved repeatedly","Subproblems are distinct","Problem is recursive"],"ans":1},
  {"q":"Huffman coding is used for?","opts":["Sorting","Encryption","Lossless data compression","Graph traversal"],"ans":2},
  {"q":"What is a reduction in complexity theory?","opts":["Making algorithm simpler","Transforming one problem to another to prove hardness","Dividing problem","Removing constraints"],"ans":1},
  {"q":"Matrix chain multiplication is solved by?","opts":["Greedy","Divide and conquer","Dynamic programming","Backtracking"],"ans":2},
  {"q":"The edit distance (Levenshtein) problem uses?","opts":["Greedy","Dynamic programming","Divide and conquer","BFS"],"ans":1},
  {"q":"A polynomial time algorithm runs in?","opts":["O(2ⁿ)","O(n!)","O(nᵏ) for some constant k","O(n log n) only"],"ans":2},
  {"q":"What is a fully polynomial time approximation scheme (FPTAS)?","opts":["Exact algorithm","Approximation with error ≤ ε running in poly(n,1/ε)","Heuristic algorithm","Randomized algorithm"],"ans":1},
  {"q":"Which algorithm solves single-source shortest path with non-negative weights?","opts":["Bellman-Ford","Floyd-Warshall","Dijkstra's","DFS"],"ans":2},
  {"q":"B&B (Branch and Bound) is used for?","opts":["Sorting","Optimization problems by eliminating suboptimal branches","Graph traversal","Hashing"],"ans":1},
  {"q":"What is a decision problem?","opts":["Optimization problem","Problem with yes/no answer","Counting problem","Search problem"],"ans":1},
  {"q":"Approximation algorithms provide?","opts":["Exact optimal solution","Solution within guaranteed factor of optimum","Random solution","Best-case solution"],"ans":1},
  {"q":"What is the time complexity of Heap Sort?","opts":["O(n)","O(n²)","O(n log n)","O(log n)"],"ans":2},
  {"q":"Counting sort works in?","opts":["O(n log n)","O(n²)","O(n+k) where k is value range","O(log n)"],"ans":2},
  {"q":"Radix sort is?","opts":["Comparison-based","Non-comparison-based","Random-based","Divide and conquer"],"ans":1},
  {"q":"The Hamiltonian cycle problem is?","opts":["In P","NP-Complete","Solvable greedily","Undecidable"],"ans":1},
  {"q":"What is the purpose of Rabin-Karp algorithm?","opts":["Sorting","String pattern matching using hashing","Shortest path","Compression"],"ans":1},
  {"q":"KMP algorithm's key advantage over naive string search?","opts":["Uses less memory","Avoids re-examining characters using failure function","Runs in O(m+n)... always faster","Uses hashing"],"ans":1},
  {"q":"What is a flow network?","opts":["Graph with edge capacities for max flow","Shortest path graph","Undirected weighted graph","Bipartite graph"],"ans":0},
  {"q":"Ford-Fulkerson algorithm solves?","opts":["Minimum spanning tree","Maximum flow","Shortest path","Topological sort"],"ans":1},
  {"q":"What is a lower bound?","opts":["Upper limit on complexity","Minimum time any algorithm must take","Average case time","Space used"],"ans":1},
  {"q":"Information theoretic lower bound for comparison sorts is?","opts":["O(n)","O(n log n)","O(n²)","O(log n)"],"ans":1},
  {"q":"What is the subset sum problem?","opts":["Finding if any subset sums to target — NP-Complete","Sorting a subset","Finding max element","Minimum sum"],"ans":0},
  {"q":"What is an online algorithm?","opts":["Algorithm running on internet","Algorithm making decisions without future input","Algorithm always optimal","Algorithm with memoization"],"ans":1},
  {"q":"Amortized cost of table doubling is?","opts":["O(n)","O(n²)","O(1) amortized","O(log n)"],"ans":2},
],
"sem4-dbms": [
  {"q":"DBMS stands for?","opts":["Database Management System","Data Base Merge System","Digital Base Management Software","Data Binary Management System"],"ans":0},
  {"q":"Which is a primary key property?","opts":["Can be null","Can have duplicates","Unique and not null","Optional"],"ans":2},
  {"q":"A foreign key?","opts":["Uniquely identifies a row","References primary key of another table","Can have any value","Is always indexed"],"ans":1},
  {"q":"SQL stands for?","opts":["Structured Query Language","Sequential Query Language","Structured Question Language","Simple Query Logic"],"ans":0},
  {"q":"SELECT * FROM table retrieves?","opts":["First row only","All columns and rows","Only primary keys","Selected columns"],"ans":1},
  {"q":"Which SQL command removes all rows without deleting table?","opts":["DELETE","DROP","TRUNCATE","REMOVE"],"ans":2},
  {"q":"DROP TABLE removes?","opts":["All rows","Table structure and data","Only data","Only structure"],"ans":1},
  {"q":"Normalization reduces?","opts":["Query speed","Data redundancy and anomalies","Index count","Table count"],"ans":1},
  {"q":"1NF requires?","opts":["No partial dependencies","Atomic values, no repeating groups","No transitive dependencies","BCNF compliance"],"ans":1},
  {"q":"2NF requires?","opts":["1NF + no partial dependencies on composite key","1NF only","No transitive dependencies","Atomic values"],"ans":0},
  {"q":"3NF requires?","opts":["2NF + no transitive dependencies","1NF only","No partial dependencies","BCNF compliance"],"ans":0},
  {"q":"BCNF is violated when?","opts":["Non-key attribute depends on another non-key attribute","A determinant is not a superkey","Primary key is composite","Foreign key is missing"],"ans":1},
  {"q":"JOIN combines rows from?","opts":["One table","Two or more tables based on related column","Unrelated tables","Columns of same table"],"ans":1},
  {"q":"INNER JOIN returns?","opts":["All rows from both tables","Only matching rows from both tables","Rows from left table only","Rows from right table only"],"ans":1},
  {"q":"LEFT JOIN returns?","opts":["Only matching rows","All rows from left table and matching from right","All rows from right table","No matching rows"],"ans":1},
  {"q":"An index improves?","opts":["Data storage","Query performance","Normalization","Integrity"],"ans":1},
  {"q":"ACID properties stand for?","opts":["Authority, Consistency, Integrity, Data","Atomicity, Consistency, Isolation, Durability","Accuracy, Completeness, Integrity, Delivery","Atomic, Commit, Index, Delete"],"ans":1},
  {"q":"Atomicity in transactions means?","opts":["Transaction is divisible","Transaction is all-or-nothing","Transaction is isolated","Transaction is consistent"],"ans":1},
  {"q":"A view in SQL is?","opts":["Physical table copy","Virtual table based on query","Stored procedure","Index structure"],"ans":1},
  {"q":"Which command starts a transaction?","opts":["START TRANSACTION","BEGIN","COMMIT","ROLLBACK"],"ans":0},
  {"q":"ROLLBACK undoes?","opts":["Committed transactions","Uncommitted transaction changes","Table structure changes","All queries"],"ans":1},
  {"q":"E-R model stands for?","opts":["Entity-Relation","Entity-Relationship","External-Resource","Event-Result"],"ans":1},
  {"q":"A weak entity?","opts":["Has its own primary key","Depends on another entity for identification","Has no attributes","Is always many-to-many"],"ans":1},
  {"q":"Cardinality in ER model refers to?","opts":["Number of attributes","Number of relationships between entities","Degree of normalization","Number of tables"],"ans":1},
  {"q":"GROUP BY clause is used with?","opts":["Individual rows","Aggregate functions","JOIN operations","Subqueries only"],"ans":1},
  {"q":"HAVING clause filters?","opts":["Individual rows before grouping","Groups after aggregation","Table rows","Columns"],"ans":1},
  {"q":"A trigger in DBMS is?","opts":["Manual query","Automatic procedure on table event","Stored procedure","View"],"ans":1},
  {"q":"Deadlock in DBMS occurs when?","opts":["Two transactions complete together","Two transactions wait for each other's locks","Transaction fails","Index is rebuilt"],"ans":1},
  {"q":"Two-phase locking (2PL) ensures?","opts":["No deadlocks","Serializability","Fast transactions","No isolation"],"ans":1},
  {"q":"Data redundancy means?","opts":["Data loss","Same data stored in multiple places","Too many tables","Missing data"],"ans":1},
  {"q":"Which SQL function counts rows?","opts":["SUM()","AVG()","COUNT()","MAX()"],"ans":2},
  {"q":"A stored procedure is?","opts":["A temporary table","Precompiled SQL code stored in DB","An index","A view"],"ans":1},
  {"q":"What is a transaction log?","opts":["Index file","Record of all database changes for recovery","Backup of data","Schema definition"],"ans":1},
  {"q":"Concurrency control manages?","opts":["Single user access","Multiple simultaneous transactions","Index creation","Table creation"],"ans":1},
  {"q":"Timestamp ordering is a concurrency control method that uses?","opts":["Locks","Timestamps to order transactions","Rollbacks only","Validation"],"ans":1},
  {"q":"What is a schema?","opts":["Data itself","Structure/blueprint of database","Index","Query plan"],"ans":1},
  {"q":"A composite key is?","opts":["Foreign key","Primary key made of multiple attributes","Index key","Candidate key"],"ans":1},
  {"q":"A candidate key is?","opts":["Any column","A minimal superkey","Foreign key","Index"],"ans":1},
  {"q":"Data dictionary stores?","opts":["Actual data","Metadata about database structure","Indexes","Transaction logs"],"ans":1},
  {"q":"What is query optimization?","opts":["Writing better SQL","Finding efficient execution plan for a query","Creating indexes","Normalizing tables"],"ans":1},
  {"q":"B+ tree index stores?","opts":["Data only in internal nodes","Data in leaf nodes, internal nodes for routing","Data randomly","No data"],"ans":1},
  {"q":"Which isolation level prevents dirty reads?","opts":["Read Uncommitted","Read Committed","Repeatable Read","Serializable"],"ans":1},
  {"q":"Full outer join returns?","opts":["Only matches","All rows from both tables with NULLs for non-matches","Only left rows","Only right rows"],"ans":1},
  {"q":"What is denormalization?","opts":["Removing normalization to improve read performance","Adding more normal forms","Splitting tables","Adding constraints"],"ans":0},
  {"q":"Which SQL keyword removes duplicates in results?","opts":["UNIQUE","DISTINCT","ONLY","SINGLE"],"ans":1},
  {"q":"Referential integrity ensures?","opts":["Primary keys are unique","Foreign key values reference valid primary key","Tables are normalized","Data is indexed"],"ans":1},
  {"q":"What does DDL stand for?","opts":["Data Definition Language","Data Delivery Language","Dynamic Data Logic","Database Design Language"],"ans":0},
  {"q":"What does DML stand for?","opts":["Data Management Language","Data Manipulation Language","Database Module Logic","Data Migration Language"],"ans":1},
  {"q":"A cursor in DBMS is used to?","opts":["Navigate database files","Process query result rows one at a time","Create tables","Define schemas"],"ans":1},
  {"q":"Star schema is used in?","opts":["OLTP systems","Data warehousing","E-R modeling","Normalization"],"ans":1},
],
"sem4-java": [
  {"q":"Java is?","opts":["Compiled to native code","Platform-dependent","Compiled to bytecode and run on JVM","Interpreted line by line only"],"ans":2},
  {"q":"JVM stands for?","opts":["Java Virtual Memory","Java Virtual Machine","Java Variable Module","Java Version Manager"],"ans":1},
  {"q":"Which keyword defines a class in Java?","opts":["define","struct","class","object"],"ans":2},
  {"q":"Java main method signature?","opts":["void main()","static void main(String args)","public static void main(String[] args)","main(String args[])"],"ans":2},
  {"q":"Which is NOT a Java primitive type?","opts":["int","double","String","boolean"],"ans":2},
  {"q":"What does 'final' keyword mean for a variable?","opts":["It's private","It cannot be reassigned","It's static","It's global"],"ans":1},
  {"q":"Java supports multiple inheritance through?","opts":["Classes","Abstract classes","Interfaces","Constructors"],"ans":2},
  {"q":"The 'extends' keyword is for?","opts":["Implementing interfaces","Class inheritance","Creating objects","Method overriding"],"ans":1},
  {"q":"The 'implements' keyword is for?","opts":["Extending classes","Implementing interfaces","Creating objects","Overloading"],"ans":1},
  {"q":"Method overloading means?","opts":["Same method name, different parameters","Same method name, same parameters","Redefining in subclass","Using super keyword"],"ans":0},
  {"q":"Method overriding means?","opts":["Same method name, different parameters","Redefining superclass method in subclass","Creating new method","Static method re-use"],"ans":1},
  {"q":"Which Java exception is unchecked?","opts":["IOException","SQLException","NullPointerException","ClassNotFoundException"],"ans":2},
  {"q":"try-catch-finally: finally block executes?","opts":["Only on exception","Only on success","Always","Never in try"],"ans":2},
  {"q":"What is an abstract class?","opts":["Class with all methods implemented","Class that cannot be instantiated and may have abstract methods","Final class","Static class"],"ans":1},
  {"q":"An interface in Java 8+ can have?","opts":["Only abstract methods","Default and static methods too","Constructors","Instance fields"],"ans":1},
  {"q":"What is encapsulation?","opts":["Inheriting from superclass","Hiding internal data using access modifiers","Overriding methods","Implementing multiple interfaces"],"ans":1},
  {"q":"Which access modifier restricts to same class only?","opts":["public","protected","default","private"],"ans":3},
  {"q":"What does 'static' mean in Java?","opts":["Object-level member","Class-level member shared among all instances","Final member","Abstract member"],"ans":1},
  {"q":"Which collection maintains insertion order and allows duplicates?","opts":["HashSet","TreeSet","ArrayList","HashMap"],"ans":2},
  {"q":"HashMap stores?","opts":["Ordered key-value pairs","Unordered key-value pairs","Sorted keys","No duplicates in values"],"ans":1},
  {"q":"What is a constructor?","opts":["Method that returns object","Special method called on object creation","Static factory method","Abstract method"],"ans":1},
  {"q":"'super' keyword refers to?","opts":["Current class","Parent class","Interface","Static context"],"ans":1},
  {"q":"'this' keyword refers to?","opts":["Parent class","Static context","Current object instance","Interface"],"ans":2},
  {"q":"What is a generic type in Java?","opts":["Type that works with any data type","Type for generics only","Abstract type","Primitive type"],"ans":0},
  {"q":"Lambda expression syntax in Java?","opts":["(params) -> body","params => body","def(params): body","fn params: body"],"ans":0},
  {"q":"Stream API in Java is used for?","opts":["Networking","Functional-style operations on collections","File I/O","Database access"],"ans":1},
  {"q":"Which keyword prevents subclassing?","opts":["abstract","private","final","static"],"ans":2},
  {"q":"What is the purpose of 'synchronized' in Java?","opts":["Makes method abstract","Prevents concurrent thread access","Makes method static","Adds caching"],"ans":1},
  {"q":"What is a thread in Java?","opts":["New process","Light-weight unit of execution within a process","Operating system process","JVM instance"],"ans":1},
  {"q":"Which interface must be implemented for a class to be runnable?","opts":["Callable","Comparable","Runnable","Serializable"],"ans":2},
  {"q":"What does garbage collection do in Java?","opts":["Removes unused files","Automatically frees unused objects in memory","Optimizes code","Handles exceptions"],"ans":1},
  {"q":"String in Java is?","opts":["Mutable","Primitive","Immutable","Dynamic"],"ans":2},
  {"q":"StringBuilder differs from String in that it is?","opts":["Immutable","Thread-safe","Mutable","Always synchronized"],"ans":2},
  {"q":"Comparable interface is used for?","opts":["Copying objects","Natural ordering of objects","Comparison with lambda","Sorting only with Comparator"],"ans":1},
  {"q":"What is polymorphism?","opts":["One class, one method","Same method name behaves differently based on object type","Multiple inheritance","Method hiding"],"ans":1},
  {"q":"What is an Iterator?","opts":["Random access tool","Object to traverse collections sequentially","Sorting algorithm","Hashing tool"],"ans":1},
  {"q":"Optional class in Java is used to?","opts":["Make variables optional in declarations","Avoid NullPointerException by wrapping nullable values","Replace collections","Implement generics"],"ans":1},
  {"q":"What is the difference between == and .equals() for Strings?","opts":["No difference","== compares references, .equals() compares content","== compares content, .equals() compares references","Both compare content"],"ans":1},
  {"q":"Which Java collection does not allow null keys?","opts":["HashMap","LinkedHashMap","TreeMap","Hashtable"],"ans":3},
  {"q":"What is autoboxing?","opts":["Converting primitive to wrapper type automatically","Converting wrapper to primitive","Creating arrays","Casting types"],"ans":0},
  {"q":"What is the factory method pattern?","opts":["Create objects via static factory method instead of constructor","Singleton pattern","Observer pattern","Decorator pattern"],"ans":0},
  {"q":"What does 'throws' keyword in method signature mean?","opts":["Method throws exception always","Method may throw specified checked exception","Creates exception object","Catches exception"],"ans":1},
  {"q":"What is instanceof keyword used for?","opts":["Creating instances","Casting types","Checking if object is instance of class/interface","Comparing values"],"ans":2},
  {"q":"Checked exceptions must be?","opts":["Caught or declared in throws","Ignored","Unchecked","Runtime exceptions"],"ans":0},
  {"q":"What is the Singleton design pattern?","opts":["Multiple instances of a class","Only one instance of a class","Abstract factory","Prototype pattern"],"ans":1},
  {"q":"What does Collections.sort() use by default?","opts":["Quick sort","Insertion sort","Merge sort (TimSort)","Heap sort"],"ans":2},
  {"q":"What is reflection in Java?","opts":["Mirroring UI","Inspecting/modifying classes at runtime","Copying objects","Serialization"],"ans":1},
  {"q":"What does Serializable interface enable?","opts":["Multi-threading","Object conversion to byte stream","Network communication only","Sorting"],"ans":1},
  {"q":"What is the JDK?","opts":["Java Runtime only","Java Development Kit including compiler and tools","Java Virtual Machine","Java Documentation Kit"],"ans":1},
  {"q":"Which loop was introduced in Java 5 for collections?","opts":["do-while","for(;;)","Enhanced for-each loop","Iterator loop"],"ans":2},
],
"sem4-se": [
  {"q":"SE stands for?","opts":["System Engineering","Software Engineering","Software Environment","System Execution"],"ans":1},
  {"q":"SDLC stands for?","opts":["Software Data Life Cycle","Software Development Life Cycle","System Design Logic Control","Software Deployment and Launch Cycle"],"ans":1},
  {"q":"Which SDLC model uses sequential phases?","opts":["Agile","Spiral","Waterfall","Prototype"],"ans":2},
  {"q":"Agile methodology emphasizes?","opts":["Rigid planning","Customer collaboration and iterative delivery","Documentation over code","Long release cycles"],"ans":1},
  {"q":"Scrum is a framework for?","opts":["Testing only","Project management using agile principles","Database design","UI development"],"ans":1},
  {"q":"A Sprint in Scrum is?","opts":["Final release","Time-boxed iteration (1-4 weeks)","Bug fixing phase","Planning meeting"],"ans":1},
  {"q":"What is a use case?","opts":["Test case","Description of system functionality from user perspective","Database schema","Deployment plan"],"ans":1},
  {"q":"SRS stands for?","opts":["Software Resource Specification","Software Requirements Specification","System Runtime Specification","Software Release Summary"],"ans":1},
  {"q":"Which diagram shows system interactions between actors and system?","opts":["Class diagram","Sequence diagram","Use case diagram","Activity diagram"],"ans":2},
  {"q":"Cohesion in software design means?","opts":["Degree of dependency between modules","Degree to which a module has a single well-defined purpose","Number of modules","Code reuse level"],"ans":1},
  {"q":"Coupling refers to?","opts":["Single purpose of module","Degree of interdependency between modules","Number of classes","Test coverage"],"ans":1},
  {"q":"High cohesion and low coupling is?","opts":["Bad design","Best design practice","Average design","Only for small projects"],"ans":1},
  {"q":"What is a design pattern?","opts":["UI template","Reusable solution to common software design problems","Coding standard","Test template"],"ans":1},
  {"q":"Which testing verifies individual units of code?","opts":["Integration testing","System testing","Unit testing","Acceptance testing"],"ans":2},
  {"q":"Regression testing is?","opts":["Testing new features only","Re-testing after changes to ensure nothing is broken","Performance testing","Security testing"],"ans":1},
  {"q":"Black-box testing?","opts":["Tests internal code structure","Tests functionality without knowledge of internal code","Tests with full code knowledge","Tests hardware"],"ans":1},
  {"q":"White-box testing?","opts":["Tests without internal knowledge","Tests internal code structure with full knowledge","Tests hardware","Tests documentation"],"ans":1},
  {"q":"What is version control?","opts":["Controlling application version number","Managing changes to source code over time","Testing versions","Deployment management"],"ans":1},
  {"q":"Git is a?","opts":["Centralized version control","Distributed version control system","Project management tool","Testing tool"],"ans":1},
  {"q":"What is technical debt?","opts":["Financial cost of software","Cost of rework from poor design choices made for short-term gain","Bug count","Test coverage deficit"],"ans":1},
  {"q":"UML stands for?","opts":["Universal Modeling Language","Unified Modeling Language","Unified Module Language","Universal Module Loader"],"ans":1},
  {"q":"A class diagram shows?","opts":["Sequence of method calls","Classes, attributes, and relationships","Use cases","Deployment architecture"],"ans":1},
  {"q":"What is refactoring?","opts":["Adding new features","Restructuring existing code without changing external behavior","Bug fixing","Testing"],"ans":1},
  {"q":"CI/CD stands for?","opts":["Code Integration/Code Deployment","Continuous Integration/Continuous Delivery","Critical Issues/Code Debug","Component Interface/Continuous Deployment"],"ans":1},
  {"q":"What is a software prototype?","opts":["Final product","Early working model to gather feedback","Documentation","Test plan"],"ans":1},
  {"q":"The spiral model emphasizes?","opts":["Sequential phases","Risk analysis at each iteration","No risk management","Agile sprints"],"ans":1},
  {"q":"What is code review?","opts":["Running tests","Manual inspection of code by peers","Automated analysis","Documentation check"],"ans":1},
  {"q":"Functional requirements describe?","opts":["Performance constraints","What the system should do","Hardware requirements","Security policies"],"ans":1},
  {"q":"Non-functional requirements include?","opts":["User login functionality","Performance, scalability, security","Business logic","Database schema"],"ans":1},
  {"q":"What is a burndown chart?","opts":["CI/CD pipeline","Chart tracking remaining work in sprint","Bug tracking chart","Resource allocation chart"],"ans":1},
  {"q":"MVP in software development means?","opts":["Most Valuable Product","Minimum Viable Product","Maximum Value Product","Most Visible Product"],"ans":1},
  {"q":"What is pair programming?","opts":["Two separate coders working independently","Two developers working on same code at one workstation","Remote collaboration","Code review process"],"ans":1},
  {"q":"Test-driven development (TDD) means?","opts":["Write tests after code","Write tests before writing code","Only do automated tests","Skip unit tests"],"ans":1},
  {"q":"What is software maintenance?","opts":["Initial development","Modifying software after delivery to fix bugs, improve, adapt","Documentation only","Testing only"],"ans":1},
  {"q":"Static analysis tools?","opts":["Run tests","Analyze code without executing it","Run code","Deploy code"],"ans":1},
  {"q":"What is a product backlog in Scrum?","opts":["Bug list","Prioritized list of features/requirements","Sprint tasks only","Test cases"],"ans":1},
  {"q":"DevOps integrates?","opts":["Design and testing","Development and operations","Documentation and coding","UI and backend"],"ans":1},
  {"q":"Kanban is a?","opts":["Fixed sprint framework","Visual workflow management system","Testing methodology","Documentation standard"],"ans":1},
  {"q":"What is a software architecture?","opts":["UI design","High-level structure of software system","Database design","Algorithm selection"],"ans":1},
  {"q":"SOA stands for?","opts":["Software Object Architecture","Service-Oriented Architecture","System Operation Analysis","Software Output Action"],"ans":1},
  {"q":"What does API stand for?","opts":["Application Performance Index","Application Programming Interface","Automated Program Integration","Application Process Interface"],"ans":1},
  {"q":"Which UML diagram shows order of method calls?","opts":["Class diagram","Use case diagram","Sequence diagram","State diagram"],"ans":2},
  {"q":"What is risk management in SE?","opts":["Managing money risks","Identifying and mitigating software project risks","Test management","Deployment management"],"ans":1},
  {"q":"An ERD is used for?","opts":["Software architecture","Database design modeling entities and relationships","UI design","API documentation"],"ans":1},
  {"q":"What are acceptance criteria?","opts":["Bug count limits","Conditions that a feature must meet to be accepted","Performance benchmarks","Code coverage requirements"],"ans":1},
  {"q":"COCOMO model is used for?","opts":["Test management","Software cost and effort estimation","Bug tracking","Version control"],"ans":1},
  {"q":"What is smoke testing?","opts":["Performance testing","Quick high-level test to see if build is stable","Security testing","Regression testing"],"ans":1},
  {"q":"What is the product owner role in Scrum?","opts":["Technical lead","Person responsible for product backlog and value","Scrum facilitator","Developer"],"ans":1},
  {"q":"Feature-driven development (FDD) focuses on?","opts":["Sprint-based delivery","Delivering features incrementally","Risk analysis","Waterfall phases"],"ans":1},
  {"q":"What is spaghetti code?","opts":["Modular code","Complex, tangled code with poor structure","Test code","Documentation"],"ans":1},
],
"sem4-web-tech": [
  {"q":"HTML stands for?","opts":["High Text Markup Language","HyperText Markup Language","Hyperlink Text Management Language","High Transfer Markup Language"],"ans":1},
  {"q":"CSS stands for?","opts":["Cascading Style Sheets","Computer Style Sheets","Creative Style Script","Cascading Script Sheets"],"ans":0},
  {"q":"Which HTML tag creates a hyperlink?","opts":["<link>","<href>","<a>","<url>"],"ans":2},
  {"q":"The DOCTYPE declaration in HTML5 is?","opts":["<!DOCTYPE HTML5>","<!DOCTYPE html>","<html DOCTYPE>","<html5>"],"ans":1},
  {"q":"Which CSS property changes text color?","opts":["font-color","text-color","color","foreground"],"ans":2},
  {"q":"JavaScript is primarily?","opts":["Server-side only","Client-side scripting language","Compiled language","Database query language"],"ans":1},
  {"q":"What does DOM stand for?","opts":["Document Object Model","Data Object Module","Document Operation Model","Dynamic Object Management"],"ans":0},
  {"q":"Which HTTP method is used to send form data securely?","opts":["GET","HEAD","POST","DELETE"],"ans":2},
  {"q":"What is a cookie?","opts":["Browser history","Small data stored on client by server","Server-side session","Cache data"],"ans":1},
  {"q":"JSON stands for?","opts":["Java Script Online Notation","JavaScript Object Notation","Java Serial Object Notation","JavaScript Output Number"],"ans":1},
  {"q":"What is AJAX?","opts":["A Java framework","Asynchronous JavaScript and XML — async web updates","A CSS preprocessor","A server technology"],"ans":1},
  {"q":"What is the box model in CSS?","opts":["Content, padding, border, margin","Content and border only","Margin and content","Content and padding"],"ans":0},
  {"q":"Which HTML element is for JavaScript code?","opts":["<js>","<javascript>","<script>","<code>"],"ans":2},
  {"q":"What is a responsive design?","opts":["Fast loading design","Design adapting to different screen sizes","Animated design","Server-side rendering"],"ans":1},
  {"q":"Which CSS unit is relative to viewport width?","opts":["px","em","rem","vw"],"ans":3},
  {"q":"Flexbox in CSS is used for?","opts":["Animations","One-dimensional layout","Grid layout","Typography"],"ans":1},
  {"q":"CSS Grid is used for?","opts":["Animations","One-dimensional layout","Two-dimensional layout","Typography"],"ans":2},
  {"q":"What does REST stand for?","opts":["Representational State Transfer","Remote Execution State Transfer","Real-time Event State Transfer","Representational Server Transfer"],"ans":0},
  {"q":"Which HTML tag creates an ordered list?","opts":["<ul>","<li>","<ol>","<list>"],"ans":2},
  {"q":"What is Node.js?","opts":["Frontend JavaScript framework","JavaScript runtime on server-side","Database","CSS preprocessor"],"ans":1},
  {"q":"Which is a JavaScript framework?","opts":["Laravel","Django","React","Flask"],"ans":2},
  {"q":"The 'async/await' in JavaScript is for?","opts":["Synchronous code","Handling promises more cleanly","DOM manipulation","CSS animations"],"ans":1},
  {"q":"What is a Promise in JavaScript?","opts":["A guarantee of output","Object representing future completion or failure of async operation","A callback function","An event listener"],"ans":1},
  {"q":"What is localStorage?","opts":["Server-side storage","Client-side key-value storage persisting across sessions","Session-only storage","Cookie storage"],"ans":1},
  {"q":"PHP is primarily?","opts":["Client-side scripting","Database management","Server-side scripting language","CSS processor"],"ans":2},
  {"q":"SQL injection is?","opts":["A valid SQL technique","Malicious SQL code inserted into input fields","Database backup method","SQL optimization"],"ans":1},
  {"q":"HTTPS differs from HTTP by?","opts":["Faster speed","Adding SSL/TLS encryption","Different port only","Using POST method"],"ans":1},
  {"q":"What is a CDN?","opts":["Content Delivery Network — distributed servers for faster content delivery","Code Deployment Node","Central Data Node","Content Development Network"],"ans":0},
  {"q":"Which tag defines the body of an HTML page?","opts":["<head>","<main>","<body>","<section>"],"ans":2},
  {"q":"What is CORS?","opts":["Cross-Origin Resource Sharing — controls cross-domain requests","Content Origin Restriction System","Cross-Origin Rendering Service","Cascading Object Resource System"],"ans":0},
  {"q":"event.preventDefault() in JavaScript?","opts":["Stops event bubbling","Prevents default browser action for event","Removes event listener","Stops all events"],"ans":1},
  {"q":"What is event bubbling in JavaScript?","opts":["Event starts at target and bubbles up to ancestors","Event starts at root and goes down","Event fires multiple times","Event is cancelled"],"ans":0},
  {"q":"Which HTML5 API allows offline web apps?","opts":["WebSocket","Web Workers","Service Workers/AppCache","Canvas"],"ans":2},
  {"q":"What does the 'defer' attribute on script tag do?","opts":["Runs script immediately","Loads script after HTML parsing","Blocks HTML parsing","Caches the script"],"ans":1},
  {"q":"What is a SPA?","opts":["Server-side PHP Application","Single Page Application","Static Public Asset","Secure Page Application"],"ans":1},
  {"q":"What does enctype='multipart/form-data' enable?","opts":["Text-only forms","File upload in forms","JSON submission","Encrypted forms"],"ans":1},
  {"q":"What is WebSocket?","opts":["HTTP extension","Full-duplex communication protocol over TCP","REST API","Server-side script"],"ans":1},
  {"q":"What is the purpose of meta viewport tag?","opts":["Set page title","Control layout on mobile devices","Load CSS","Set charset"],"ans":1},
  {"q":"Semantic HTML means?","opts":["Using any tags for layout","Using meaningful tags that describe content (header, nav, article)","Using only div and span","Using JavaScript"],"ans":1},
  {"q":"Which CSS selector selects by class?","opts":["#classname",".classname","classname","*classname"],"ans":1},
  {"q":"Which CSS selector selects by ID?","opts":[".idname","#idname","idname","*idname"],"ans":1},
  {"q":"What is a media query in CSS?","opts":["Database query","CSS rule applying styles based on device conditions","JavaScript query","API request"],"ans":1},
  {"q":"What is webpack?","opts":["A testing framework","Module bundler for JavaScript","CSS preprocessor","Database ORM"],"ans":1},
  {"q":"What does npm stand for?","opts":["Node Package Manager","New Programming Module","Network Package Management","Node Process Manager"],"ans":0},
  {"q":"What is SSR in web development?","opts":["Server-Side Rendering","Static Site Rendering","Secure Socket Response","Slow Script Rendering"],"ans":0},
  {"q":"What is GraphQL?","opts":["A database","A query language for APIs","A JavaScript framework","A CSS tool"],"ans":1},
  {"q":"Which tag makes text bold in HTML5?","opts":["<b>","<bold>","<strong>","Both <b> and <strong>"],"ans":3},
  {"q":"What is the purpose of the alt attribute in img tags?","opts":["Image title","Alternative text for accessibility and broken images","CSS class","Image link"],"ans":1},
  {"q":"What is a JWT?","opts":["Java Web Token","JSON Web Token — compact self-contained token for auth","JavaScript Widget Tool","Joint Web Transfer"],"ans":1},
  {"q":"What does localhost refer to?","opts":["Remote server","The local machine itself","Internet gateway","Router"],"ans":1},
],
}

def build_js_block(subject_key, questions):
    lines = [f'  "{subject_key}": [']
    for i, q in enumerate(questions):
        comma = "," if i < len(questions)-1 else ""
        opts = ', '.join(f'"{o}"' for o in q["opts"])
        lines.append(f'    {{')
        lines.append(f'      "question": "{q["q"]}",')
        lines.append(f'      "options": [{opts}],')
        lines.append(f'      "correctAnswer": {q["ans"]}')
        lines.append(f'    }}{comma}')
    lines.append('  ]')
    return '\n'.join(lines)

out_dir = os.path.join(os.path.dirname(__file__), '..', 'frontend', 'assets')
out_file = os.path.join(out_dir, 'quiz_sem4.js')

blocks = []
keys = list(SEM4.keys())
for i, key in enumerate(keys):
    comma = "," if i < len(keys)-1 else ""
    blocks.append(build_js_block(key, SEM4[key]) + comma)

content = 'const quizDataSem4 = {\n' + '\n'.join(blocks) + '\n};\n'
with open(out_file, 'w', encoding='utf-8') as f:
    f.write(content)

for key, qs in SEM4.items():
    assert len(qs) == 50, f"{key} has {len(qs)} questions"
    texts = [q['q'] for q in qs]
    assert len(set(texts)) == 50, f"{key} has duplicate questions"

print(f"[OK] quiz_sem4.js generated with {len(SEM4)} subjects, 50 questions each.")
