import os

SEM3 = {
"sem3-python": [
  {"q":"Which keyword defines a function in Python?","opts":["func","def","function","define"],"ans":1},
  {"q":"What is the output of type(3.14)?","opts":["int","float","str","double"],"ans":1},
  {"q":"Which symbol is used for single-line comments in Python?","opts":["//","/*","#","--"],"ans":2},
  {"q":"What does len() do?","opts":["Deletes a list","Returns length of sequence","Sorts a list","Reverses a list"],"ans":1},
  {"q":"Python list is?","opts":["Immutable","Ordered and mutable","Unordered","Immutable sequence"],"ans":1},
  {"q":"A tuple in Python is?","opts":["Mutable","Ordered and immutable","Unordered mutable","Sorted"],"ans":1},
  {"q":"Which data type stores key-value pairs in Python?","opts":["List","Set","Tuple","Dictionary"],"ans":3},
  {"q":"Python uses which type of scoping?","opts":["Dynamic only","Static only","LEGB (Local, Enclosing, Global, Built-in)","Block scoping"],"ans":2},
  {"q":"What does 'pass' do in Python?","opts":["Exits function","Skips to next iteration","Does nothing (placeholder)","Raises exception"],"ans":2},
  {"q":"What is a lambda in Python?","opts":["Named function","Multi-line function","Anonymous function","Class method"],"ans":2},
  {"q":"Which built-in function sorts a list in place?","opts":["sorted()","order()","arrange()","list.sort()"],"ans":3},
  {"q":"What does 'self' represent in a Python class?","opts":["Global variable","Class itself","Instance of the class","Function parameter"],"ans":2},
  {"q":"Which exception is raised for division by zero?","opts":["ValueError","TypeError","ZeroDivisionError","ArithmeticError"],"ans":2},
  {"q":"What is list comprehension?","opts":["Loop over dict","Compact way to create lists","Sorting algorithm","Method to delete lists"],"ans":1},
  {"q":"What does 'import os' do?","opts":["Imports operating system kernel","Imports the os module","Starts OS","Creates OS variable"],"ans":1},
  {"q":"The keyword to define a class in Python?","opts":["def","struct","class","object"],"ans":2},
  {"q":"What is inheritance in Python?","opts":["Class using methods of another class","Function calling itself","Module importing","Exception handling"],"ans":0},
  {"q":"Which Python keyword is used for exception handling?","opts":["catch","handle","except","error"],"ans":2},
  {"q":"What does open('file.txt', 'r') do?","opts":["Creates new file","Opens file for reading","Writes to file","Deletes file"],"ans":1},
  {"q":"What is a generator in Python?","opts":["Class factory","Function using yield for lazy iteration","List creator","Module importer"],"ans":1},
  {"q":"Which method adds an element to the END of a list?","opts":["insert()","add()","append()","extend()"],"ans":2},
  {"q":"What does the 'in' keyword do?","opts":["Imports module","Checks membership","Defines loop variable","Arithmetic"],"ans":1},
  {"q":"What is the output of bool('')?","opts":["True","False","None","Error"],"ans":1},
  {"q":"Which module is used for regular expressions in Python?","opts":["regex","re","regexp","match"],"ans":1},
  {"q":"The 'global' keyword in Python?","opts":["Creates global function","Allows modifying global variable inside function","Imports global module","Declares global class"],"ans":1},
  {"q":"What is a decorator in Python?","opts":["A class wrapper","Function that modifies another function","A type of loop","An exception handler"],"ans":1},
  {"q":"The __init__ method is called when?","opts":["Deletion of object","Accessing method","Creating an object","Importing module"],"ans":2},
  {"q":"What does zip() do in Python?","opts":["Compresses files","Pairs elements from multiple iterables","Sorts two lists together","Concatenates lists"],"ans":1},
  {"q":"Which is an immutable sequence type?","opts":["List","Dictionary","Set","Tuple"],"ans":3},
  {"q":"What does 'continue' do in a loop?","opts":["Exits the loop","Skips rest of current iteration","Pauses loop","Restarts from beginning"],"ans":1},
  {"q":"How do you concatenate strings in Python?","opts":["Using &","Using +","Using .concat()","Using ,"],"ans":1},
  {"q":"Which built-in function converts string to int?","opts":["integer()","int()","str()","float()"],"ans":1},
  {"q":"What is a set in Python?","opts":["Ordered mutable collection with duplicates","Unordered collection of unique elements","Ordered immutable collection","Key-value pairs"],"ans":1},
  {"q":"Python's 'is' operator checks?","opts":["Value equality","Identity (same object)","Type equality","String equality"],"ans":1},
  {"q":"What does enumerate() return?","opts":["Just values","Just indices","Index-value pairs","Reversed list"],"ans":2},
  {"q":"Which access modifier is indicated by double underscore (__)?","opts":["Public","Protected","Private (name mangling)","Static"],"ans":2},
  {"q":"What is polymorphism in Python?","opts":["Single class multiple instances","Same method works on different types","Multiple inheritance","Lambda functions"],"ans":1},
  {"q":"What does map() do in Python?","opts":["Creates dictionary","Applies function to all items in iterable","Filters items","Sorts items"],"ans":1},
  {"q":"What is the difference between '==' and 'is'?","opts":["No difference","'==' compares values, 'is' compares identity","'is' compares values, '==' compares identity","Both compare identity"],"ans":1},
  {"q":"Which module is used for JSON in Python?","opts":["jsonlib","jsonio","json","simplejson"],"ans":2},
  {"q":"What does *args in function definition mean?","opts":["Multiple keyword arguments","Variable positional arguments","Single argument","Default argument"],"ans":1},
  {"q":"What does **kwargs in function definition mean?","opts":["Variable positional arguments","Variable keyword arguments","Keyword only arguments","Default dict argument"],"ans":1},
  {"q":"What is the scope of a variable defined inside a function?","opts":["Global","Module-level","Local","Built-in"],"ans":2},
  {"q":"What does filter() return?","opts":["List","Filter object with items where function returns True","Sorted list","None"],"ans":1},
  {"q":"Which method removes and returns the last element of a list?","opts":["remove()","delete()","pop()","discard()"],"ans":2},
  {"q":"What is a context manager in Python?","opts":["Manages memory allocation","Object supporting 'with' statement","Thread manager","Event handler"],"ans":1},
  {"q":"What does os.path.join() do?","opts":["Joins two lists","Creates OS path string","Joins strings","Concatenates file content"],"ans":1},
  {"q":"What is duck typing?","opts":["Using ducks as objects","Type checking by behavior not type","Strict type checking","Static typing"],"ans":1},
  {"q":"What is PEP 8?","opts":["Python Enhancement Proposal for style guide","Python Extension Protocol","Python Error Protocol","Python Execution Plan"],"ans":0},
  {"q":"What does 'assert' do in Python?","opts":["Assigns value","Raises AssertionError if condition is False","Prints a value","Defines a condition"],"ans":1},
],
"sem3-cn": [
  {"q":"CN stands for?","opts":["Computer Networks","Circuit Networks","Computing Nodes","Communication Networks"],"ans":0},
  {"q":"The OSI model has how many layers?","opts":["4","5","6","7"],"ans":3},
  {"q":"Which layer is responsible for routing?","opts":["Data Link","Network","Transport","Session"],"ans":1},
  {"q":"IP address version 4 is how many bits?","opts":["16","32","64","128"],"ans":1},
  {"q":"What does DNS stand for?","opts":["Domain Name System","Data Network Service","Digital Network Switch","Distributed Name Server"],"ans":0},
  {"q":"HTTP operates at which layer?","opts":["Transport","Network","Application","Physical"],"ans":2},
  {"q":"TCP provides which type of service?","opts":["Connectionless","Unreliable","Connection-oriented reliable","Best-effort"],"ans":2},
  {"q":"UDP is preferred for?","opts":["File transfer","Email","Low-latency streaming","Database queries"],"ans":2},
  {"q":"What is the default port for HTTPS?","opts":["80","21","22","443"],"ans":3},
  {"q":"What is subnetting?","opts":["Joining two networks","Dividing a network into smaller parts","Encrypting network traffic","Routing between networks"],"ans":1},
  {"q":"The MAC address is found at which layer?","opts":["Network","Transport","Data Link","Physical"],"ans":2},
  {"q":"What is a router?","opts":["Connects devices in LAN","Forwards packets between networks","Amplifies signal","Converts protocols"],"ans":1},
  {"q":"What does ARP stand for?","opts":["Address Resolution Protocol","Access Router Protocol","Automatic Routing Protocol","Address Register Protocol"],"ans":0},
  {"q":"What is the function of DHCP?","opts":["Resolves domain names","Assigns IP addresses dynamically","Encrypts traffic","Routes packets"],"ans":1},
  {"q":"Which protocol is used for email sending?","opts":["POP3","IMAP","SMTP","FTP"],"ans":2},
  {"q":"What is bandwidth?","opts":["Length of cable","Maximum data transfer rate","Signal frequency","Network delay"],"ans":1},
  {"q":"What is latency?","opts":["Data transfer rate","Delay in data transmission","Network reliability","Packet size"],"ans":1},
  {"q":"IPv6 address is how many bits?","opts":["32","64","96","128"],"ans":3},
  {"q":"What is a firewall?","opts":["Physical barrier","Security system monitoring network traffic","Router configuration","Encryption algorithm"],"ans":1},
  {"q":"The three-way handshake is used in?","opts":["UDP","ARP","TCP connection establishment","DNS lookup"],"ans":2},
  {"q":"What does NAT stand for?","opts":["Network Address Translation","Network Access Terminal","Node Address Table","Network Allocation Transfer"],"ans":0},
  {"q":"What is a hub?","opts":["Intelligent packet forwarder","Broadcasts data to all ports","Routes between networks","Encrypts data"],"ans":1},
  {"q":"What is a switch?","opts":["Broadcasts to all ports","Forwards data using MAC address","Routes between networks","Amplifies signals"],"ans":1},
  {"q":"What is CSMA/CD?","opts":["Collision detection in wireless","Collision detection in Ethernet","Circuit switching method","Channel assignment"],"ans":1},
  {"q":"Which topology has a central hub?","opts":["Bus","Ring","Star","Mesh"],"ans":2},
  {"q":"What is a VPN?","opts":["Virtual Private Network","Very Public Node","Verified Packet Network","Virtual Protocol Node"],"ans":0},
  {"q":"FTP uses which port by default?","opts":["20/21","80","443","25"],"ans":0},
  {"q":"What is packet switching?","opts":["Circuit-based communication","Data divided into packets routed independently","Broadcasting","Fixed path communication"],"ans":1},
  {"q":"What is TTL in IP packets?","opts":["Total Transfer Limit","Time To Live — limits packet lifespan","Transfer Type Label","Total Traffic Load"],"ans":1},
  {"q":"Which is a connectionless protocol?","opts":["TCP","FTP","HTTP (over TCP)","UDP"],"ans":3},
  {"q":"What is ICMP used for?","opts":["File transfer","Email","Error reporting and diagnostics (ping)","Web browsing"],"ans":2},
  {"q":"What does SSL/TLS provide?","opts":["Routing","Encryption and security","IP addressing","Domain resolution"],"ans":1},
  {"q":"A Class C IP address supports how many hosts?","opts":["65534","254","16777214","2"],"ans":1},
  {"q":"What is a broadcast address?","opts":["Loopback address","Address that sends data to all hosts","Gateway address","Multicast address"],"ans":1},
  {"q":"What is OSPF?","opts":["A link-state routing protocol","A distance-vector protocol","A transport protocol","A session protocol"],"ans":0},
  {"q":"BGP is used for?","opts":["Internal routing","Inter-AS (Internet) routing","LAN communication","Wireless routing"],"ans":1},
  {"q":"The loopback address is?","opts":["192.168.0.1","0.0.0.0","255.255.255.255","127.0.0.1"],"ans":3},
  {"q":"What is multiplexing?","opts":["Combining multiple signals over one channel","Splitting a signal","Encrypting a signal","Amplifying a signal"],"ans":0},
  {"q":"What is the sliding window protocol used for?","opts":["Error detection","Flow control","Routing","Encryption"],"ans":1},
  {"q":"What is VLAN?","opts":["Virtual LAN — logical network segmentation","Very Large Area Network","Variable Length Address Network","Virtual Link Access Node"],"ans":0},
  {"q":"What is the purpose of the transport layer?","opts":["Routing","End-to-end communication and reliability","Physical transmission","Encryption"],"ans":1},
  {"q":"HTTP status code 404 means?","opts":["Server error","Resource not found","Redirect","Unauthorized"],"ans":1},
  {"q":"What is QoS?","opts":["Quality of Service — prioritizing network traffic","Quick Output System","Query over Switch","Quality of Software"],"ans":0},
  {"q":"A gateway connects?","opts":["Two LANs","Networks using different protocols","Two computers","Two servers"],"ans":1},
  {"q":"What is the data unit at the network layer?","opts":["Frame","Segment","Packet","Bit"],"ans":2},
  {"q":"What is a repeat er in networking?","opts":["Stores data","Amplifies and retransmits signals","Routes packets","Encrypts data"],"ans":1},
  {"q":"What is the port number for SSH?","opts":["21","22","23","80"],"ans":1},
  {"q":"Ethernet is a standard for?","opts":["Wireless LAN","Wired LAN","WAN routing","Internet protocol"],"ans":1},
  {"q":"What is a socket?","opts":["Hardware connector","IP address only","Endpoint of network communication (IP+port)","Physical network card"],"ans":2},
  {"q":"What does HTTP stand for?","opts":["HyperText Transfer Process","HyperText Transfer Protocol","High Transfer Text Protocol","Hyperlink Text Transfer Protocol"],"ans":1},
],
"sem3-mfcs": [
  {"q":"MFCS stands for?","opts":["Mathematical Foundations of Computer Science","Modern Formal Computing Systems","Machine Function Control System","Multi-Function Computing Science"],"ans":0},
  {"q":"A proposition is?","opts":["A command","A question","A statement that is true or false","An expression"],"ans":2},
  {"q":"The negation of 'P AND Q' is?","opts":["NOT P AND NOT Q","NOT P OR NOT Q","P OR Q","NOT(P OR Q)"],"ans":1},
  {"q":"Which rule: (P→Q) ≡ (¬P∨Q)?","opts":["De Morgan's","Material implication","Modus Ponens","Contrapositive"],"ans":1},
  {"q":"A tautology is a formula that is?","opts":["Always false","Sometimes true","Always true","Context dependent"],"ans":2},
  {"q":"Modus Ponens: If P→Q and P, then?","opts":["¬Q","¬P","Q","P∧Q"],"ans":2},
  {"q":"The set of positive integers is?","opts":["Finite","Uncountably infinite","Countably infinite","Empty"],"ans":2},
  {"q":"What is a power set of {a,b}?","opts":["{a,b}","{∅,{a},{b},{a,b}}","{a},{b}","{a,b,∅}"],"ans":1},
  {"q":"Which is an equivalence relation required property?","opts":["Reflexive, Symmetric, Transitive","Reflexive only","Transitive only","Symmetric only"],"ans":0},
  {"q":"A function is bijective if it is?","opts":["Injective only","Surjective only","Both injective and surjective","Neither"],"ans":2},
  {"q":"Cantor's diagonal argument proves?","opts":["Rationals are uncountable","Naturals are uncountable","Real numbers are uncountable","Integers are finite"],"ans":2},
  {"q":"A DFA accepts a string if?","opts":["It reaches any state","It reaches a final/accepting state","It reaches start state","It has no transitions"],"ans":1},
  {"q":"NFA differs from DFA in that NFA can have?","opts":["More states","Multiple transitions for same input","Fewer final states","More alphabets"],"ans":1},
  {"q":"Regular expressions describe?","opts":["Context-free languages","Regular languages","Context-sensitive languages","Recursive languages"],"ans":1},
  {"q":"A CFG generates which type of language?","opts":["Regular","Context-free","Recursive","Unrestricted"],"ans":1},
  {"q":"Pumping lemma is used to prove a language?","opts":["Is regular","Is context-free","Is NOT regular","Is decidable"],"ans":2},
  {"q":"A Turing Machine is?","opts":["Physical computer","Abstract computational model","DFA with stack","Finite automaton"],"ans":1},
  {"q":"The Church-Turing thesis states?","opts":["All problems are solvable","Turing machines capture all effective computation","NFA equals DFA in power","Regular languages are infinite"],"ans":1},
  {"q":"What is a relation on set A?","opts":["Subset of A","Function from A to A","Subset of A×A","Partition of A"],"ans":2},
  {"q":"A graph is bipartite if?","opts":["It has even number of vertices","Vertices can be 2-colored such that no adjacent vertices share color","All edges have equal weight","It has no cycles"],"ans":1},
  {"q":"What is a lattice in discrete mathematics?","opts":["A grid structure","Partially ordered set where every pair has LUB and GLB","Set of integers","A type of graph"],"ans":1},
  {"q":"Pigeonhole principle states?","opts":["n items in n+1 containers — some container has 2","n+1 items in n containers — some container has 2","Equal distribution always","No two items share"],"ans":1},
  {"q":"What is a Hamiltonian path?","opts":["Path visiting all edges once","Path visiting all vertices exactly once","Shortest path","Cyclic path"],"ans":1},
  {"q":"What is an Eulerian circuit?","opts":["Circuit visiting all vertices once","Circuit visiting all edges exactly once","Minimum spanning tree","Shortest cycle"],"ans":1},
  {"q":"Trees with n vertices have how many edges?","opts":["n","n+1","n-1","2n"],"ans":2},
  {"q":"The complement of set A relative to U is?","opts":["A∩U","U-A","A∪U","A-U"],"ans":1},
  {"q":"In a group, every element has an?","opts":["Identity","Inverse","Zero","Factor"],"ans":1},
  {"q":"A ring has which two operations?","opts":["OR and AND","Multiplication only","Addition and multiplication (with specific axioms)","Union and intersection"],"ans":2},
  {"q":"What is a partial function?","opts":["Function defined on all inputs","Function defined on some inputs","Bijective function","Surjective function"],"ans":1},
  {"q":"What is the principle of mathematical induction?","opts":["Prove for all cases directly","Prove base case and inductive step","Trial and error","Counter-example method"],"ans":1},
  {"q":"A connected graph with n vertices and n-1 edges is?","opts":["Complete graph","Bipartite graph","A tree","A cycle"],"ans":2},
  {"q":"The number of subsets of a set with n elements?","opts":["n","n²","2ⁿ","n!"],"ans":2},
  {"q":"What is a propositional tautology?","opts":["Always false formula","Sometimes true formula","Formula always true regardless of truth values","Undecidable formula"],"ans":2},
  {"q":"Star(*) in regular expression means?","opts":["One or more","Zero or one","Zero or more","Exactly one"],"ans":2},
  {"q":"What is a monoid?","opts":["Group without inverse","Group with division","Ring with identity","Set without operation"],"ans":0},
  {"q":"In first-order logic, ∀x P(x) means?","opts":["There exists x such that P(x)","For all x, P(x)","Not P(x)","P(x) is false"],"ans":1},
  {"q":"A language is decidable if?","opts":["TM accepts all strings","TM always halts and accepts or rejects","TM never halts","TM rejects all strings"],"ans":1},
  {"q":"The halting problem is?","opts":["Decidable","Semi-decidable","Undecidable","Regular"],"ans":2},
  {"q":"De Morgan's law for sets: (A∪B)' = ?","opts":["A'∪B'","A'∩B'","A∩B","A'∪B"],"ans":1},
  {"q":"A PDA (Pushdown Automaton) recognizes?","opts":["Regular languages","Context-free languages","Context-sensitive languages","Recursive languages"],"ans":1},
  {"q":"An injective (one-to-one) function maps?","opts":["Multiple inputs to same output","Each input to unique output","All of the codomain","No inputs"],"ans":1},
  {"q":"A surjective function?","opts":["Maps one to one","Covers entire codomain","Maps to one element","Is bijective"],"ans":1},
  {"q":"What is a recurrence relation?","opts":["Defines sequence using previous terms","Defines set recursively","Graph traversal technique","Sorting method"],"ans":0},
  {"q":"What is the chromatic number of a graph?","opts":["Number of edges","Minimum colors to color vertices so no adjacent share color","Number of vertices","Maximum degree"],"ans":1},
  {"q":"What is a predicate in logic?","opts":["Proposition with no variables","Function returning true/false based on variable","Constant formula","Quantifier"],"ans":1},
  {"q":"Which quantifier means 'there exists'?","opts":["∀","∃","¬","→"],"ans":1},
  {"q":"The intersection of sets A and B contains?","opts":["All elements in A or B","Elements in A but not B","Elements in both A and B","All elements in neither"],"ans":2},
  {"q":"A Boolean algebra satisfies?","opts":["Ring axioms only","Complemented distributive lattice axioms","Group axioms only","Field axioms"],"ans":1},
  {"q":"What is a planar graph?","opts":["Graph drawn on plane with no edge crossings","Graph with all edges equal","Complete graph","Bipartite graph"],"ans":0},
  {"q":"Euler's formula for planar graphs: V - E + F = ?","opts":["0","1","2","3"],"ans":2},
],
"sem3-cao": [
  {"q":"CAO stands for?","opts":["Computer Architecture and Organization","Computer Algorithms and Operations","Central Address Operations","Computing Arithmetic Operations"],"ans":0},
  {"q":"The fetch-decode-execute cycle is performed by?","opts":["RAM","ALU","CPU","Cache"],"ans":2},
  {"q":"ALU stands for?","opts":["Arithmetic Logic Unit","Advanced Logic Unit","Address Logic Utility","Automated Logic Unit"],"ans":0},
  {"q":"The program counter (PC) holds?","opts":["Current instruction data","Address of next instruction","Result of ALU","Stack pointer"],"ans":1},
  {"q":"RAM is?","opts":["Read-only","Volatile random access memory","Non-volatile","Permanent storage"],"ans":1},
  {"q":"ROM is?","opts":["Readable and writable","Volatile","Non-volatile read-only memory","Cache memory"],"ans":2},
  {"q":"Cache memory purpose?","opts":["Permanent storage","Faster temporary storage between CPU and RAM","Backup storage","Network storage"],"ans":1},
  {"q":"Which numbering system uses base 16?","opts":["Binary","Octal","Decimal","Hexadecimal"],"ans":3},
  {"q":"2's complement is used to represent?","opts":["Floating point numbers","Negative integers","Large positive integers","Fractions"],"ans":1},
  {"q":"What is pipelining?","opts":["Sequential instruction execution","Parallel overlapping execution stages","Memory management","Cache strategy"],"ans":1},
  {"q":"A RISC processor has?","opts":["Complex instructions","Few simple instructions","Many addressing modes","Micro-coded instructions"],"ans":1},
  {"q":"CISC stands for?","opts":["Complex Instruction Set Computer","Common Instruction Set Configuration","Central Instruction System Computer","Circuit Instruction Set Computer"],"ans":0},
  {"q":"Virtual memory uses?","opts":["Only RAM","Disk space to extend RAM","Cache as main memory","ROM for extra space"],"ans":1},
  {"q":"What is DMA?","opts":["Direct Memory Access — peripheral transfers data without CPU","Dynamic Memory Allocation","Distributed Memory Architecture","Direct Module Access"],"ans":0},
  {"q":"The accumulator is?","opts":["Program counter","Stack register","Special register for ALU results","Memory address register"],"ans":2},
  {"q":"Which addressing mode uses the address field as the operand itself?","opts":["Direct","Indirect","Immediate","Register"],"ans":2},
  {"q":"What is a bus in computer architecture?","opts":["Software interface","Communication pathway for data between components","Storage device","Processing unit"],"ans":1},
  {"q":"Flynn's taxonomy classifies computers by?","opts":["Speed","Instruction and data stream parallelism","Memory type","Power consumption"],"ans":1},
  {"q":"SIMD stands for?","opts":["Single Input Multiple Data","Single Instruction Multiple Data","Sequential Instruction Multiple Data","Single Instruction Memory Direct"],"ans":1},
  {"q":"What is the purpose of the instruction register (IR)?","opts":["Holds address of next instruction","Holds currently executing instruction","Holds ALU result","Holds stack pointer"],"ans":1},
  {"q":"Cache hit means?","opts":["Data not in cache","Data found in cache","Cache is full","Cache miss"],"ans":1},
  {"q":"What is temporal locality?","opts":["Nearby memory addresses accessed together","Recently accessed data likely accessed again","Sequential access pattern","Random access pattern"],"ans":1},
  {"q":"What is spatial locality?","opts":["Recently accessed data reused soon","Data near recently accessed data is accessed","Random access pattern","Cache overflow"],"ans":1},
  {"q":"Fetch cycle loads instruction from?","opts":["ALU","Cache/memory via PC","Stack","Register file"],"ans":1},
  {"q":"What is branch prediction?","opts":["Predicting branch outcome to avoid pipeline stalls","Predicting memory addresses","Predicting cache hits","Predicting interrupt times"],"ans":0},
  {"q":"The stack pointer (SP) points to?","opts":["Next instruction","Bottom of stack","Top of stack","Heap"],"ans":2},
  {"q":"Which type of memory is fastest?","opts":["Hard disk","RAM","Cache","Register"],"ans":3},
  {"q":"A superscalar processor?","opts":["Has one pipeline","Executes multiple instructions per cycle","Executes instructions sequentially","Is a CISC processor"],"ans":1},
  {"q":"What is out-of-order execution?","opts":["Executing instructions in program order","Executing instructions as resources are available regardless of order","A type of pipeline stall","Cache management"],"ans":1},
  {"q":"DRAM differs from SRAM in that DRAM?","opts":["Is faster","Needs periodic refresh","Uses flip-flops","Is non-volatile"],"ans":1},
  {"q":"A page fault occurs when?","opts":["CPU overheats","Page not in physical memory","Cache is full","ALU overflows"],"ans":1},
  {"q":"Interrupt driven I/O means?","opts":["CPU polls device continuously","Device notifies CPU when ready","DMA handles all I/O","Programmed I/O"],"ans":1},
  {"q":"IEEE 754 standard defines?","opts":["Integer representation","Floating-point representation","ASCII encoding","Memory addressing"],"ans":1},
  {"q":"The sign-magnitude representation uses?","opts":["1 bit for sign, rest for magnitude","All bits for magnitude","2 bits for sign","No sign bit"],"ans":0},
  {"q":"Word size typically refers to?","opts":["RAM capacity","Number of bits processed as unit by CPU","Cache line size","Bus speed"],"ans":1},
  {"q":"Write-through cache policy means?","opts":["Write to cache only","Write to cache and memory simultaneously","Write to memory only","Write only on cache miss"],"ans":1},
  {"q":"Write-back cache policy means?","opts":["Write to cache and memory simultaneously","Write to cache only, update memory on eviction","Write to memory only","Direct write"],"ans":1},
  {"q":"What is memory interleaving?","opts":["DRAM refresh technique","Distributing memory across banks for parallel access","Virtual memory technique","Cache replacement"],"ans":1},
  {"q":"Micro-operations are?","opts":["High-level instructions","Elementary operations performed in one clock cycle","Assembly instructions","Operating system calls"],"ans":1},
  {"q":"What is the purpose of a TLB?","opts":["Cache for instruction data","Translate virtual to physical addresses quickly","Manage interrupts","Branch prediction table"],"ans":1},
  {"q":"Hardwired control unit is?","opts":["More flexible but slower","Faster but less flexible than microprogrammed","Same speed as microprogrammed","Only used in CISC"],"ans":1},
  {"q":"What is segmentation in memory?","opts":["Dividing memory into fixed equal parts","Dividing memory into variable-size logical segments","Cache organization","Register allocation"],"ans":1},
  {"q":"What is paging?","opts":["Dividing memory into variable parts","Dividing memory into fixed-size pages","Cache technique","Register technique"],"ans":1},
  {"q":"The memory hierarchy from slowest to fastest?","opts":["Cache→RAM→Disk→Register","Register→Cache→RAM→Disk","Disk→RAM→Cache→Register","RAM→Disk→Cache→Register"],"ans":2},
  {"q":"What is an exception in CPU context?","opts":["Software bug","Unexpected event requiring OS intervention","Cache miss","Branch taken"],"ans":1},
  {"q":"Booth's algorithm is used for?","opts":["Division","Binary multiplication of signed numbers","Floating point addition","Addressing modes"],"ans":1},
  {"q":"The instruction pipeline stages typically include?","opts":["Only fetch and execute","Fetch, Decode, Execute, Write-back (and memory access)","Only decode and write","Only execute and store"],"ans":1},
  {"q":"What is forwarding/bypassing in pipelines?","opts":["Pipeline stall technique","Passing result directly to next stage to avoid stall","Branch prediction","Cache mechanism"],"ans":1},
  {"q":"Associativity of cache refers to?","opts":["Where a block can be placed in cache","Cache size","Cache speed","Read/write policy"],"ans":0},
  {"q":"What does MAR stand for?","opts":["Memory Address Register","Macro Arithmetic Register","Memory Access Rate","Main Array Register"],"ans":0},
],
"sem3-prob-stats": [
  {"q":"Probability of an impossible event is?","opts":["1","0.5","0","-1"],"ans":2},
  {"q":"Probability of a certain event is?","opts":["0","0.5","1","Infinity"],"ans":2},
  {"q":"P(A∪B) = ?","opts":["P(A)+P(B)","P(A)+P(B)-P(A∩B)","P(A)×P(B)","P(A)-P(B)"],"ans":1},
  {"q":"Two events are mutually exclusive if?","opts":["P(A∩B)=1","P(A∩B)=0","P(A)=P(B)","P(A∪B)=0"],"ans":1},
  {"q":"The mean of {2,4,6,8} is?","opts":["4","5","6","4.5"],"ans":1},
  {"q":"The median of {1,3,5,7,9} is?","opts":["3","5","7","4"],"ans":1},
  {"q":"The mode of {1,2,2,3,4} is?","opts":["1","2","3","4"],"ans":1},
  {"q":"Standard deviation is the square root of?","opts":["Mean","Median","Variance","Range"],"ans":2},
  {"q":"Binomial distribution applies when?","opts":["Continuous outcomes","Fixed n trials, 2 outcomes, constant p","Poisson events","Normal distribution"],"ans":1},
  {"q":"Poisson distribution models?","opts":["Continuous random variable","Number of events in fixed interval","Binomial with large n","Normal distribution"],"ans":1},
  {"q":"Normal distribution is?","opts":["Skewed right","Skewed left","Symmetric bell-shaped","Uniform"],"ans":2},
  {"q":"P(A|B) is?","opts":["P(A)+P(B)","Probability of A given B","P(A)×P(B)","P(B|A)"],"ans":1},
  {"q":"Bayes' theorem formula is?","opts":["P(A|B)=P(A)P(B)","P(A|B)=P(B|A)P(A)/P(B)","P(A|B)=P(A)+P(B)","P(A|B)=P(A)/P(B)"],"ans":1},
  {"q":"Expected value E[X] = ?","opts":["Σx","Σxf(x)","max(x)","min(x)"],"ans":1},
  {"q":"Variance Var(X) = ?","opts":["E[X]","E[X²]","E[X²]-(E[X])²","(E[X])²"],"ans":2},
  {"q":"A random variable is discrete if?","opts":["It takes any real value","It takes countable values","It is always positive","It follows normal distribution"],"ans":1},
  {"q":"The CDF F(x) is defined as?","opts":["P(X=x)","P(X>x)","P(X≤x)","P(X<x)"],"ans":2},
  {"q":"For independent events A and B: P(A∩B) =?","opts":["P(A)+P(B)","P(A)-P(B)","P(A)×P(B)","P(A)/P(B)"],"ans":2},
  {"q":"The z-score measures?","opts":["Absolute deviation","Number of standard deviations from mean","Variance","Skewness"],"ans":1},
  {"q":"Which distribution has equal probability for all outcomes?","opts":["Normal","Binomial","Uniform","Poisson"],"ans":2},
  {"q":"Moments of a distribution include?","opts":["Mean and variance","Mean, variance, skewness, kurtosis","Standard deviation only","Median and mode"],"ans":1},
  {"q":"Covariance of X and Y measures?","opts":["Individual variances","Joint variability","Correlation coefficient","Their means"],"ans":1},
  {"q":"Correlation coefficient r is always?","opts":["Between 0 and 1","Between -1 and 1","Greater than 1","Between -2 and 2"],"ans":1},
  {"q":"Sample mean is?","opts":["Fixed population parameter","Statistic that estimates population mean","Always equal to population mean","Median of sample"],"ans":1},
  {"q":"Central Limit Theorem states?","opts":["Population must be normal","Sample mean is approximately normal for large n","Variance decreases with n","All distributions are uniform"],"ans":1},
  {"q":"Type I error is?","opts":["Failing to reject false null hypothesis","Rejecting a true null hypothesis","Accepting a false hypothesis","Correct decision"],"ans":1},
  {"q":"Type II error is?","opts":["Rejecting a true null hypothesis","Failing to reject a false null hypothesis","Correct decision","Accepting true hypothesis"],"ans":1},
  {"q":"The p-value is?","opts":["Probability that null hypothesis is true","Probability of observed result if null is true","Significance level","Test statistic"],"ans":1},
  {"q":"Hypothesis testing begins with?","opts":["Conclusion","Collecting data","Stating null and alternate hypotheses","Computing p-value"],"ans":2},
  {"q":"Regression analysis is used to?","opts":["Test hypotheses","Model relationship between variables","Compute probability","Find mode"],"ans":1},
  {"q":"In simple linear regression y = a + bx, b is?","opts":["Intercept","Slope","Constant","Variance"],"ans":1},
  {"q":"R² in regression indicates?","opts":["Error rate","Proportion of variance explained by model","Slope value","P-value"],"ans":1},
  {"q":"Chi-square test is used for?","opts":["Testing means","Testing proportions/categorical data","Testing variance only","Regression"],"ans":1},
  {"q":"The geometric mean of 4 and 9 is?","opts":["6.5","6","7","5"],"ans":1},
  {"q":"What is skewness?","opts":["Spread of distribution","Asymmetry of distribution","Central tendency","Kurtosis"],"ans":1},
  {"q":"What is kurtosis?","opts":["Skewness measure","Tailedness of distribution","Central tendency","Variance"],"ans":1},
  {"q":"Conditional probability P(A|B) requires P(B)?","opts":["= 0","= 1","≠ 0","< 0.5"],"ans":2},
  {"q":"Complement rule: P(A') = ?","opts":["P(A)","1+P(A)","1-P(A)","0"],"ans":2},
  {"q":"The range of a dataset is?","opts":["Mean - median","Max - Min","Sum of all values","Standard deviation"],"ans":1},
  {"q":"Quartile Q2 is the same as?","opts":["Mean","Median","Mode","Variance"],"ans":1},
  {"q":"IQR (Interquartile Range) = ?","opts":["Q3-Q1","Q2-Q1","Q3-Q2","Max-Min"],"ans":0},
  {"q":"An outlier is a data point that?","opts":["Is equal to mean","Falls far from the rest of data","Is at median","Has zero probability"],"ans":1},
  {"q":"A point estimate gives?","opts":["Range of values","Single value estimate of parameter","Confidence interval","Distribution shape"],"ans":1},
  {"q":"Confidence interval gives?","opts":["Single estimate","Range believed to contain parameter with given confidence","P-value","Test statistic"],"ans":1},
  {"q":"Multiplication rule for dependent events: P(A∩B) = ?","opts":["P(A)×P(B)","P(A)×P(B|A)","P(A)+P(B)","P(A|B)"],"ans":1},
  {"q":"A binomial distribution B(n,p) has mean?","opts":["np²","np(1-p)","n/p","np"],"ans":3},
  {"q":"Standard error is?","opts":["Population standard deviation","Standard deviation of sample mean","Sample variance","Absolute error"],"ans":1},
  {"q":"The t-test is used when?","opts":["Population variance is known","Population variance is unknown (small sample)","n>1000","Distribution is uniform"],"ans":1},
  {"q":"ANOVA tests?","opts":["Two proportions","Means of three or more groups","Single mean","Variance equality"],"ans":1},
  {"q":"What is the law of total probability?","opts":["P(A)=P(A|B)+P(A|B')","P(A)=ΣP(A|Bi)P(Bi)","P(A)=P(A∩B)","P(A)=1-P(A')"],"ans":1},
],
"sem3-sdc": [
  {"q":"SDC stands for?","opts":["Software Design Concepts","Switching and Digital Circuits","System Design Computing","Sequential Digital Control"],"ans":1},
  {"q":"Binary number 1010 equals in decimal?","opts":["8","10","12","14"],"ans":1},
  {"q":"A NOT gate inverts?","opts":["Input to output as is","Input to opposite logic level","Nothing","Input and adds 1"],"ans":1},
  {"q":"AND gate output is 1 only when?","opts":["Any input is 1","All inputs are 1","Any input is 0","All inputs are 0"],"ans":1},
  {"q":"OR gate output is 0 only when?","opts":["Any input is 1","All inputs are 1","All inputs are 0","Any input is 0"],"ans":2},
  {"q":"NAND gate is a combination of?","opts":["NOT+OR","NOT+AND","AND+OR","OR+NOR"],"ans":1},
  {"q":"NOR gate is a universal gate because?","opts":["It is cheapest","Any Boolean function can be built from NOR gates","It is fastest","It uses least power"],"ans":1},
  {"q":"XOR gate output is 1 when?","opts":["All inputs same","All inputs different","Inputs are unequal (odd number of 1s)","No input is 0"],"ans":2},
  {"q":"XNOR gate output is 1 when?","opts":["Inputs are different","Inputs are equal","Any input is 1","Any input is 0"],"ans":1},
  {"q":"De Morgan's theorem: NOT(A.B) = ?","opts":["NOT A . NOT B","NOT A + NOT B","A + B","NOT A . B"],"ans":1},
  {"q":"A half adder produces?","opts":["Sum and carry out","Only sum","Only carry","Sum, carry, and borrow"],"ans":0},
  {"q":"A full adder differs from half adder by having?","opts":["More outputs","One extra input (carry in)","More gates","Different truth table"],"ans":1},
  {"q":"Karnaugh map is used for?","opts":["Designing flip-flops","Simplifying Boolean expressions","Solving logic equations numerically","Testing circuits"],"ans":1},
  {"q":"A multiplexer (MUX) selects?","opts":["One output from multiple inputs based on select lines","Multiple inputs from one output","Equal inputs and outputs","No selection"],"ans":0},
  {"q":"A demultiplexer routes?","opts":["Multiple inputs to one output","One input to one of several outputs based on select","Inputs to outputs equally","Nothing"],"ans":1},
  {"q":"A flip-flop is?","opts":["Combinational circuit","Sequential circuit storing one bit","Adder circuit","Encoder"],"ans":1},
  {"q":"SR flip-flop with S=1, R=1 results in?","opts":["Q=1","Q=0","Undefined/forbidden state","Toggles"],"ans":2},
  {"q":"D flip-flop on positive clock edge?","opts":["Resets Q","Stores current D value to Q","Toggles Q","Ignores D"],"ans":1},
  {"q":"JK flip-flop with J=1, K=1?","opts":["Sets Q=1","Resets Q=0","Toggles Q","No change"],"ans":2},
  {"q":"T flip-flop with T=1?","opts":["Sets Q=1","Resets Q=0","Toggles Q","No change"],"ans":2},
  {"q":"A register stores?","opts":["One bit","Multiple bits (a word)","Infinite bits","Only program counter"],"ans":1},
  {"q":"Hexadecimal F equals decimal?","opts":["14","15","16","13"],"ans":1},
  {"q":"Octal number 17 equals in decimal?","opts":["15","16","17","12"],"ans":0},
  {"q":"Two's complement of 0101 (4-bit)?","opts":["1010","1011","0101","1101"],"ans":1},
  {"q":"A counter that counts in natural binary is?","opts":["Ring counter","Johnson counter","Ripple counter","Gray code counter"],"ans":2},
  {"q":"A Johnson counter of n flip-flops has how many states?","opts":["n","n+1","2n","n²"],"ans":2},
  {"q":"Priority encoder encodes?","opts":["Highest priority active input","Lowest priority active input","All inputs equally","No inputs"],"ans":0},
  {"q":"A BCD code represents?","opts":["Binary coded decimal (each decimal digit in 4 bits)","Bit coded data","Binary cyclic digits","Bit-count detector"],"ans":0},
  {"q":"What is Gray code used for?","opts":["Faster arithmetic","Minimizing errors in position encoders (one bit changes at a time)","ASCII encoding","Hexadecimal conversion"],"ans":1},
  {"q":"A 4-to-1 MUX needs how many select lines?","opts":["1","2","3","4"],"ans":1},
  {"q":"Propagation delay in a gate is?","opts":["Power consumed","Time for output to change after input changes","Gate size","Voltage supply"],"ans":1},
  {"q":"PLA stands for?","opts":["Programmable Logic Array","Parallel Logic Array","Program Loader Array","Processing Layer Array"],"ans":0},
  {"q":"Synchronous circuits are controlled by?","opts":["Input signals only","Clock signal","Power supply","Random events"],"ans":1},
  {"q":"Race condition in sequential circuits means?","opts":["Circuit is fast","Output depends on timing of signal arrivals","Circuit is slow","No clock is used"],"ans":1},
  {"q":"A binary decoder with n inputs has how many outputs?","opts":["n","n+1","2n","2ⁿ"],"ans":3},
  {"q":"The SOP (Sum of Products) form uses?","opts":["OR of AND terms","AND of OR terms","Only OR terms","Only AND terms"],"ans":0},
  {"q":"The POS (Product of Sums) form uses?","opts":["OR of AND terms","AND of OR terms","Only AND terms","Only OR terms"],"ans":1},
  {"q":"A latch is level-triggered while a flip-flop is?","opts":["Level-triggered","Edge-triggered","Not triggered","Power-triggered"],"ans":1},
  {"q":"Which is a sequential circuit?","opts":["Half adder","MUX","D flip-flop","AND gate"],"ans":2},
  {"q":"Boolean expression A.A = ?","opts":["0","A","1","2A"],"ans":1},
  {"q":"Boolean expression A+A = ?","opts":["0","A","1","A²"],"ans":1},
  {"q":"Boolean expression A.0 = ?","opts":["A","1","0","NOT A"],"ans":2},
  {"q":"Boolean expression A+1 = ?","opts":["A","0","NOT A","1"],"ans":3},
  {"q":"A shift register shifts data?","opts":["Left only","Right only","Left or right by clock pulse","Randomly"],"ans":2},
  {"q":"Minterm is?","opts":["OR of all variables","AND of all variables (complemented or not)","Sum of all variables","Product of subsets"],"ans":1},
  {"q":"Maxterm is?","opts":["AND of all variables","OR of all variables (complemented or not)","Product of all variables","XOR of all variables"],"ans":1},
  {"q":"CMOS logic uses?","opts":["NPN transistors only","PNP transistors only","Complementary pairs of NMOS and PMOS","Only NMOS"],"ans":2},
  {"q":"Fan-out of a gate is?","opts":["Number of gates it can drive","Number of inputs it accepts","Power it consumes","Speed it operates at"],"ans":0},
  {"q":"Which is the fastest logic family?","opts":["TTL","CMOS","ECL","NMOS"],"ans":2},
  {"q":"A binary ripple counter with 4 flip-flops can count up to?","opts":["8","15","16","14"],"ans":1},
],
}

def build_js_block(subject_key, questions):
    lines = [f'  "{subject_key}": [']
    for i, q in enumerate(questions):
        comma = "," if i < len(questions)-1 else ""
        opts = ', '.join(f'"{o}"' for o in q["opts"])
        lines.append(f'    {{')
        lines.append(f'      "question": "{q["q"]}",')
        lines.append(f'      "options": [{opts}],')
        lines.append(f'      "correctAnswer": {q["ans"]}')
        lines.append(f'    }}{comma}')
    lines.append('  ]')
    return '\n'.join(lines)

out_dir = os.path.join(os.path.dirname(__file__), '..', 'frontend', 'assets')
out_file = os.path.join(out_dir, 'quiz_sem3.js')

blocks = []
keys = list(SEM3.keys())
for i, key in enumerate(keys):
    comma = "," if i < len(keys)-1 else ""
    blocks.append(build_js_block(key, SEM3[key]) + comma)

content = 'const quizDataSem3 = {\n' + '\n'.join(blocks) + '\n};\n'
with open(out_file, 'w', encoding='utf-8') as f:
    f.write(content)

for key, qs in SEM3.items():
    assert len(qs) == 50, f"{key} has {len(qs)} questions"
    texts = [q['q'] for q in qs]
    assert len(set(texts)) == 50, f"{key} has duplicate questions: {len(set(texts))}"

print(f"[OK] quiz_sem3.js generated with {len(SEM3)} subjects, 50 questions each.")
