import os

SEM2 = {
"sem2-applied-physics": [
  {"q":"What is the SI unit of force?","opts":["Joule","Watt","Newton","Pascal"],"ans":2},
  {"q":"Which law states F=ma?","opts":["Newton's 1st Law","Newton's 2nd Law","Newton's 3rd Law","Hooke's Law"],"ans":1},
  {"q":"The SI unit of energy is?","opts":["Watt","Newton","Joule","Pascal"],"ans":2},
  {"q":"Speed of light in vacuum?","opts":["3×10⁶ m/s","3×10⁸ m/s","3×10¹⁰ m/s","3×10⁴ m/s"],"ans":1},
  {"q":"Which phenomenon explains why a straw in water looks bent?","opts":["Reflection","Diffraction","Refraction","Interference"],"ans":2},
  {"q":"The SI unit of electric current is?","opts":["Volt","Ohm","Ampere","Watt"],"ans":2},
  {"q":"What is Ohm's Law?","opts":["P=IV","V=IR","F=qE","E=mc²"],"ans":1},
  {"q":"The work done is zero when force is applied?","opts":["In direction of motion","Opposite to motion","Perpendicular to motion","At 45° to motion"],"ans":2},
  {"q":"Which type of wave requires a medium?","opts":["Electromagnetic","Light","Mechanical","Radio"],"ans":2},
  {"q":"The unit of frequency is?","opts":["Second","Meter","Hertz","Ampere"],"ans":2},
  {"q":"Which law of thermodynamics defines entropy?","opts":["Zeroth","First","Second","Third"],"ans":2},
  {"q":"What is the acceleration due to gravity on Earth (approx)?","opts":["8.9 m/s²","9.8 m/s²","10.8 m/s²","7.8 m/s²"],"ans":1},
  {"q":"A body in uniform circular motion has constant?","opts":["Velocity","Speed","Acceleration magnitude","Force direction"],"ans":1},
  {"q":"The principle of superposition applies to?","opts":["Newton's laws","Wave interference","Ohm's law","Thermodynamics"],"ans":1},
  {"q":"Magnetic field lines exit from which pole?","opts":["South","North","Both","Neither"],"ans":1},
  {"q":"What is the unit of magnetic flux?","opts":["Tesla","Weber","Gauss","Henry"],"ans":1},
  {"q":"Energy stored in a spring is?","opts":["Kinetic","Thermal","Elastic potential","Gravitational"],"ans":2},
  {"q":"The refractive index of a medium is?","opts":["c/v","v/c","n×c","c×n"],"ans":0},
  {"q":"Which type of lens converges light?","opts":["Concave","Convex","Plane","Diverging"],"ans":1},
  {"q":"What is Young's modulus?","opts":["Ratio of stress to strain","Ratio of strain to stress","Force per area","Pressure per volume"],"ans":0},
  {"q":"The first law of thermodynamics is about conservation of?","opts":["Momentum","Mass","Energy","Charge"],"ans":2},
  {"q":"Doppler effect is related to?","opts":["Temperature change","Frequency change due to motion","Light bending","Wave diffraction"],"ans":1},
  {"q":"Which force is responsible for keeping planets in orbit?","opts":["Electromagnetic","Nuclear","Gravitational","Centrifugal"],"ans":2},
  {"q":"What is the unit of capacitance?","opts":["Ohm","Henry","Farad","Weber"],"ans":2},
  {"q":"What is latent heat?","opts":["Heat that raises temperature","Heat absorbed/released during phase change","Heat from radiation","Heat from convection"],"ans":1},
  {"q":"The speed of sound in air at 0°C is approximately?","opts":["330 m/s","220 m/s","440 m/s","660 m/s"],"ans":0},
  {"q":"What is nuclear fission?","opts":["Atoms combine","Nucleus splits","Electrons emitted","Protons absorbed"],"ans":1},
  {"q":"Impulse equals?","opts":["Force × distance","Force × time","Mass × acceleration","Work done"],"ans":1},
  {"q":"The law of conservation of momentum holds when?","opts":["External forces act","No external forces act","Friction is present","Gravity acts"],"ans":1},
  {"q":"In photoelectric effect, who explained it?","opts":["Newton","Maxwell","Einstein","Bohr"],"ans":2},
  {"q":"What is the unit of inductance?","opts":["Farad","Henry","Weber","Tesla"],"ans":1},
  {"q":"Which particle has no charge?","opts":["Proton","Electron","Positron","Neutron"],"ans":3},
  {"q":"Bernoulli's principle relates to?","opts":["Heat flow","Fluid flow and pressure","Electric fields","Light waves"],"ans":1},
  {"q":"The phenomenon of total internal reflection requires?","opts":["Light going from denser to rarer medium at critical angle","Any angle of incidence","Rarer to denser medium","Parallel rays only"],"ans":0},
  {"q":"What is the unit of power?","opts":["Joule","Newton","Watt","Pascal"],"ans":2},
  {"q":"The Heisenberg Uncertainty Principle states?","opts":["Energy is conserved","Position and momentum cannot both be precisely known","Entropy always increases","Light speed is constant"],"ans":1},
  {"q":"What is wavelength?","opts":["Number of waves per second","Distance between two consecutive crests","Amplitude of wave","Speed of wave"],"ans":1},
  {"q":"Stefan-Boltzmann Law relates to?","opts":["Fluid pressure","Thermal radiation energy","Wave diffraction","Magnetic fields"],"ans":1},
  {"q":"What is polarization of light?","opts":["Light bending","Restriction of vibration to one plane","Light splitting","Interference pattern"],"ans":1},
  {"q":"The force between two charges follows?","opts":["Newton's 2nd Law","Coulomb's Law","Faraday's Law","Ohm's Law"],"ans":1},
  {"q":"What is a semiconductor?","opts":["Perfect conductor","Perfect insulator","Material with intermediate conductivity","Superconductor"],"ans":2},
  {"q":"Which effect demonstrates light's wave nature?","opts":["Photoelectric effect","Compton effect","Interference","None of these"],"ans":2},
  {"q":"What is angular momentum?","opts":["m×v","r×mv","F×r","m×a"],"ans":1},
  {"q":"Absolute zero temperature is?","opts":["0°C","−100°C","−273.15°C","−173°C"],"ans":2},
  {"q":"What is meant by 'resonance' in physics?","opts":["Random vibration","Vibration at natural frequency","Damped oscillation","Forced oscillation"],"ans":1},
  {"q":"The de Broglie wavelength relates to?","opts":["Wave-particle duality","Light speed","Entropy","Gravity"],"ans":0},
  {"q":"What is electric potential difference also called?","opts":["Current","Resistance","Voltage","Charge"],"ans":2},
  {"q":"Transformer works on principle of?","opts":["Self induction","Mutual induction","Electromagnetic radiation","Static electricity"],"ans":1},
  {"q":"Centre of mass of a system moves as if?","opts":["External forces act on it","Internal forces act on it","No forces act","Gravity acts only"],"ans":0},
  {"q":"What is the unit of pressure?","opts":["Joule","Newton","Pascal","Watt"],"ans":2},
],
"sem2-bee": [
  {"q":"BEE stands for?","opts":["Basic Electrical Equipment","Basic Electrical Engineering","Binary Electrical Engineering","Built-in Electrical Elements"],"ans":1},
  {"q":"Ohm's law states V =?","opts":["I/R","IR","I+R","I²R"],"ans":1},
  {"q":"The unit of resistance is?","opts":["Volt","Ampere","Ohm","Watt"],"ans":2},
  {"q":"Which component stores charge?","opts":["Resistor","Inductor","Capacitor","Diode"],"ans":2},
  {"q":"In series circuit, current is?","opts":["Different in each component","Same throughout","Zero","Maximum at source"],"ans":1},
  {"q":"In parallel circuit, voltage is?","opts":["Different across each branch","Same across all branches","Doubled","Halved"],"ans":1},
  {"q":"The power dissipated in a resistor is?","opts":["V/I","V²/R","V×R","I/V"],"ans":1},
  {"q":"Faraday's law relates to?","opts":["Induced EMF","Electric current","Resistance","Capacitance"],"ans":0},
  {"q":"A transformer changes?","opts":["Frequency","Phase","Voltage level","Current direction"],"ans":2},
  {"q":"The unit of electric charge is?","opts":["Ampere","Coulomb","Volt","Farad"],"ans":1},
  {"q":"What is meant by EMF?","opts":["Electromotive Force","Electromagnetic Field","Electric Magnetic Flux","Electron Movement Force"],"ans":0},
  {"q":"Kirchhoff's Current Law states that?","opts":["Voltage around a loop is zero","Sum of currents at a node is zero","Resistance in series adds","Power is conserved"],"ans":1},
  {"q":"Kirchhoff's Voltage Law states that?","opts":["Current at node sums to zero","Sum of voltages in a closed loop is zero","Resistance in parallel is less","Current is same in parallel"],"ans":1},
  {"q":"A diode allows current to flow?","opts":["In both directions","In one direction only","Only when voltage is zero","Only in AC"],"ans":1},
  {"q":"An alternating current (AC) changes its?","opts":["Resistance","Frequency","Direction periodically","Capacitance"],"ans":2},
  {"q":"The frequency of standard AC supply in India is?","opts":["50 Hz","60 Hz","100 Hz","25 Hz"],"ans":0},
  {"q":"RMS value of AC is?","opts":["Peak value","Peak/√2","Peak×√2","Peak/2"],"ans":1},
  {"q":"An inductor opposes change in?","opts":["Voltage","Charge","Current","Resistance"],"ans":2},
  {"q":"Lenz's law is related to?","opts":["Direction of induced EMF","Magnitude of resistance","Electric field direction","Power factor"],"ans":0},
  {"q":"The impedance in AC circuits is measured in?","opts":["Farad","Henry","Ohm","Watt"],"ans":2},
  {"q":"Which is the correct formula for power factor?","opts":["cos φ","sin φ","tan φ","sec φ"],"ans":0},
  {"q":"A step-up transformer increases?","opts":["Current","Voltage","Frequency","Power"],"ans":1},
  {"q":"The relationship between charge and capacitance is?","opts":["Q=CV","Q=C/V","Q=V/C","Q=C+V"],"ans":0},
  {"q":"Norton's theorem replaces a network with?","opts":["Voltage source and series resistance","Current source and parallel resistance","Capacitor and inductor","Two resistors"],"ans":1},
  {"q":"Thevenin's theorem replaces a network with?","opts":["Current source and parallel resistance","Voltage source and series resistance","Two capacitors","Two inductors"],"ans":1},
  {"q":"The energy stored in a capacitor is?","opts":["CV²","½CV²","CV","C²V"],"ans":1},
  {"q":"The energy stored in an inductor is?","opts":["LI²","½LI²","LI","L²I"],"ans":1},
  {"q":"Superposition theorem applies to?","opts":["Nonlinear circuits","Linear circuits only","Capacitive circuits only","Inductive circuits only"],"ans":1},
  {"q":"What is resonance frequency in LC circuit?","opts":["1/(2π√LC)","2π√LC","LC/2π","√LC"],"ans":0},
  {"q":"The material with very high resistance is called?","opts":["Conductor","Semiconductor","Insulator","Superconductor"],"ans":2},
  {"q":"What is the unit of inductance?","opts":["Farad","Ohm","Henry","Weber"],"ans":2},
  {"q":"A full-wave rectifier uses how many diodes?","opts":["1","2","4","8"],"ans":2},
  {"q":"The efficiency of a transformer is (output/input)?","opts":["Power","Voltage","Current","Impedance"],"ans":0},
  {"q":"Which law governs the magnetic field around a current-carrying conductor?","opts":["Faraday's","Ohm's","Ampere's","Lenz's"],"ans":2},
  {"q":"Star-Delta transformation is used to simplify?","opts":["Series circuits","Three-phase circuits","Parallel circuits","DC circuits"],"ans":1},
  {"q":"What does a relay do?","opts":["Stores charge","Controls a circuit using another circuit","Converts AC to DC","Amplifies voltage"],"ans":1},
  {"q":"The no-load current of a transformer is?","opts":["Zero","Equal to full load","Small magnetizing current","Infinite"],"ans":2},
  {"q":"Voltage leads current in a purely?","opts":["Resistive circuit","Capacitive circuit","Inductive circuit","Resistive-capacitive circuit"],"ans":2},
  {"q":"Current leads voltage in a purely?","opts":["Resistive circuit","Inductive circuit","Capacitive circuit","LC circuit"],"ans":2},
  {"q":"The mutual inductance depends on?","opts":["Resistance only","Geometry and relative position of coils","Voltage only","Current only"],"ans":1},
  {"q":"What is the purpose of a fuse?","opts":["Store energy","Protect circuit from overcurrent","Amplify current","Regulate voltage"],"ans":1},
  {"q":"Reactive power is measured in?","opts":["Watts","VA","VAR","kWh"],"ans":2},
  {"q":"The phase angle in a purely resistive circuit is?","opts":["90°","45°","0°","180°"],"ans":2},
  {"q":"What is the time constant of an RC circuit?","opts":["R/C","RC","R+C","C/R"],"ans":1},
  {"q":"What is the time constant of an RL circuit?","opts":["R/L","RL","L/R","R+L"],"ans":2},
  {"q":"An ideal voltage source has internal resistance of?","opts":["Infinite","Zero","1 Ohm","Variable"],"ans":1},
  {"q":"An ideal current source has internal resistance of?","opts":["Zero","1 Ohm","Infinite","Variable"],"ans":2},
  {"q":"Which instrument measures current?","opts":["Voltmeter","Ammeter","Ohmmeter","Wattmeter"],"ans":1},
  {"q":"The dot convention in coupled circuits indicates?","opts":["Voltage polarity","Current direction","Phase of mutual induction","Frequency"],"ans":2},
  {"q":"What is apparent power?","opts":["V×I×cosφ","V×I","V×I×sinφ","V²/R"],"ans":1},
],
"sem2-data-structures": [
  {"q":"Which data structure uses LIFO?","opts":["Queue","Stack","Array","Tree"],"ans":1},
  {"q":"Which data structure uses FIFO?","opts":["Stack","Queue","Tree","Graph"],"ans":1},
  {"q":"Time complexity of binary search?","opts":["O(n)","O(log n)","O(n²)","O(1)"],"ans":1},
  {"q":"A linked list node contains?","opts":["Data only","Pointer only","Data and pointer","Index and data"],"ans":2},
  {"q":"Which tree has at most 2 children per node?","opts":["AVL Tree","B-Tree","Binary Tree","Heap"],"ans":2},
  {"q":"The root of a tree has which depth?","opts":["1","0","-1","Depends"],"ans":1},
  {"q":"Which sorting is best for nearly sorted data?","opts":["Quick Sort","Heap Sort","Insertion Sort","Merge Sort"],"ans":2},
  {"q":"Inorder traversal of BST gives?","opts":["Random order","Sorted order","Reverse sorted","Level order"],"ans":1},
  {"q":"What is the height of a balanced BST with n nodes?","opts":["O(n)","O(log n)","O(n²)","O(1)"],"ans":1},
  {"q":"Bubble sort's worst-case time complexity?","opts":["O(n log n)","O(n)","O(n²)","O(log n)"],"ans":2},
  {"q":"Which traversal visits root LAST?","opts":["Preorder","Inorder","Postorder","Levelorder"],"ans":2},
  {"q":"A graph with no cycles is called?","opts":["Tree","DAG (Directed Acyclic Graph)","Connected graph","Complete graph"],"ans":0},
  {"q":"What is a priority queue?","opts":["FIFO queue","Queue where elements have priority","LIFO queue","Circular queue"],"ans":1},
  {"q":"Hashing resolves collision by?","opts":["Sorting","Chaining or open addressing","Deletion","Restarting"],"ans":1},
  {"q":"Which algorithm finds shortest path in weighted graph?","opts":["BFS","DFS","Dijkstra's","Kruskal's"],"ans":2},
  {"q":"A min-heap ensures the root is?","opts":["Largest element","Smallest element","Median element","Random element"],"ans":1},
  {"q":"What is a deque?","opts":["Single-ended queue","Double-ended queue","Priority queue","Circular queue"],"ans":1},
  {"q":"Merge sort's time complexity is?","opts":["O(n²)","O(n)","O(n log n)","O(log n)"],"ans":2},
  {"q":"BFS uses which data structure internally?","opts":["Stack","Queue","Heap","Tree"],"ans":1},
  {"q":"DFS uses which data structure internally?","opts":["Queue","Stack","Heap","Array"],"ans":1},
  {"q":"Which is NOT a linear data structure?","opts":["Array","Stack","Queue","Tree"],"ans":3},
  {"q":"The degree of a node in a tree is?","opts":["Height of node","Number of children","Level of node","Depth of node"],"ans":1},
  {"q":"An AVL tree is a?","opts":["Binary tree","Self-balancing BST","Max-heap","B-tree"],"ans":1},
  {"q":"Which has O(1) access time?","opts":["Linked list","Stack","Array","Queue"],"ans":2},
  {"q":"Kruskal's algorithm builds?","opts":["Shortest path","Minimum spanning tree","Maximum flow","Topological order"],"ans":1},
  {"q":"What is a circular linked list?","opts":["List with no nodes","Last node points to first node","Doubly linked list","List with one node"],"ans":1},
  {"q":"Quick sort's average time complexity?","opts":["O(n²)","O(n log n)","O(n)","O(log n)"],"ans":1},
  {"q":"Postorder traversal visits nodes in which order?","opts":["Root-Left-Right","Left-Root-Right","Left-Right-Root","Right-Left-Root"],"ans":2},
  {"q":"A full binary tree has?","opts":["All nodes with 0 or 2 children","All nodes with 2 children","All leaves at same level","Only one child per node"],"ans":0},
  {"q":"Which data structure is used in recursive function calls?","opts":["Queue","Array","Stack","Tree"],"ans":2},
  {"q":"The number of edges in a complete graph with n vertices?","opts":["n","n-1","n(n-1)/2","n²"],"ans":2},
  {"q":"Dijkstra's algorithm fails with?","opts":["Undirected graphs","Negative weight edges","Large graphs","Disconnected graphs"],"ans":1},
  {"q":"What is a sparse matrix?","opts":["Matrix with many non-zero values","Matrix with mostly zero values","Square matrix","Identity matrix"],"ans":1},
  {"q":"Amortized time complexity of push in dynamic array?","opts":["O(n)","O(log n)","O(1)","O(n²)"],"ans":2},
  {"q":"Prim's algorithm builds?","opts":["Shortest path tree","Minimum spanning tree","Topological sort","Eulerian path"],"ans":1},
  {"q":"What is the space complexity of merge sort?","opts":["O(1)","O(log n)","O(n)","O(n²)"],"ans":2},
  {"q":"Topological sort applies to?","opts":["Undirected graphs","Directed acyclic graphs","Trees only","Complete graphs"],"ans":1},
  {"q":"Which search works only on sorted arrays?","opts":["Linear search","Binary search","Hash search","DFS"],"ans":1},
  {"q":"A B-tree of order m has at most how many keys per node?","opts":["m","m-1","m+1","2m"],"ans":1},
  {"q":"The time to insert into a hash table on average?","opts":["O(n)","O(log n)","O(1)","O(n²)"],"ans":2},
  {"q":"Which tree is used in database indexing?","opts":["Binary tree","AVL tree","B+ tree","Heap"],"ans":2},
  {"q":"Red-Black tree ensures the tree height is?","opts":["O(n)","O(log n)","O(1)","O(n²)"],"ans":1},
  {"q":"Preorder traversal visits nodes in which order?","opts":["Left-Root-Right","Root-Left-Right","Left-Right-Root","Right-Root-Left"],"ans":1},
  {"q":"Which is NOT a graph traversal algorithm?","opts":["BFS","DFS","Dijkstra's","Bubble Sort"],"ans":3},
  {"q":"A heap is typically implemented using?","opts":["Linked list","Array","Tree pointers","Stack"],"ans":1},
  {"q":"What is the worst case of quick sort?","opts":["O(n log n)","O(n)","O(n²)","O(log n)"],"ans":2},
  {"q":"In which order does level-order traversal visit nodes?","opts":["Depth first","Left subtree first","Level by level","Root last"],"ans":2},
  {"q":"A skip list provides O(log n) search with?","opts":["Binary tree","Sorted linked list with express lanes","Hash table","Heap"],"ans":1},
  {"q":"Bellman-Ford algorithm handles?","opts":["Positive weights only","Negative weights","Unweighted graphs","Minimum spanning trees"],"ans":1},
  {"q":"A segment tree supports range queries in?","opts":["O(n)","O(n²)","O(log n)","O(1)"],"ans":2},
],
"sem2-edc": [
  {"q":"EDC stands for?","opts":["Electronic Data Circuits","Electronic Devices and Circuits","Electrical Device Control","Electronic Device Computing"],"ans":1},
  {"q":"A p-n junction diode allows current when?","opts":["Reverse biased","Forward biased","Unbiased","In AC"],"ans":1},
  {"q":"The depletion region in a p-n junction contains?","opts":["Free electrons and holes","No mobile charge carriers","Positive ions only","Negative ions only"],"ans":1},
  {"q":"Which diode maintains constant voltage?","opts":["LED","Schottky","Zener","Photodiode"],"ans":2},
  {"q":"A transistor in saturation mode acts as?","opts":["Open switch","Amplifier","Closed switch","Oscillator"],"ans":2},
  {"q":"BJT stands for?","opts":["Bipolar Junction Transistor","Binary Junction Transistor","Buffered Junction Transistor","Base Junction Transistor"],"ans":0},
  {"q":"The three terminals of a BJT are?","opts":["Source, Gate, Drain","Anode, Cathode, Gate","Emitter, Base, Collector","Input, Output, Ground"],"ans":2},
  {"q":"FET stands for?","opts":["Field Effect Transistor","Frequency Effect Transistor","Forward Emitter Transistor","Fixed Emitter Terminal"],"ans":0},
  {"q":"A half-wave rectifier uses how many diodes?","opts":["1","2","4","6"],"ans":0},
  {"q":"A bridge rectifier uses?","opts":["1 diode","2 diodes","4 diodes","6 diodes"],"ans":2},
  {"q":"The ripple factor of full-wave rectifier compared to half-wave?","opts":["Higher","Equal","Lower","Zero"],"ans":2},
  {"q":"Zener breakdown occurs due to?","opts":["Thermal runaway","High electric field breaking covalent bonds","Impact ionization at low voltage","High temperature"],"ans":1},
  {"q":"Avalanche breakdown is caused by?","opts":["High reverse voltage carrier multiplication","Low forward voltage","Temperature decrease","No doping"],"ans":0},
  {"q":"The current gain β of a BJT is?","opts":["IC/IB","IB/IC","IE/IB","IC/IE"],"ans":0},
  {"q":"An ideal op-amp has input impedance of?","opts":["Zero","1 kΩ","Infinite","100 Ω"],"ans":2},
  {"q":"The gain of an inverting amplifier is?","opts":["Rf/Rin","Rin/Rf","-Rf/Rin","1+Rf/Rin"],"ans":2},
  {"q":"MOSFET gate controls current by?","opts":["Base current","Electric field","Magnetic field","Light"],"ans":1},
  {"q":"In a common emitter amplifier, the output is?","opts":["In phase with input","180° out of phase","90° out of phase","Same as input"],"ans":1},
  {"q":"Minority carriers in p-type semiconductor are?","opts":["Holes","Electrons","Protons","Ions"],"ans":1},
  {"q":"The built-in potential of Si p-n junction is approximately?","opts":["0.3 V","0.7 V","1.0 V","1.5 V"],"ans":1},
  {"q":"LEDs emit light due to?","opts":["Photoelectric effect","Electroluminescence","Fluorescence","Phosphorescence"],"ans":1},
  {"q":"What is the cut-off frequency of an amplifier?","opts":["Frequency at which gain is maximum","Frequency at which gain drops to 0.707 of max","Minimum operating frequency","Natural frequency"],"ans":1},
  {"q":"Schmitt trigger is used for?","opts":["Amplification","Signal conditioning with hysteresis","Oscillation","Rectification"],"ans":1},
  {"q":"CMOS stands for?","opts":["Complementary Metal Oxide Semiconductor","Common Metal Oxide Switch","Combined MOS","Charged MOS"],"ans":0},
  {"q":"What is transconductance (gm)?","opts":["ΔID/ΔVDS","ΔID/ΔVGS","ΔVGS/ΔID","IC/IB"],"ans":1},
  {"q":"The emitter follower configuration has voltage gain of approximately?","opts":["Very high","Very low (≈1)","Negative","Zero"],"ans":1},
  {"q":"Which biasing technique provides best stability?","opts":["Fixed bias","Voltage divider bias","Emitter bias","Collector bias"],"ans":1},
  {"q":"Pinch-off voltage in JFET occurs when?","opts":["VGS=0","Depletion region closes channel","Gate is forward biased","Drain voltage is zero"],"ans":1},
  {"q":"The cutoff region of BJT means?","opts":["Both junctions forward biased","Both junctions reverse biased","Active region","Saturation"],"ans":1},
  {"q":"A Darlington pair provides?","opts":["Low current gain","Very high current gain","Zero voltage gain","High voltage gain"],"ans":1},
  {"q":"IC fabrication process starts with?","opts":["Packaging","Testing","Silicon wafer","Metal deposition"],"ans":2},
  {"q":"The Early effect in BJT refers to?","opts":["Variation of β with temperature","Variation of IC with VCE","Breakdown","Thermal runaway"],"ans":1},
  {"q":"The notation nbspVT in diode equation stands for?","opts":["Threshold voltage","Thermal voltage","Terminal voltage","Transition voltage"],"ans":1},
  {"q":"The ideal voltage gain of a non-inverting op-amp is?","opts":["Rf/Rin","-(Rf/Rin)","1+Rf/Rin","Rin/Rf"],"ans":2},
  {"q":"Barkhausen criteria for oscillation requires loop gain to be?","opts":["Less than 1","Equal to 1","Greater than 1","Zero"],"ans":1},
  {"q":"A tunnel diode is used in?","opts":["Rectification","High-frequency oscillators","Power supply","LED lights"],"ans":1},
  {"q":"The bandwidth of an amplifier is?","opts":["fH - fL","fH + fL","fH × fL","fH / fL"],"ans":0},
  {"q":"Varactor diode is used as?","opts":["Amplifier","Variable capacitor","Current regulator","Rectifier"],"ans":1},
  {"q":"Which configuration has no current gain but voltage gain?","opts":["Common emitter","Common base","Common collector","Darlington"],"ans":1},
  {"q":"Op-amp comparator compares?","opts":["Frequencies","Two input voltages","Resistances","Currents"],"ans":1},
  {"q":"The unity gain bandwidth of op-amp means?","opts":["Gain=1 at DC","Frequency at which gain=1","Maximum bandwidth","Infinite bandwidth"],"ans":1},
  {"q":"Thermal runaway in BJT is prevented by?","opts":["Increasing VCC","Using emitter resistance","Removing base bias","Using PNP transistor"],"ans":1},
  {"q":"Slew rate of op-amp is?","opts":["Maximum frequency","Maximum rate of output voltage change","Gain bandwidth product","Input offset voltage"],"ans":1},
  {"q":"A Schottky diode has lower forward voltage because?","opts":["It's made of Germanium","It uses metal-semiconductor junction","It has no depletion region","It is reverse biased"],"ans":1},
  {"q":"The function of bypass capacitor in amplifier?","opts":["Block AC","Pass AC and bypass emitter resistance","Smooth DC","Couple stages"],"ans":1},
  {"q":"CMRR of op-amp measures?","opts":["Maximum gain","Ability to reject common-mode signals","Slew rate","Bandwidth"],"ans":1},
  {"q":"Majority carriers in n-type semiconductor are?","opts":["Holes","Protons","Electrons","Ions"],"ans":2},
  {"q":"The region between VBE(on) and breakdown in BJT is?","opts":["Cutoff","Saturation","Active region","Ohmic"],"ans":2},
  {"q":"A phase shift oscillator uses how many RC stages?","opts":["1","2","3","4"],"ans":2},
  {"q":"The input offset voltage of an ideal op-amp is?","opts":["Infinite","1 mV","Zero","Variable"],"ans":2},
],
}

def build_js_block(subject_key, questions):
    lines = [f'  "{subject_key}": [']
    for i, q in enumerate(questions):
        comma = "," if i < len(questions)-1 else ""
        opts = ', '.join(f'"{o}"' for o in q["opts"])
        lines.append(f'    {{')
        lines.append(f'      "question": "{q["q"]}",')
        lines.append(f'      "options": [{opts}],')
        lines.append(f'      "correctAnswer": {q["ans"]}')
        lines.append(f'    }}{comma}')
    lines.append('  ]')
    return '\n'.join(lines)

out_dir = os.path.join(os.path.dirname(__file__), '..', 'frontend', 'assets')
out_file = os.path.join(out_dir, 'quiz_sem2.js')

blocks = []
keys = list(SEM2.keys())
for i, key in enumerate(keys):
    comma = "," if i < len(keys)-1 else ""
    blocks.append(build_js_block(key, SEM2[key]) + comma)

content = 'const quizDataSem2 = {\n' + '\n'.join(blocks) + '\n};\n'
with open(out_file, 'w', encoding='utf-8') as f:
    f.write(content)

for key, qs in SEM2.items():
    assert len(qs) == 50, f"{key} has {len(qs)} questions"
    texts = [q['q'] for q in qs]
    assert len(set(texts)) == 50, f"{key} has duplicate questions"

print(f"[OK] quiz_sem2.js generated with {len(SEM2)} subjects, 50 questions each.")
