import os

SEM5 = {
"sem5-ml": [
  {"q":"ML stands for?","opts":["Machine Learning","Machine Logic","Molecular Learning","Mobile Logic"],"ans":0},
  {"q":"Supervised learning requires?","opts":["Labeled data","Unlabeled data","No data","Random data"],"ans":0},
  {"q":"Unsupervised learning finds?","opts":["Labels","Patterns/Clusters in unlabeled data","Correct answers","Target variables"],"ans":1},
  {"q":"Regression predicts?","opts":["Categories","Continuous values","Clusters","Images"],"ans":1},
  {"q":"Classification predicts?","opts":["Continuous values","Discrete categories/labels","Clusters","Probabilities only"],"ans":1},
  {"q":"Overfitting occurs when?","opts":["Model is too simple","Model learns noise in training data too well","Model generalizes well","Data is missing"],"ans":1},
  {"q":"Underfitting occurs when?","opts":["Model is too complex","Model is too simple to capture patterns","Model has zero bias","Model has zero variance"],"ans":1},
  {"q":"A training set is used to?","opts":["Evaluate final model","Train the model","Fine-tune hyperparameters only","Test for bias"],"ans":1},
  {"q":"A test set is used to?","opts":["Train the model","Fine-tune hyperparameters","Evaluate final model performance on unseen data","Analyze training error"],"ans":2},
  {"q":"K-Nearest Neighbors (KNN) is?","opts":["Eager learner","Lazy learner","Parametric model","Clustering only"],"ans":1},
  {"q":"In K-Means clustering, 'K' represents?","opts":["Number of features","Number of clusters","Number of points","Number of iterations"],"ans":1},
  {"q":"Decision Trees split nodes based on?","opts":["Random choice","Information gain or Gini impurity","Distance","Mean value"],"ans":1},
  {"q":"Random Forest is an ensemble of?","opts":["Linear models","Decision Trees","Neural Networks","K-Means"],"ans":1},
  {"q":"SVM stands for?","opts":["Simple Vector Machine","Support Vector Machine","Standard Variation Model","Structured Value Matrix"],"ans":1},
  {"q":"The goal of SVM is to find?","opts":["Closest points","Hyperplane that maximizes the margin","Mean of data","Gradient"],"ans":1},
  {"q":"A kernel in SVM?","opts":["Reduces data size","Transforms data into higher-dimensional space","Is a loss function","Is a regularization term"],"ans":1},
  {"q":"Neural Networks are inspired by?","opts":["Transistors","Biological neurons","Fluid dynamics","Quantum mechanics"],"ans":1},
  {"q":"Backpropagation is used for?","opts":["Initialization","Updating weights based on error","Clustering","Feature selection"],"ans":1},
  {"q":"Deep Learning is a subset of?","opts":["AI only","Machine Learning using multi-layered neural networks","Data mining only","Traditional statistics"],"ans":1},
  {"q":"Gradient Descent is an?","opts":["Algorithm for clustering","Optimization algorithm to minimize loss function","Activation function","Normalization technique"],"ans":1},
  {"q":"Regularization (L1/L2) helps prevent?","opts":["Underfitting","Overfitting","Bias","Data loss"],"ans":1},
  {"q":"L1 regularization is also known as?","opts":["Ridge","Lasso","Elastic Net","Dropout"],"ans":1},
  {"q":"L2 regularization is also known as?","opts":["Lasso","Ridge","Dropout","Batch norm"],"ans":1},
  {"q":"Precision is defined as?","opts":["TP / (TP + FP)","TP / (TP + FN)","TN / (TN + FP)","(TP + TN) / Total"],"ans":0},
  {"q":"Recall is defined as?","opts":["TP / (TP + FP)","TP / (TP + FN)","TN / (TN + FP)","TP / TN"],"ans":1},
  {"q":"F1-score is?","opts":["Sum of precision and recall","Harmonic mean of precision and recall","Product of precision and recall","Mean of accuracy and precision"],"ans":1},
  {"q":"PCA stands for?","opts":["Primary Component Analysis","Principal Component Analysis","Predictive Component Analysis","Private Cloud Access"],"ans":1},
  {"q":"PCA is used for?","opts":["Clustering","Dimensionality reduction","Classification","Regression"],"ans":1},
  {"q":"Logarithmic loss (LogLoss) is used for?","opts":["Regression","Classification (probabilistic)","Clustering","PCA"],"ans":1},
  {"q":"Bias-Variance tradeoff: A complex model has?","opts":["High bias, low variance","Low bias, high variance","Low bias, low variance","High bias, high variance"],"ans":1},
  {"q":"Bias-Variance tradeoff: A simple model has?","opts":["High bias, low variance","Low bias, high variance","High bias, high variance","Low bias, low variance"],"ans":0},
  {"q":"The sigmoid function outputs values between?","opts":["-1 and 1","0 and 1","0 and 100","-Infinity and Infinity"],"ans":1},
  {"q":"Softmax function is used in?","opts":["Binary classification","Multi-class classification","Linear regression","Clustering"],"ans":1},
  {"q":"Reinforcement learning involves?","opts":["Labels","Clusters","Agents and rewards","Unlabeled data only"],"ans":2},
  {"q":"The 'learning rate' in gradient descent controls?","opts":["Final accuracy","Step size towards minimum of loss function","Number of layers","Batch size"],"ans":1},
  {"q":"One-hot encoding is used for?","opts":["Scaling numerical data","Converting categorical data into numerical vectors","Regularization","Normalization"],"ans":1},
  {"q":"What is a Confusion Matrix?","opts":["Matrix of errors","Table showing performance of classification model","Correlation matrix","Weight matrix"],"ans":1},
  {"q":"Boosting is an ensemble technique that?","opts":["Trains models in parallel","Trains models sequentially, improving on previous errors","Randomly samples data","Reduces variance only"],"ans":1},
  {"q":"Bagging (Bootstrap Aggregating) is used to?","opts":["Increase bias","Reduce variance by averaging multiple models","Speed up training","Choose features"],"ans":1},
  {"q":"XGBoost stands for?","opts":["Xtreme Gradient Boosting","Extended Gradient Boosting","X-factor Boosting","Extra Gradient Boosting"],"ans":0},
  {"q":"Cross-validation is used to?","opts":["Train faster","Assess model reliability and prevent overfitting","Store data","Encrypt data"],"ans":1},
  {"q":"Naive Bayes is based on which theorem?","opts":["Pythagorean theorem","Bayes' Theorem","Central Limit Theorem","Master Theorem"],"ans":1},
  {"q":"'Naive' in Naive Bayes assumes?","opts":["Features are dependent","Features are independent","Model is simple","Data is gaussian"],"ans":1},
  {"q":"Standardization (Z-score) scales data to?","opts":["Range [0, 1]","Mean 0 and variance 1","Mean 1 and variance 0","Any range"],"ans":1},
  {"q":"Normalization (Min-Max scaling) scales data to?","opts":["Range [0, 1]","Mean 0 and variance 1","Mean 10","Range [-1, 1] only"],"ans":0},
  {"q":"The ROC curve plots?","opts":["Precision vs Recall","True Positive Rate vs False Positive Rate","Accuracy vs Loss","Bias vs Variance"],"ans":1},
  {"q":"AUC (Area Under Curve) measures?","opts":["Overfitting","Overall performance across all thresholds","Training speed","Memory usage"],"ans":1},
  {"q":"Stochastic Gradient Descent (SGD) updates weights?","opts":["Once per epoch","After every single training example","After every 10 examples","At the end of training"],"ans":1},
  {"q":"Dropout in neural networks?","opts":["Removes neurons to prevent overfitting","Increases neurons","Speeds up gradient descent","Is a loss function"],"ans":0},
  {"q":"A feature is?","opts":["Model parameter","Individual measurable property or characteristic of a phenomenon","Final prediction","Random noise"],"ans":1}
],
"sem5-cd": [
  {"q":"CD in this context stands for?","opts":["Compact Disc","Compiler Design","Change Directory","Cloud Delivery"],"ans":1},
  {"q":"A compiler?","opts":["Executes code line-by-line","Translates high-level source code to low-level target code","Edits text","Manages memory"],"ans":1},
  {"q":"The first phase of a compiler is?","opts":["Syntax analysis","Lexical analysis","Code generation","Optimization"],"ans":1},
  {"q":"Lexical analysis produces?","opts":["Parse tree","Tokens","Symbol table","Object code"],"ans":1},
  {"q":"What is a token?","opts":["A type of error","A sequence of characters with a collective meaning (e.g., keyword, id)","A machine instruction","A line of code"],"ans":1},
  {"q":"Syntax analysis is also called?","opts":["Scanning","Parsing","Generation","Loading"],"ans":1},
  {"q":"Parsing checks for?","opts":["Logical errors","Grammatical structure of source code","Variable types","Runtime exceptions"],"ans":1},
  {"q":"Context-Free Grammar (CFG) is used in which phase?","opts":["Lexical","Syntax","Code gen","Optimization"],"ans":1},
  {"q":"Semantic analysis checks for?","opts":["Tokens","Type mismatches and logical consistency","Grammar","Characters"],"ans":1},
  {"q":"The symbol table stores?","opts":["Source code","Information about identifiers (names, types, scope)","Only keywords","Error messages"],"ans":1},
  {"q":"Intermediate Code Generation (ICG) produces?","opts":["Target code","Architecture-independent machine-like code (e.g., 3-address code)","Tokens","Source code"],"ans":1},
  {"q":"Code optimization aims to?","opts":["Write new code","Make target code faster or use less space","Find bugs","Generate tokens"],"ans":1},
  {"q":"The last phase of a compiler is?","opts":["Syntax analysis","Code generation","Intermediate representation","Lexical analysis"],"ans":1},
  {"q":"Code generation converts?","opts":["Tokens to tree","Intermediate representation to target machine language","Source to tokens","ASCII to Binary"],"ans":1},
  {"q":"A Lexical analyzer is also known as?","opts":["Parser","Scanner","Linker","Interpreter"],"ans":1},
  {"q":"Which tool is used for lexical analysis?","opts":["YACC","LEX/Flex","GCC","GDB"],"ans":1},
  {"q":"Which tool is used for generating parsers?","opts":["Bison/YACC","LEX","Git","Make"],"ans":0},
  {"q":"Left-most derivation is used in?","opts":["Bottom-up parsing","Top-down parsing","ICG","Optimization"],"ans":1},
  {"q":"Bottom-up parsing starts from?","opts":["Root","Leaves (tokens) and works up towards the start symbol","Mid-section","End of file"],"ans":1},
  {"q":"Recursive descent is a type of?","opts":["Bottom-up parser","Top-down parser","Code optimizer","Lexer"],"ans":1},
  {"q":"LR parsing stands for?","opts":["Left-to-right, Right-most derivation","Left-to-right, Left-most derivation","Logic-Reasoning","Linear-Regression"],"ans":0},
  {"q":"LL(1) parser stands for?","opts":["Left-to-right, Left-most derivation with 1 lookahead","Linear-Logic","Leaf-Level","Long-Loop"],"ans":0},
  {"q":"A DAG in compiler design stands for?","opts":["Direct Access Group","Directed Acyclic Graph","Digital Analysis Group","Direct Annotated Grammar"],"ans":1},
  {"q":"DAG is used for?","opts":["Grammar checking","Identifying common sub-expressions in code optimization","Lexical analysis","Memory management"],"ans":1},
  {"q":"Static checking includes?","opts":["Runtime check","Type checking and flow of control checking at compile-time","User input check","Hardware check"],"ans":1},
  {"q":"Three-address code?","opts":["Has only 3 lines","Uses at most three addresses/operands per instruction","Is for 3-bit CPUs","Only uses addresses 1, 2, 3"],"ans":1},
  {"q":"Static single assignment (SSA) form?","opts":["Each variable assigned exactly once","One variable for everything","Simplified syntax","Assembly code"],"ans":0},
  {"q":"Optimization: Loop unrolling?","opts":["Removing loops","Replicating loop body to reduce branching overhead","Increasing loop count","Recursive call"],"ans":1},
  {"q":"Optimization: Constant folding?","opts":["Replacing constants with variables","Evaluating constant expressions at compile-time","Folding the source code","Hashing constant values"],"ans":1},
  {"q":"Optimization: Dead code elimination?","opts":["Removing code that is never executed or needed","Adding comments","Refactoring functions","Debugging code"],"ans":0},
  {"q":"The handle of a sentential form is?","opts":["The entire line","A substring that matches the right side of a production","A token","The first character"],"ans":1},
  {"q":"Operator precedence parsing is for?","opts":["All grammars","Small class of grammars (operator grammars)","Lexical tokens","Code generation"],"ans":1},
  {"q":"LALR stands for?","opts":["Linear-Attribute-Logic-Reason","Look-Ahead LR","Logic-Annotated-LR","Long-Address-LR"],"ans":1},
  {"q":"The input to the syntax analyzer is?","opts":["Characters","Tokens from lexical analyzer","Parse tree","Machine code"],"ans":1},
  {"q":"Abstract Syntax Tree (AST) is?","opts":["Concrete parse tree","Simplified tree representation of source code structure","List of errors","Symbol table"],"ans":1},
  {"q":"Shift-reduce is the basic operation of?","opts":["Top-down parsers","Bottom-up parsers","Lexers","Optimizers"],"ans":1},
  {"q":"Semantic gap is the difference between?","opts":["Memory and CPU","High-level programming concepts and machine instructions","Syntax and Logic","Two compilers"],"ans":1},
  {"q":"Target machine features?","opts":["Don't matter","Are critical for code generation (register count, instruction set)","Only matter for lexing","Are simulated"],"ans":1},
  {"q":"Register allocation assigns?","opts":["Memory addresses","Variables to machine registers","Tokens to types","Files to disk"],"ans":1},
  {"q":"The cross-compiler?","opts":["Compiles on one platform for another platform","Compiles cross-platform code","Is a bad compiler","Swaps two files"],"ans":0},
  {"q":"Runtime storage management handles?","opts":["Stack and Heap allocation during execution","File storage","Symbol table storage","Permanent disk storage"],"ans":0},
  {"q":"Activation record stores?","opts":["Global variables","Procedure/function-specific data (params, return addr, local vars)","Entire program","Compiler version"],"ans":1},
  {"q":"Binding?","opts":["Tying two files","Mapping between a name and an object or location","Indenting code","Parsing line"],"ans":1},
  {"q":"Backpatching solves?","opts":["Logic errors","Problems where jump target address is unknown during generation","Syntax errors","Memory leaks"],"ans":1},
  {"q":"Peephole optimization?","opts":["Scanning entire file","Examining short sequences of target instructions for simple improvements","Removing comments","Looking at CPU"],"ans":1},
  {"q":"The 'Bootstrapping' of a compiler?","opts":["Rebooting PC","Writing a compiler for a language in its own language","Loading OS","Installing software"],"ans":1},
  {"q":"Error recovery in parsing?","opts":["Crashing program","Attempting to continue parsing after finding an error","Deleting code","Asking user"],"ans":1},
  {"q":"Closure in LR parsing is used to?","opts":["Close the file","Expand items in a set to find all reachable items","End the program","Delete memory"],"ans":1},
  {"q":"A regular expression is used to?","opts":["Define grammars","Define lexical patterns for tokens","Generate code","Optimize loops"],"ans":1},
  {"q":"Ambiguous grammar has?","opts":["No parse tree","More than one parse tree for some string","Invalid tokens","Complexity"],"ans":1}
],
"sem5-ai": [
  {"q":"AI stands for?","opts":["Artificial Intelligence","Automated Logic","Advanced Inclusion","Analysis of Information"],"ans":0},
  {"q":"The 'Turing Test' measures?","opts":["Computer speed","Machine's ability to exhibit intelligent behavior equivalent to human","Memory capacity","Algorithm complexity"],"ans":1},
  {"q":"The 'Father of AI' is generally considered to be?","opts":["Alan Turing","John McCarthy","Grace Hopper","Bill Gates"],"ans":1},
  {"q":"Weak AI (Narrow AI) is?","opts":["Human-level intelligence","AI designed for a specific task","Conscious AI","Super intelligence"],"ans":1},
  {"q":"Strong AI (AGI) is?","opts":["Task-specific AI","AI that can understand or learn any intellectual task a human can","A simple calculator","A search engine"],"ans":1},
  {"q":"State space search involves?","opts":["Searching for files","Initial state, goal state, and actions to transition","Finding physical space","Database querying"],"ans":1},
  {"q":"Breadth-First Search (BFS) is?","opts":["LIFO","FIFO using queue","Greedy","Heuristic-based"],"ans":1},
  {"q":"Depth-First Search (DFS) uses?","opts":["Queue","Stack (LIFO)","Heap","Random access"],"ans":1},
  {"q":"Which search is informed?","opts":["BFS","DFS","A* search","IDS"],"ans":2},
  {"q":"Heuristic function h(n) estimates?","opts":["Exact cost","Cost from node n to the goal","Cost from start to n","Total path length"],"ans":1},
  {"q":"A* search evaluates nodes using?","opts":["f(n) = g(n) + h(n)","f(n) = g(n)","f(n) = h(n)","f(n) = g(n) - h(n)"],"ans":0},
  {"q":"In A*, g(n) represents?","opts":["Estimated cost to goal","Path cost from start to node n","Number of nodes","Heuristic value"],"ans":1},
  {"q":"Admissible heuristic means?","opts":["Never overestimates true cost","Never underestimates true cost","Always accurate","Zero value"],"ans":0},
  {"q":"Minimax algorithm is used in?","opts":["Clustering","Game theory/Game playing (adversarial search)","Linear regression","Image processing"],"ans":1},
  {"q":"Alpha-Beta pruning helps in Minimax by?","opts":["Adding branches","Eliminating branches that cannot affect final decision","Smoothing data","Increasing depth"],"ans":1},
  {"q":"Hill Climbing is a type of?","opts":["Global search","Local search/Optimization","Backtracking","Informed search"],"ans":1},
  {"q":"Local maxima in Hill Climbing?","opts":["The best solution","A peak higher than its neighbors but not necessarily the global optimum","The starting point","A flat area"],"ans":1},
  {"q":"Knowledge Representation includes?","opts":["Binary code only","Semantic Networks, Frames, Logic, Rules","Only text files","Neural networks only"],"ans":1},
  {"q":"First-Order Logic (FOL) allows?","opts":["Only simple booleans","Quantifiers like 'For All' and 'There Exists'","No variables","Graphics"],"ans":1},
  {"q":"An Expert System?","opts":["Replaces humans","Emulates decision-making ability of a human expert","Is a database","Is a hardware component"],"ans":1},
  {"q":"Inference Engine?","opts":["Part of car","Component of expert system applying rules to data","A hardware chip","A graphics engine"],"ans":1},
  {"q":"Fuzzy Logic?","opts":["Is incorrect logic","Deals with degrees of truth rather than absolute true/false","Is binary","Is random"],"ans":1},
  {"q":"Semantic Net is?","opts":["An internet protocol","Knowledge representation using nodes and links","A weight matrix","A social network"],"ans":1},
  {"q":"What is an Agent?","opts":["Spy","Anything that perceives its environment through sensors and acts via actuators","A user","A database"],"ans":1},
  {"q":"PEAS for an agent stands for?","opts":["Program, Entry, Action, State","Performance, Environment, Actuators, Sensors","Plan, Execute, Analyze, Save","Process, Evaluate, Access, System"],"ans":1},
  {"q":"Natural Language Processing (NLP) is?","opts":["Programming in English","AI for understanding and generating human language","Graphics design","Low-level coding"],"ans":1},
  {"q":"Supervised vs Unsupervised AI?","opts":["Supervised has feedback/labels","Unsupervised has labels","No difference","Supervised is faster"],"ans":0},
  {"q":"Deep Learning used in AI is mostly?","opts":["Neural networks with many layers","Simple logic gates","Decision trees","Assembly code"],"ans":0},
  {"q":"Probabilistic reasoning uses?","opts":["Certainty","Probability theory to handle uncertainty","Absolute truth","Fixed rules only"],"ans":1},
  {"q":"Bayesian Networks represent?","opts":["Linear sequences","Probabilistic relationships among variables using DAG","Hierarchical trees","Sorted lists"],"ans":1},
  {"q":"Reinforcement Learning: Rewards?","opts":["Used to punish agent","Feedback signal guiding agent towards goals","Cash payments","Random numbers"],"ans":1},
  {"q":"The 'Exploration vs Exploitation' trade-off?","opts":["Trying new things vs using known good ones","Binary choice only","Search algorithm type","Memory management"],"ans":0},
  {"q":"Genetic Algorithms are inspired by?","opts":["Physics","Biological evolution (selection, crossover, mutation)","Chemistry","Math"],"ans":1},
  {"q":"Ontology in AI?","opts":["Study of bugs","Formal specification of concepts and relationships in a domain","Algorithm for sorting","Hardware schema"],"ans":1},
  {"q":"Planning in AI involves?","opts":["Calendar setup","Finding sequence of actions to achieve goal","Writing code","Data entry"],"ans":1},
  {"q":"Computer Vision?","opts":["Watching TV","Enabling machines to perceive and interpret visual data","Better monitor design","Camera settings"],"ans":1},
  {"q":"LISP and Prolog are?","opts":["Graphics libraries","Programming languages historically used for AI","Databases","OS names"],"ans":1},
  {"q":"Symbolic AI?","opts":["Uses numbers mostly","AI based on high-level human-readable symbols and logic","Neural nets","Hardware symbols"],"ans":1},
  {"q":"Sub-symbolic AI?","opts":["Neural networks and connectionism","Logic-based AI","Expert systems","Text processing"],"ans":0},
  {"q":"What is a Perceptron?","opts":["A deep network","Simplest form of a neural network (binary classifier)","A search algorithm","A file format"],"ans":1},
  {"q":"Knowledge Base?","opts":["A book","Collection of facts, rules, and information for an AI system","A hardware drive","A website"],"ans":1},
  {"q":"Forward Chaining?","opts":["Starts with goal","Starts with facts and applies rules to reach goal","Backward search","Recursive calls"],"ans":1},
  {"q":"Backward Chaining?","opts":["Starts with facts","Starts with goal and works backward to find supporting facts","Linear search","LIFO"],"ans":1},
  {"q":"Condition-Action rules?","opts":["IF-THEN statements","WHILE loops","Variable declarations","Comments"],"ans":0},
  {"q":"Breadth of AI?","opts":["One narrow area","Multidisciplinary field involving CS, Math, Psych, Philosophy","Only coding","Only hardware"],"ans":1},
  {"q":"Overfitting in AI?","opts":["Mastering the training data too well, failing on new data","Generalizing perfectly","Too small training set","Under-training"],"ans":0},
  {"q":"Bias in AI?","opts":["Mathematical error","Unfairness or systematic errors in data/algorithms","Random noise","Model weight"],"ans":1},
  {"q":"Singularity?","opts":["A black hole only","Hypothetical point where AI surpasses human intelligence","A math term","Single processor"],"ans":1},
  {"q":"AI Ethics deals with?","opts":["Speed of AI","Responsible development and impact of AI on society","Cost of AI","GPU power"],"ans":1},
  {"q":"Robotics is?","opts":["Pure software","Integration of AI with physical hardware and control","Pure hardware","Toy design"],"ans":1}
],
"sem5-st": [
  {"q":"Software Testing aims to?","opts":["Write code","Identify defects and ensure quality","Manage project","Design UI"],"ans":1},
  {"q":"Verification asks?","opts":["Are we building the right product?","Are we building the product right?","Is the client happy?","Does it look good?"],"ans":1},
  {"q":"Validation asks?","opts":["Are we building the product right?","Are we building the right product? (meeting user requirements)","Is the code clean?","Is the database fast?"],"ans":1},
  {"q":"A defect/bug is?","opts":["A feature","Deviation from expected behavior","Code comment","New requirement"],"ans":1},
  {"q":"Error vs Failure?","opts":["They are identical","Error is human mistake; Failure is deviation in result","Failure is human mistake","Error is runtime only"],"ans":1},
  {"q":"Static Testing?","opts":["Running the app","Examining code/documents without execution","Speed testing","Server testing"],"ans":1},
  {"q":"Dynamic Testing?","opts":["Reviewing code","Evaluating system by executing it","Writing documentation","UI design"],"ans":1},
  {"q":"Unit Testing?","opts":["Testing whole system","Testing individual components/functions","User testing","Acceptance testing"],"ans":1},
  {"q":"Integration Testing check for?","opts":["Single function errors","Interface defects between modules","Total system performance","Spelling errors"],"ans":1},
  {"q":"System Testing evaluates?","opts":["Single unit","Fully integrated system against requirements","Only the database","External APIs only"],"ans":1},
  {"q":"Acceptance Testing (UAT)?","opts":["Final test by users/customers before release","Developer testing","Unit testing","Stress testing"],"ans":0},
  {"q":"Regression Testing?","opts":["Testing first time","Re-testing to ensure changes haven't broken existing features","Performance check","Security check"],"ans":1},
  {"q":"Smoke Testing?","opts":["Finding details","Preliminary testing to ensure build is stable enough for further tests","Performance test","Stress test"],"ans":1},
  {"q":"Sanity Testing?","opts":["Detailed check","Quick broad check after bug fix to verify logical sanity","System test","Security test"],"ans":1},
  {"q":"Black-box Testing?","opts":["Knowledge of internal code","No knowledge of internal code (functionality only)","Tests hardware","Tests privacy"],"ans":1},
  {"q":"White-box Testing?","opts":["No code knowledge","Full knowledge of internal code and logic","User testing","Stress testing"],"ans":1},
  {"q":"Gray-box Testing?","opts":["Combination of black and white box","Tests and documentation","Hardware testing","Visual testing"],"ans":0},
  {"q":"Equivalence Partitioning?","opts":["Dividing data into groups that should behave similarly","Random testing","Unique data for all cases","Stress testing"],"ans":0},
  {"q":"Boundary Value Analysis (BVA)?","opts":["Testing random values","Testing values at the edges of input ranges","Testing average values","Testing text only"],"ans":1},
  {"q":"Negative Testing?","opts":["Checking for bugs","Testing with invalid inputs to ensure proper error handling","Sad testing","Limited testing"],"ans":1},
  {"q":"Usability Testing?","opts":["Checking speed","Evaluating how easy the UI is to use","Checking logic","Database check"],"ans":1},
  {"q":"Stress Testing?","opts":["Normal load","Testing system behavior under extreme load/pressure","Testing UI","Manual test"],"ans":1},
  {"q":"Load Testing?","opts":["Zero load","Testing system under expected peak load","Testing code","Parsing"],"ans":1},
  {"q":"Alpha Testing?","opts":["External users","Internal testing performed within the organization","Beta testing","Final release"],"ans":1},
  {"q":"Beta Testing?","opts":["Internal testing","External testing by real users in real environments","Unit testing","Automated test"],"ans":1},
  {"q":"Performance Testing?","opts":["UI test","Evaluating speed, responsiveness, stability","Logic test","Bug tracking"],"ans":1},
  {"q":"Test Case includes?","opts":["Code","Steps, Expected Result, Preconditions, Inputs","Bug ID only","User manual"],"ans":1},
  {"q":"Test Plan?","opts":["Final report","Strategy document describing scope, approach, resources for testing","Code summary","Deployment guide"],"ans":1},
  {"q":"STLC stands for?","opts":["Software Test Life Cycle","Source Testing Logic Control","System Test Local Center","Software Trial Loop Control"],"ans":0},
  {"q":"Requirement Traceability Matrix (RTM)?","opts":["Mapping requirements to test cases","List of bugs","Code diagram","Database map"],"ans":0},
  {"q":"Defect Lifecycle/Bug Lifecycle?","opts":["States a bug goes through (New, Open, Fixed, etc.)","Developer's day","User activity","File history"],"ans":0},
  {"q":"Retesting?","opts":["Testing everything","Testing a specific bug fix specifically","Testing hardware","Beta test"],"ans":1},
  {"q":"Non-functional Testing?","opts":["Functionality only","Focuses on performance, security, reliability","Logic only","UI text"],"ans":1},
  {"q":"Security Testing?","opts":["Checking buttons","Identifying vulnerabilities and protecting data","Checking speed","Backup check"],"ans":1},
  {"q":"Compatibility Testing?","opts":["One browser only","Testing across different browsers, OS, and devices","Speed test","Stress test"],"ans":1},
  {"q":"Maintenance Testing?","opts":["First build","Testing after system is operational and updated/hot-fixed","Setup test","Installation test"],"ans":1},
  {"q":"Test Harness?","opts":["Project manager","Tools/Framework to execute tests and monitor results","Safety belt","Backup drive"],"ans":1},
  {"q":"Automation Testing?","opts":["Manual entry","Using scripts/tools to execute test cases automatically","Visual check","Human review"],"ans":1},
  {"q":"Exploratory Testing?","opts":["Formal test cases","Simultaneous learning, test design, and test execution (less formal)","Scripted test","Unit test"],"ans":1},
  {"q":"V-Model in STLC?","opts":["Vertical model","Verification and Validation model (development and testing phases in parallel)","Value model","Variable model"],"ans":1},
  {"q":"Mutation Testing?","opts":["Testing viruses","Modifying code slightly to see if test cases find the change (test quality test)","Deleting code","Beta test"],"ans":1},
  {"q":"Agile Testing?","opts":["Final phase testing","Continuous testing throughout development iterations","Waterfall testing","No testing"],"ans":1},
  {"q":"Test Coverage measures?","opts":["Bug count","Amount of testing performed on a system (code, requirements)","Number of testers","Time spent"],"ans":1},
  {"q":"Standard for software testing?","opts":["ISO 9001","ISO/IEC/IEEE 29119","ISO 14001","HTTP"],"ans":1},
  {"q":"Cyclomatic Complexity?","opts":["Number of files","Measure of logical complexity of a program","Number of bugs","Code size"],"ans":1},
  {"q":"Stub vs Driver?","opts":["Both are tools","Stub (called by module); Driver (calls module)","Driver is for OS","Stubs are bugs"],"ans":1},
  {"q":"End-to-end (E2E) testing?","opts":["First and last line","Verifying the complete workflow from start to finish","UI only","Backend only"],"ans":1},
  {"q":"Test Exit Criteria?","opts":["Lunch break","Conditions that define when testing is complete","First bug found","Code build success"],"ans":1},
  {"q":"Code Walkthrough?","opts":["Running code","Informal peer review of source code","Debugging session","Refactoring"],"ans":1},
  {"q":"Static Analysis?","opts":["Dynamic check","Analyzing code using tools without execution","User interview","Beta test"],"ans":1}
],
"sem5-cc": [
  {"q":"Cloud Computing provides?","opts":["On-demand computing resources over the internet","Physical hard drives only","Local software only","Offline storage"],"ans":0},
  {"q":"NIST stands for?","opts":["National Information Security Team","National Institute of Standards and Technology","Network Inclusion Systems Tool","Natural Interface Standard"],"ans":1},
  {"q":"Cloud feature: Scalability?","opts":["Fixed size","Ability to grow or shrink resources as per demand","Slow performance","Physical size of server"],"ans":1},
  {"q":"Cloud feature: On-demand self-service?","opts":["Manual setup by provider","Provisioning resources without human intervention from provider","Call for support","Local setup"],"ans":1},
  {"q":"IaaS stands for?","opts":["Infrastructure as a Service","Information as a Service","Internet as a Software","Interface and System"],"ans":0},
  {"q":"PaaS stands for?","opts":["Product as a Service","Platform as a Service","Process as a Script","Public as a System"],"ans":1},
  {"q":"SaaS stands for?","opts":["System as a Service","Software as a Service","Server as a Software","Storage and Service"],"ans":1},
  {"q":"Example of SaaS?","opts":["AWS EC2","Google Workspace/Gmail","Microsoft Azure VMs","Cisco Routers"],"ans":1},
  {"q":"Example of IaaS?","opts":["Amazon EC2/S3","Salesforce","DropBox","WhatsApp"],"ans":0},
  {"q":"Public Cloud is?","opts":["Shared among multiple organizations over public internet","Reserved for one company","Internal data center","Private server"],"ans":0},
  {"q":"Private Cloud is?","opts":["Shared publicly","Dedicated to a single organization (on-prem or off-prem)","Internet-only","A VPN"],"ans":1},
  {"q":"Hybrid Cloud?","opts":["New technology","Combination of public and private clouds","A specific software","Local hosting only"],"ans":1},
  {"q":"Elasticity refers to?","opts":["Physical flexibility","Automatic scaling of resources in real-time","Database size","Broadband speed"],"ans":1},
  {"q":"Pay-per-use (Utility computing) means?","opts":["Flat monthly fee","Charging based on actual resource consumption","Free service","One-time purchase"],"ans":1},
  {"q":"Multi-tenancy?","opts":["Multiple owners for one PC","Multiple users/customers sharing same physical infrastructure","One user per server","No security"],"ans":1},
  {"q":"Virtualization?","opts":["New hardware","Software technology that creates virtual versions of hardware/OS","Video games","Physical server moving"],"ans":1},
  {"q":"Hypervisor (VMM) is?","opts":["Fast CPU","Software that manages and runs virtual machines","A visual tool","Monitor management"],"ans":1},
  {"q":"Type 1 Hypervisor (Bare-metal)?","opts":["Runs on top of OS","Runs directly on hardware","A browser plugin","Mobile app"],"ans":1},
  {"q":"Type 2 Hypervisor (Hosted)?","opts":["Runs on hardware","Runs as an application on an existing OS","Primary OS","Firmware"],"ans":1},
  {"q":"Cloud security concerns?","opts":["Speed","Data privacy, unauthorized access, loss of control","Monitor quality","Keyboard layout"],"ans":1},
  {"q":"AWS stands for?","opts":["Amazon Web Services","Advanced Web Solutions","American Web Server","Alpha Web Screen"],"ans":0},
  {"q":"Microsoft's cloud platform is called?","opts":["AWS","Azure","GCP","iCloud"],"ans":1},
  {"q":"Google's cloud platform is?","opts":["GCP (Google Cloud Platform)","SkyDrive","CloudOne","BlueCloud"],"ans":0},
  {"q":"Community Cloud?","opts":["Public","Infrastructure shared by several organizations with shared concerns (e.g., gov, edu)","Internal only","Global"],"ans":1},
  {"q":"Resource Pooling?","opts":["Swimming pool","Provider's resources are shared by many consumers","Deleting files","Hardware repair"],"ans":1},
  {"q":"Snapshot in Cloud?","opts":["Photo of server","State of a VM at a specific point in time","Slow internet","CPU speed"],"ans":1},
  {"q":"Serverless Computing (FaaS)?","opts":["No servers exist","Developers write code (functions) without managing server infrastructure","Slow servers","Manual servers"],"ans":1},
  {"q":"Cloud Storage example?","opts":["RAM","Amazon S3 / Google Drive / OneDrive","CPU Cache","Local HDD"],"ans":1},
  {"q":"VPC stands for?","opts":["Virtual Private Cloud","Variable Process Control","Visual Project Center","Virtual Public Connection"],"ans":0},
  {"q":"SLA stands for?","opts":["System Logic Action","Service Level Agreement (defines uptime/guarantees)","Software Layer Access","Single Logic Area"],"ans":1},
  {"q":"Edge Computing?","opts":["Center of network","Processing data near the source/edge of network (IoT)","Cloud only","Slow processing"],"ans":1},
  {"q":"Fog Computing?","opts":["Cloud near ground","Extending cloud to the edge (intermediary layer)","Rainy weather","Offline tool"],"ans":1},
  {"q":"Big Data in Cloud?","opts":["Small files","Large scale data processing using cloud scale","Text only","Random data"],"ans":1},
  {"q":"Data Migration?","opts":["Deleting data","Moving data/apps from on-prem to cloud or between clouds","Data backup","Formatting drive"],"ans":1},
  {"q":"IAM stands for?","opts":["Internal Access Model","Identity and Access Management","Internet App Manager","Integrated Area Model"],"ans":1},
  {"q":"Containers (e.g. Docker)?","opts":["Heavy VMs","Lightweight virtualization sharing OS kernel","Physical boxes","Hardware drivers"],"ans":1},
  {"q":"Kubernetes is?","opts":["A cloud provider","Container orchestration system","A programming language","OS name"],"ans":1},
  {"q":"Disaster Recovery (DR) in cloud?","opts":["System crash only","Ability to restore data/services after a failure/disaster","Manual backup only","Logic check"],"ans":1},
  {"q":"Latency affects?","opts":["Disk space","Response time/speed of network","Storage capacity","Color depth"],"ans":1},
  {"q":"Bandwidth?","opts":["File size","Max data transfer rate of network","Memory speed","CPU cores"],"ans":1},
  {"q":"Region vs Availability Zone (AZ)?","opts":["Region is a set of AZs","AZ is a set of Regions","They are identical","Region is for users"],"ans":0},
  {"q":"Cold vs Hot Storage?","opts":["Physical temp","Infrequently accessed (cheap) vs frequently accessed (fast/pricier) data","Hardware vs Software","RAM vs Cache"],"ans":1},
  {"q":"Cloud deployment models: How many?","opts":["1","4 (Public, Private, Hybrid, Community)","8","Unlimited"],"ans":1},
  {"q":"Broad network access?","opts":["Local only","Access via standard mechanisms (mobile, tablets, laptops) over net","High speed cables only","Internal LAN"],"ans":1},
  {"q":"Measured service?","opts":["Free service","Resource usage is monitored, controlled, and reported","No monitoring","Guessing usage"],"ans":1},
  {"q":"Grid Computing vs Cloud Computing?","opts":["Cloud is evolution of Grid (shared resources)","Grid is faster","No relationship","Grid is newer"],"ans":0},
  {"q":"API economy?","opts":["Buying stock","Monetizing services through APIs in the cloud","Reducing costs","Trading servers"],"ans":1},
  {"q":"Cloud bursting?","opts":["System crash","Overflowing from private cloud to public cloud during peak loads","Exploding server","Slow loading"],"ans":1},
  {"q":"Shadow IT?","opts":["Security team","Using cloud services without IT department approval","Dark mode apps","Secret coding"],"ans":1},
  {"q":"Vendor lock-in?","opts":["Opening door","Difficulty moving from one cloud provider to another due to dependencies","Locking server","Password security"],"ans":1}
],
}

def build_js_block(subject_key, questions):
    lines = [f'  "{subject_key}": [']
    for i, q in enumerate(questions):
        comma = "," if i < len(questions)-1 else ""
        opts = ', '.join(f'"{o}"' for o in q["opts"])
        lines.append(f'    {{')
        lines.append(f'      "question": "{q["q"]}",')
        lines.append(f'      "options": [{opts}],')
        lines.append(f'      "correctAnswer": {q["ans"]}')
        lines.append(f'    }}{comma}')
    lines.append('  ]')
    return '\n'.join(lines)

out_dir = os.path.join(os.path.dirname(__file__), '..', 'frontend', 'assets')
out_file = os.path.join(out_dir, 'quiz_sem5.js')

blocks = []
keys = list(SEM5.keys())
for i, key in enumerate(keys):
    comma = "," if i < len(keys)-1 else ""
    blocks.append(build_js_block(key, SEM5[key]) + comma)

content = 'const quizDataSem5 = {\n' + '\n'.join(blocks) + '\n};\n'
with open(out_file, 'w', encoding='utf-8') as f:
    f.write(content)

for key, qs in SEM5.items():
    assert len(qs) == 50, f"{key} has {len(qs)} questions"
    texts = [q['q'] for q in qs]
    assert len(set(texts)) == 50, f"{key} has duplicate questions"

print(f"[OK] quiz_sem5.js generated with {len(SEM5)} subjects, 50 questions each.")
