import os

SEM6 = {
"sem6-dl": [
  {"q":"Deep Learning is a subset of?","opts":["Computer Vision","Machine Learning","Natural Language Processing","Robotics"],"ans":1},
  {"q":"The basic building block of a Neural Network is?","opts":["Neuron/Perceptron","Transistor","Logic Gate","Fiber"],"ans":0},
  {"q":"Activation functions introduce?","opts":["Linearity","Non-linearity","Randomness","Normalization"],"ans":1},
  {"q":"Which activation function is most common in hidden layers?","opts":["Sigmoid","Tanh","ReLU","Softmax"],"ans":2},
  {"q":"ReLU stands for?","opts":["Rectified Linear Unit","Reduced Linear Unit","Relative Logic Unit","Rectangular Unit"],"ans":0},
  {"q":"CNN stands for?","opts":["Convolutional Neural Network","Central Neural Network","Computed Network Node","Circular Neural Net"],"ans":0},
  {"q":"CNNs are primarily used for?","opts":["Wait times","Image and spatial data","Text processing only","Sorting"],"ans":1},
  {"q":"Pooling in CNNs helps to?","opts":["Increase parameters","Reduce spatial dimensions/parameters","Add noise","Reverse convolution"],"ans":1},
  {"q":"RNN stands for?","opts":["Recurrent Neural Network","Recursive Neural Network","Random Neural Network","Reverse Neural Network"],"ans":0},
  {"q":"RNNs are designed for?","opts":["Fixed-length input","Sequential/Time-series data","Images only","Clustering"],"ans":1},
  {"q":"LSTM stands for?","opts":["Long Short-Term Memory","Large Scale Training Model","Logic-State Time Model","Linear Search Time Map"],"ans":0},
  {"q":"LSTM solves which RNN problem?","opts":["Exploding gradient","Vanishing gradient","Overfitting","Underfitting"],"ans":1},
  {"q":"A 'Filter' or 'Kernel' in CNN performs?","opts":["Average only","Convolution (element-wise multiplication and sum)","Classification","Sorting"],"ans":1},
  {"q":"Deep learning models are 'deep' because?","opts":["They have many nodes","They have many hidden layers","They are complex","They use deep water"],"ans":1},
  {"q":"The 'loss function' measures?","opts":["Accuracy","Difference between predicted and actual values","Model size","Training speed"],"ans":1},
  {"q":"Optimizer (e.g. Adam, SGD)?","opts":["Increases loss","Adjusts weights to minimize loss","Deletes neurons","Normalizes data"],"ans":1},
  {"q":"Dropout is used for?","opts":["Normalization","Regularization to prevent overfitting","Data augmentation","Feature selection"],"ans":1},
  {"q":"Transfer Learning?","opts":["Moving data","Using a pre-trained model on a new, related task","Retraining from scratch","Sharing weights"],"ans":1},
  {"q":"GAN stands for?","opts":["Generative Adversarial Network","General AI Network","Genetic Algorithm Network","Grammar Analysis Net"],"ans":0},
  {"q":"GAN consists of two networks:","opts":["CNN and RNN","Generator and Discriminator","Input and Output","Encoder and Decoder"],"ans":1},
  {"q":"Autoencoders are used for?","opts":["Classification","Dimensionality reduction/Unsupervised learning","Regression","Sorting"],"ans":1},
  {"q":"Batch Normalization?","opts":["Sums all data","Normalizes inputs of each layer for stability/speed","Deletes batches","Updates weights"],"ans":1},
  {"q":"What is a 'Tensor'?","opts":["A scalar","A multi-dimensional array","A vector only","A matrix only"],"ans":1},
  {"q":"Which lib is widely used for DL?","opts":["React","TensorFlow/PyTorch","Django","Pandas"],"ans":1},
  {"q":"Data Augmentation?","opts":["Deleting data","Artificially increasing data size by transforming existing data","Merging two datasets","Encryption"],"ans":1},
  {"q":"Epoch?","opts":["One training step","One full pass over the entire training dataset","One batch","One second"],"ans":1},
  {"q":"Learning Rate?","opts":["Speed of internet","Step size during weight updates","Number of layers","Accuracy level"],"ans":1},
  {"q":"Softmax output?","opts":["Sum of 100","Probability distribution across classes (sum to 1)","Binary 0 or 1","Any number"],"ans":1},
  {"q":"Hyperparameters are set?","opts":["During training","Before training (manually tuned)","After training","Automatically by gradient"],"ans":1},
  {"q":"Weight initialization?","opts":["Setting weights to zero","Setting starting values for weights to prevent gradients from dying","Setting weights to 1","Randomizing output"],"ans":1},
  {"q":"Backpropagation follows?","opts":["Chain rule of calculus","Pythagorean theorem","Bayes' rule","Master theorem"],"ans":0},
  {"q":"Word Embeddings (e.g. Word2Vec)?","opts":["Text files","Vector representation of words capturing semantic meaning","Spelling check","Grammar rules"],"ans":1},
  {"q":"Attention Mechanism?","opts":["Focusing on all data equally","Allowing model to focus on specific parts of input sequence","Deleting inputs","Increasing memory"],"ans":1},
  {"q":"Transformer architecture relies on?","opts":["Convolution","Self-Attention","Recursion","Iteration"],"ans":1},
  {"q":"BERT is?","opts":["A cartoon","Transformer-based model for NLP","A CNN","An optimizer"],"ans":1},
  {"q":"Stochastic Gradient Descent (SGD)?","opts":["Updates once per epoch","Updates after every sample (or mini-batch)","No updates","Global search"],"ans":1},
  {"q":"Overfitting sign?","opts":["Low training loss, high validation loss","High training loss","Low validation loss","Model is fast"],"ans":0},
  {"q":"Vanishing gradient means?","opts":["Gradients become too large","Gradients become extremely small, stopping weight updates","Gradients are zero always","No error"],"ans":1},
  {"q":"Exploding gradient?","opts":["Gradients vanish","Gradients become too large, leading to instability","Model is fast","Accuracy increases"],"ans":1},
  {"q":"Fine-tuning?","opts":["Setting weights to zero","Adapting a pre-trained model by training it on specific data","Deleting layers","Data entry"],"ans":1},
  {"q":"Fully Connected (FC) layer?","opts":["Layer where every neuron connects to all neurons in next layer","Isolated layer","Input layer only","Output layer only"],"ans":0},
  {"q":"Fine-tuning usually involves?","opts":["Changing loss function","Frozen layers and small learning rate","Deleting all layers","Random weights"],"ans":1},
  {"q":"Mean Squared Error (MSE)?","opts":["Classification loss","Regression loss","Clustering loss","Accuracy measure"],"ans":1},
  {"q":"Cross-Entropy Loss?","opts":["Regression loss","Classification loss","Weight decay","Clustering"],"ans":1},
  {"q":"Early Stopping?","opts":["Stopping training after fixed epochs","Stopping training when validation performance stops improving","Shutting down PC","Deleting model"],"ans":1},
  {"q":"Object Detection task?","opts":["Identifying presence of one thing","Locating and classifying multiple objects in an image","Captioning","Generating images"],"ans":1},
  {"q":"Semantic Segmentation?","opts":["Detecting boxes","Classifying every pixel in an image","Finding text","Sorting pixels"],"ans":1},
  {"q":"Embedding space?","opts":["Storage space","D-dimensional space where vectors are located","Cloud storage","RAM"],"ans":1},
  {"q":"Residual Networks (ResNet) use?","opts":["Complex gates","Skip connections (identity shortcuts)","No layers","Recursion"],"ans":1},
  {"q":"Deep learning requires high?","opts":["Disk space only","Computational power (GPUs/TPUs)","Internet speed only","RAM only"],"ans":1}
],
"sem6-is": [
  {"q":"Information Security (IS) objective:","opts":["Speed","Confidentiality, Integrity, Availability (CIA)","Cost","Accessibility only"],"ans":1},
  {"q":"Confidentiality ensure?","opts":["Data is correct","Data is accessible to authorized users only","Data is fast","Data is backed up"],"ans":1},
  {"q":"Integrity ensures?","opts":["No unauthorized access","No unauthorized modification was made to data","High availability","Encryption"],"ans":1},
  {"q":"Cryptography is?","opts":["Study of maps","Technique of securing communication using codes","Study of coins","Database design"],"ans":1},
  {"q":"Symmetric Key Encryption?","opts":["Uses two different keys","Uses same key for encryption and decryption","No key used","Public key only"],"ans":1},
  {"q":"Asymmetric Key Encryption?","opts":["Uses same key","Uses public and private key pair","Is faster than symmetric","Requires no net"],"ans":1},
  {"q":"RSA is?","opts":["A symmetric algorithm","Popular asymmetric encryption algorithm","Hashing algorithm","Protocol"],"ans":1},
  {"q":"Digital Signature ensures?","opts":["Privacy","Authentication and non-repudiation","Encryption","Speed"],"ans":1},
  {"q":"Hashing?","opts":["Is reversible","One-way function producing fixed-length output (Digest)","Encryption","Compression"],"ans":1},
  {"q":"MD5 and SHA are?","opts":["Ciphers","Hashing algorithms","Protocols","Hardware"],"ans":1},
  {"q":"Firewall?","opts":["Physical wall","Network security system monitoring/controlling traffic","Hardware only","Software only"],"ans":1},
  {"q":"IDS stands for?","opts":["Intrusion Detection System","Internal Data System","Input Delivery Script","Inbound Data Service"],"ans":0},
  {"q":"Phishing is?","opts":["Sports","Social engineering attack to steal credentials","A virus","Encryption type"],"ans":1},
  {"q":"Malware stands for?","opts":["Malicious Hardware","Malicious Software","Many-layered Ware","Main Logic Ware"],"ans":1},
  {"q":"Ransomware?","opts":["Free software","Malware that encrypts data and demands payment for key","A virus that deletes files","A firewall"],"ans":1},
  {"q":"Brute Force Attack?","opts":["Physical attack","Trying every possible password combination","Logic attack","Social engineering"],"ans":1},
  {"q":"SQL Injection?","opts":["DB backup","Inserting malicious SQL into input to manipulate DB","Fast query","Index creation"],"ans":1},
  {"q":"XSS stands for?","opts":["Cross-Site Scripting","Extra Site Safety","Cross-Server System","XML Security Solution"],"ans":0},
  {"q":"HTTPS provides?","opts":["Faster net","Secure communication over network using SSL/TLS","More bandwidth","Privacy only"],"ans":1},
  {"q":"SSL/TLS?","opts":["Hardware protocols","Cryptographic protocols for secure communication","Encryption algorithms","Hashing tools"],"ans":1},
  {"q":"VPN stands for?","opts":["Virtual Private Network","Variable Process Node","Visual Port Name","Virtual Public Network"],"ans":0},
  {"q":"Two-Factor Authentication (2FA)?","opts":["One password","Using two different pieces of evidence to authenticate","Two passwords","Biometrics only"],"ans":1},
  {"q":"Social Engineering?","opts":["Engineering software","Manipulating people into divalging confidential info","Psychology study","Team building"],"ans":1},
  {"q":"Authorization vs Authentication?","opts":["They are same","Auth is WHO; Authorization is WHAT they can do","Auth is logic","Authorization is signup"],"ans":1},
  {"q":"DDoS stands for?","opts":["Distributed Denial of Service","Digital Data of System","Direct Delivery of Software","Distributed Data on Server"],"ans":0},
  {"q":"Zero Day Vulnerability?","opts":["New feature","Vulnerability unknown to vendor/public","Safe day","Beta bug"],"ans":1},
  {"q":"Encryption: AES?","opts":["Asymmetric","Symmetric block cipher (Standard)","Hash","Protocol"],"ans":1},
  {"q":"PKI stands for?","opts":["Public Key Infrastructure","Private Key Inclusion","Public Key Index","Personal Key Instance"],"ans":0},
  {"q":"Certificate Authority (CA)?","opts":["Government","Trusted entity that issues digital certificates","Browser","Anti-virus"],"ans":1},
  {"q":"Man-in-the-Middle (MitM)?","opts":["Helpful user","Attacker intercepts/alters communication between two parties","Chat agent","Proxy server"],"ans":1},
  {"q":"Steganography?","opts":["Bold text","Hiding information within another file (e.g. image)","Encryption","Hashing"],"ans":1},
  {"q":"Governance and Compliance?","opts":["Rules for developers","Meeting legal and regulatory security requirements (e.g. GDPR)","Writing clean code","Testing"],"ans":1},
  {"q":"Access Control List (ACL)?","opts":["Guest list","List of permissions attached to an object","Search index","Memory map"],"ans":1},
  {"q":"Physical Security?","opts":["Encryption","Locks, cameras, and guards for hardware protection","Passwords","Firewall"],"ans":1},
  {"q":"Backdoor?","opts":["Main entry","Hidden entry point into a system bypassing security","Exit only","Emergency port"],"ans":1},
  {"q":"Trojan Horse?","opts":["Helpful app","Malware disguised as legitimate software","Physical gift","Virus"],"ans":1},
  {"q":"Botnet?","opts":["Robotic arm","Network of infected computers controlled as a group","Fast network","Cloud cluster"],"ans":1},
  {"q":"Least Privilege Principle?","opts":["Give everyone admin","Give users only minimum access needed for task","No access","Random access"],"ans":1},
  {"q":"Intrusion Prevention System (IPS)?","opts":["Reports only","IDS that also takes action to stop attack","A firewall","Encryption tool"],"ans":1},
  {"q":"Kerberos?","opts":["Dog in mythology","Network authentication protocol using tickets","Encryption cipher","Anti-virus"],"ans":1},
  {"q":"Biometrics?","opts":["Passwords","Biological characteristics (fingerprint, iris) for auth","ID cards","Keys"],"ans":1},
  {"q":"Disaster Recovery Plan (DRP)?","opts":["Test plan","Strategy to restore IT operations after catastrophe","Deployment plan","Migration guide"],"ans":1},
  {"q":"Patch Management?","opts":["UI updates","Acquiring, testing, and installing software fixes","Bug tracking","File sorting"],"ans":1},
  {"q":"Vulnerability Scanning?","opts":["Writing code","Automated process of finding security weaknesses","Human review","Beta test"],"ans":1},
  {"q":"Risk Assessment?","opts":["Counting files","Identifying and evaluating security risks to assets","Testing logic","Speed test"],"ans":1},
  {"q":"Security Audit?","opts":["Fixing bugs","Systematic evaluation of security controls","Deleting logs","Code review"],"ans":1},
  {"q":"Encryption Key?","opts":["Secret code used for cipher logic","Physical key","Password hint","Hardware token"],"ans":0},
  {"q":"Key Escrow?","opts":["Deleting keys","Storing keys with a third party for recovery","Selling keys","Generating keys"],"ans":1},
  {"q":"Worm?","opts":["Physical bug","Self-replicating malware that spreads over network","A virus that needs human to open","A beneficial script"],"ans":1},
  {"q":"Non-repudiation?","opts":["Privacy","Inability to deny having sent or received a message","Integrity","Authorization"],"ans":1}
],
"sem6-bd": [
  {"q":"Big Data - Three Vs?","opts":["Volume, Velocity, Variety","Value, Virtual, Visual","Vector, Variable, View","Version, Volume, Voice"],"ans":0},
  {"q":"Volume refers to?","opts":["Speed","Scale of data (Petabytes, Zettabytes)","Diversity of types","Accuracy"],"ans":1},
  {"q":"Velocity refers to?","opts":["Data size","Speed at which data is generated and processed","Data type","Data value"],"ans":1},
  {"q":"Variety refers to?","opts":["Speed","Different forms of data (structured, unstructured, streaming)","Data size","Data accuracy"],"ans":1},
  {"q":"Two extra Vs often added:","opts":["Value and Veracity","Variable and Version","Vector and Visual","Void and Volume"],"ans":0},
  {"q":"Hadoop?","opts":["A programming language","Open-source framework for distributed storage and processing","A database","An OS"],"ans":1},
  {"q":"HDFS stands for?","opts":["Hadoop Distributed File System","High Data File Server","Hadoop Data Feedback System","Hardware Distributed File Service"],"ans":0},
  {"q":"MapReduce?","opts":["Search algorithm","Programming model for processing large data in parallel","Clustering logic","UI framework"],"ans":1},
  {"q":"The 'Map' phase?","opts":["Aggregates data","Sorts and filters data","Saves to disk","Displays data"],"ans":1},
  {"q":"The 'Reduce' phase?","opts":["Reads data","Summarizes or aggregates the 'mapped' data","Splits data","Encryption"],"ans":1},
  {"q":"NoSQL databases are?","opts":["Standard SQL","Non-relational, flexible schema databases for Big Data","Only text files","Small databases"],"ans":1},
  {"q":"Spark?","opts":["A slow engine","Fast, in-memory data processing engine","A physical item","A language"],"ans":1},
  {"q":"RDD in Spark stands for?","opts":["Resilient Distributed Dataset","Random Data Delivery","Recent Data Dictionary","Remote Data Driver"],"ans":0},
  {"q":"Hive?","opts":["A database","Data warehouse software for querying HDFS using SQL-like language","A browser","A compiler"],"ans":1},
  {"q":"Pig Latin?","opts":["A spoken language","Scripting language for Hadoop/MapReduce","A browser","A virus"],"ans":1},
  {"q":"Zookeeper manages?","opts":["Animals","Distributed coordination and configuration management","Files only","Memory only"],"ans":1},
  {"q":"Kafka?","opts":["A database","Distributed event streaming platform","A search engine","A compiler"],"ans":1},
  {"q":"Data Ingestion?","opts":["Processing data","Collecting and importing data for immediate use/storage","Deleting data","Archiving"],"ans":1},
  {"q":"Data Lake?","opts":["Structured storage","Repository storing massive amounts of raw data in native format","Sorted database","A physical lake"],"ans":1},
  {"q":"Flume is used for?","opts":["Processing","Efficiently collecting, aggregating, and moving streaming data","Sorting","Storage"],"ans":1},
  {"q":"YARN stands for?","opts":["Yet Another Resource Negotiator","YAML Resource Node","Yellow Area Resource Network","Your Area Runtime Network"],"ans":0},
  {"q":"HBase?","opts":["A relational DB","Distributed, column-oriented NoSQL database on HDFS","Memory cache","Text file"],"ans":1},
  {"q":"Structured data?","opts":["Audio files","Relational database rows (tables with types)","Text blobs","Social media posts"],"ans":1},
  {"q":"Unstructured data?","opts":["CSV files","Images, videos, audio, social media (no fixed schema)","Excel sheets","JSON files"],"ans":1},
  {"q":"Semi-structured data?","opts":["Database table","XML and JSON files (tags/keys but no rigid schema)","Text only","Random data"],"ans":1},
  {"q":"Data Mining?","opts":["Storing data","Discovering patterns in large datasets","Deleting data","Formatting drive"],"ans":1},
  {"q":"Sentiment Analysis?","opts":["Speed test","Determining emotional tone from text data","Data size check","Color analysis"],"ans":1},
  {"q":"Predictive Analytics?","opts":["Old reports","Using data to find patterns and predict future outcomes","Data entry","Sorting"],"ans":1},
  {"q":"ETL stands for?","opts":["Extract, Transform, Load","Entries, Transitions, Logics","Expert Tool Load","Elastic Text Logic"],"ans":0},
  {"q":"Vertical Scaling?","opts":["Adding more servers","Adding more power (RAM/CPU) to a single machine","Adding more HDD","Networking"],"ans":1},
  {"q":"Horizontal Scaling?","opts":["Adding more power to one PC","Adding more machines to a cluster","Increasing clock speed","Deleting files"],"ans":1},
  {"q":"Sharding?","opts":["Copying data","Splitting data across multiple servers/databases","Deleting data","Encryption"],"ans":1},
  {"q":"Replication?","opts":["Splitting data","Storing copies of data on multiple nodes for fault tolerance","Deleting data","Moving data"],"ans":1},
  {"q":"CAP Theorem?","opts":["Consistency, Availability, Partition Tolerance","Cost, Access, Power","Complexity, Accuracy, Proxy","Code, API, Process"],"ans":0},
  {"q":"BASE (NoSQL) stands for?","opts":["Basically Available, Soft state, Eventual consistency","Basic Access, Shared Entries","Binary Area System Entries","Broad Access System Entry"],"ans":0},
  {"q":"Cassandra is?","opts":["Relational DB","Distributed NoSQL database (wide-column)","Hashing tool","Compiler"],"ans":1},
  {"q":"MongoDB?","opts":["Relational DB","Popular document-oriented NoSQL database","Graph database","Assembly tool"],"ans":1},
  {"q":"Graph databases (e.g. Neo4j)?","opts":["Tables only","Use graph structures with nodes/edges for relationships","Text only","Binary only"],"ans":1},
  {"q":"Lambda Architecture?","opts":["Specific code","Processing pattern for both batch and stream data","A compiler","A CPU design"],"ans":1},
  {"q":"Real-time processing?","opts":["Delayed check","Processing data as it arrives (milliseconds to seconds latency)","Overnight task","Manual report"],"ans":1},
  {"q":"Data Visualization?","opts":["Writing text","Graphical representation of information and data","Storing data","Encrypting data"],"ans":1},
  {"q":"In-memory computing?","opts":["Primary storage on HDD","Processing data stored in RAM for high speed","Backup storage","Cache only"],"ans":1},
  {"q":"Mahout?","opts":["A browser","Machine learning library for Big Data (Hadoop)","A search engine","A compiler"],"ans":1},
  {"q":"Storm?","opts":["Weather event","Real-time computation system (streaming)","A database","A browser"],"ans":1},
  {"q":"Data scrubbing/cleaning?","opts":["Deleting everything","Removing corrupt or inaccurate records from a dataset","Formatting disk","Writing code"],"ans":1},
  {"q":"Information extraction?","opts":["Deleting info","Automatically extracting structured info from unstructured sources","Printing data","Saving data"],"ans":1},
  {"q":"Scalability?","opts":["Fixed size","Ability of system to handle increased load","Slowness","Physical weight"],"ans":1},
  {"q":"Cluster?","opts":["One fast PC","Group of computers working together as a single system","A virus","A database index"],"ans":1},
  {"q":"Fault tolerance?","opts":["Crashing on error","System's ability to continue operating after a failure","Formatting disk","Speeding up"],"ans":1},
  {"q":"Columnar storage?","opts":["Rows next to each other","Storing data by column rather than row (faster analytical queries)","Random storage","Text-only"],"ans":1}
],
"sem6-iot": [
  {"q":"IoT stands for?","opts":["Internet of Things","Internal online Tool","Integrated Office Technology","Internet of Tokens"],"ans":0},
  {"q":"Core of IoT is?","opts":["Monitors","Connectivity of physical devices to the internet","Offline databases","Paper records"],"ans":1},
  {"q":"A sensor?","opts":["Acts on environment","Detects and responds to physical input (heat, light, motion)","Stores data","Is a screen"],"ans":1},
  {"q":"An actuator?","opts":["Detects heat","Performs a physical action (moving, turning on/off)","Only displays text","Is a database"],"ans":1},
  {"q":"MQTT is?","opts":["A hardware driver","Lightweight messaging protocol for IoT (publish-subscribe)","A web browser","Encryption type"],"ans":1},
  {"q":"RFID stands for?","opts":["Radio-Frequency Identification","Resource File ID","Rapid Field Inclusion","Radio-Feedback Integration"],"ans":0},
  {"q":"NFC stands for?","opts":["Near-Field Communication","Network File Control","Nodes and Files Connection","National Frequency Center"],"ans":0},
  {"q":"IoT Gateway?","opts":["A firewall only","Device connecting IoT devices to the cloud/WAN","A router for PCs only","A battery"],"ans":1},
  {"q":"WSN stands for?","opts":["Wireless Sensor Network","Wide-Spectrum Node","Web Service Network","Wireless System Node"],"ans":0},
  {"q":"Zigbee is?","opts":["A brand of honey","Low-power, short-range wireless communication standard","A high-speed fiber","A satellite"], "ans":1},
  {"q":"Smart Home example?","opts":["Paper calendar","Thermostat controlled via phone","Analog clock","Wired light switch"],"ans":1},
  {"q":"Industrial IoT (IIoT)?","opts":["Consumer gadgets","IoT in manufacturing/industry for monitoring and efficiency","Only office tools","Only medical tools"],"ans":1},
  {"q":"Wearable IoT?","opts":["Smartwatch/Fitness trackers","Desktop PCs","Analog watches","Trousers"],"ans":0},
  {"q":"Security in IoT is challenging due to?","opts":["Too much power","Constrained resources (low RAM/CPU) on devices","High cost","Lack of internet"],"ans":1},
  {"q":"Edge computing in IoT?","opts":["Cloud only","Processing data locally on devices/near them for low latency","Slow processing","Search engine"],"ans":1},
  {"q":"CoAP stands for?","opts":["Constrained Application Protocol","Control and Process","Common Access Port","Common Application Protocol"],"ans":0},
  {"q":"M2M stands for?","opts":["Machine-to-Machine communication","Main-to-Manual","Many-to-Many","Mobile-to-Mobile"],"ans":0},
  {"q":"IoT Stack layers:","opts":["Perception, Network, Middleware, Application","Hardware only","Software only","User only"],"ans":0},
  {"q":"Perception layer?","opts":["Handles internet","Sensors and actuators (physical interaction)","Database","UI"],"ans":1},
  {"q":"Network layer in IoT?","opts":["Detects heat","Handles data transmission (Wi-Fi, Bluetooth, Zigbee)","Displays data","Logic"],"ans":1},
  {"q":"Application layer?","opts":["Physical sensors","User-facing services and analysis","Radio waves","Cables"],"ans":1},
  {"q":"IPv6 is important for IoT because?","opts":["It's newer","Provides massive address space for billions of devices","It's faster","It's safer"],"ans":1},
  {"q":"LoRaWAN?","opts":["Local Radio Network","Long Range Wide Area Network for low power devices","Fast local Wi-Fi","Satellite link"],"ans":1},
  {"q":"6LoWPAN?","opts":["IPv6 over Low-Power Wireless Personal Area Networks","New 6G network","Local Web Port","Search tool"],"ans":0},
  {"q":"Bluetooth Low Energy (BLE)?","opts":["Standard Bluetooth","Power-efficient version for short-range IoT","High-speed data transfer","Long-range Wi-Fi"],"ans":1},
  {"q":"Smart Grid?","opts":["Math tool","IoT-enabled electrical grid for efficiency and monitoring","Better battery","Physical wires"],"ans":1},
  {"q":"Precision Agriculture?","opts":["Better tractors","Using IoT sensors (soil, weather) to optimize farming","More fertilizer","Large farms"],"ans":1},
  {"q":"IoT platform example?","opts":["Windows 95","AWS IoT Core / Azure IoT Hub / ThingSpeak","Notepad","VLC Player"],"ans":1},
  {"q":"Interoperability?","opts":["Fast speed","Ability of different IoT devices/systems to work together","Privacy","Encryption"],"ans":1},
  {"q":"Fog Computing in IoT?","opts":["Cloud near sources","Intermediate layer between edge and cloud for scaling","Rainy days","Offline mode"],"ans":1},
  {"q":"Digital Twin?","opts":["A clone","Virtual replica of a physical IoT asset/system","A second monitor","Backup file"],"ans":1},
  {"q":"Latency in IoT?","opts":["Storage size","Delay in data transmission/processing (critical for real-time)","Battery life","Device cost"],"ans":1},
  {"q":"Energy harvesting?","opts":["Charging phone","Generating electrical energy from environment (solar, heat) for sensors","Electricity bill","Battery recycling"],"ans":1},
  {"q":"Actuators: Solenoid?","opts":["Light sensor","Electromagnetic device that moves a plunger","Battery","WiFi chip"],"ans":1},
  {"q":"Microcontroller commonly used in IoT?","opts":["Intel i9","Arduino / ESP8266 / Raspberry Pi / ARM Cortex","Standard PC","Mainframe"],"ans":1},
  {"q":"Raspberry Pi is?","opts":["A fruit","Single-board computer used in IoT projects","A browser","An OS"],"ans":1},
  {"q":"ESP8266 is?","opts":["CPU","Low-cost Wi-Fi microchip with full TCP/IP stack","A memory card","A screen"],"ans":1},
  {"q":"IoT analytic?","opts":["Deleting data","Processing sensor data to extract insights","Printing reports","Saving logs"],"ans":1},
  {"q":"Privacy in IoT?","opts":["Speed","Protecting user data collected by 'always-on' sensors","Hardware design","Color depth"],"ans":1},
  {"q":"Standard: IEEE 802.15.4?","opts":["Fast Wi-Fi","Technical standard for low-rate wireless personal area networks","Ethernet","HDMI"],"ans":1},
  {"q":"Beacon?","opts":["Light in sea","IoT device broadcasting signal to nearby devices (e.g. for location)","A battery","A router"],"ans":1},
  {"q":"Sensor: Accelerometer?","opts":["Heat sensor","Measures acceleration/tilt (rotation/movement)","Light sensor","Pressure sensor"],"ans":1},
  {"q":"Sensor: LDR?","opts":["Motion sensor","Light Dependent Resistor (detects brightness)","Sound sensor","Gas sensor"],"ans":1},
  {"q":"Sensor: Ultrasonic?","opts":["Heat","Measures distance using sound waves","Color sensor","Image sensor"],"ans":1},
  {"q":"IoT Cloud?","opts":["Physical cloud","Remote servers providing storage and analysis for IoT data","A browser","Local memory"],"ans":1},
  {"q":"Scalability in IoT?","opts":["Fixed count","Ability to support millions of devices and data streams","Device size","Battery capacity"],"ans":1},
  {"q":"Service-Oriented Architecture (SOA) in IoT?","opts":["Single app","Modular approach where functions are provided as services","Hardware only","User only"],"ans":1},
  {"q":"Real-time operating system (RTOS)?","opts":["Standard Windows","OS for real-time applications with strict timing constraints (Zephyr, FreeRTOS)","Linux Mint","MacOS"],"ans":1},
  {"q":"Things in IoT?","opts":["Physical objects with sensors/actuators and connectivity","Web pages only","Software code only","Users only"],"ans":0},
  {"q":"Ubiquitous computing?","opts":["Computing everywhere/around us seamlessly","Large computers","Limited access","Ancient tech"],"ans":0}
],
"sem6-mad": [
  {"q":"MAD stands for?","opts":["Mobile Application Development","Modern App Design","Mobile Access Device","Module Android Design"],"ans":0},
  {"q":"Primary mobile OS?","opts":["Windows and Linux","Android and iOS","MacOS and Ubuntu","DOS and Symbian"],"ans":1},
  {"q":"Android is based on?","opts":["Windows kernel","Linux kernel","Unix only","Proprietary kernel"],"ans":1},
  {"q":"Native App?","opts":["Generic app","App built specifically for one platform using its native language","Web app","Hybrid app"],"ans":1},
  {"q":"iOS apps are commonly built in?","opts":["Java","Swift or Objective-C","C#","Python"],"ans":1},
  {"q":"Android apps were traditionally built in?","opts":["C++","Java or Kotlin","Swift","PHP"],"ans":1},
  {"q":"Kotlin?","opts":["An OS","Modern programming language for Android development","A browser","A database"],"ans":1},
  {"q":"Hybrid App?","opts":["Native only","Web app wrapped in a native container (accesses device features)","Browser-only app","Console app"],"ans":1},
  {"q":"Cross-platform framework?","opts":["Windows Studio","React Native / Flutter / Xamarin","VS Code only","Unity only"],"ans":1},
  {"q":"Flutter uses which language?","opts":["Java","Dart","C#","JavaScript"],"ans":1},
  {"q":"React Native uses which language?","opts":["Java","JavaScript/TypeScript","Dart","C++"],"ans":1},
  {"q":"PWA stands for?","opts":["Progressive Web App","Private Web Access","Public Web Area","Project Web Analytics"],"ans":0},
  {"q":"APK stands for?","opts":["Android Package Kit","Android Personal Key","App Process Kernel","Array Process Kit"],"ans":0},
  {"q":"IPA is the file format for?","opts":["Android","iOS","Windows","Linux"],"ans":1},
  {"q":"SDK stands for?","opts":["System Design Key","Software Development Kit","Software Data Kernel","Standard Delivery Script"],"ans":1},
  {"q":"IDE for Android?","opts":["Xcode","Android Studio","Visual Studio (primary for .NET)","NotePad"],"ans":1},
  {"q":"IDE for iOS?","opts":["Android Studio","Xcode","PyCharm","Eclipse"],"ans":1},
  {"q":"Activity in Android?","opts":["A background task","A single screen with a user interface","A database connection","A file"],"ans":1},
  {"q":"Fragment in Android?","opts":["Broken code","A reusable portion of a user interface within an activity","A whole screen","A tiny bug"],"ans":1},
  {"q":"Intent in Android?","opts":["User desire","A messaging object to request an action from another component","A variable","A loop"],"ans":1},
  {"q":"Android Manifest file?","opts":["User manual","File defining essential information about app to the system","Source code","Database file"],"ans":1},
  {"q":"View in mobile dev?","opts":["The behind code","A UI component (button, text field, image)","A database query","A browser history"],"ans":1},
  {"q":"ViewGroup is?","opts":["Social network","A container for other views (Layout)","A list of users","A security group"],"ans":1},
  {"q":"Lifecycle: onCreate()?","opts":["Closing app","Called when activity is first created","Stopping app","Resuming app"],"ans":1},
  {"q":"Lifecycle: onPause()?","opts":["Starting app","Called when user leaves activity temporarily","Ending app","Creating activity"],"ans":1},
  {"q":"App permissions?","opts":["Developer name","Requests to access device features (camera, location, contacts)","App size","Version number"],"ans":1},
  {"q":"Mobile Database: SQLite?","opts":["NoSQL","Embedded relational database for local storage","Cloud DB","Text file"],"ans":1},
  {"q":"Push Notifications?","opts":["Internal logs","Messages sent from server to app even when not active","User settings","Errors"],"ans":1},
  {"q":"API Level in Android?","opts":["App version","Integer value identifying framework version (OS features)","Battery level","UI density"],"ans":1},
  {"q":"Screen Density (DPI)?","opts":["Width in pixels","Dots per inch (affects UI scaling/image crispness)","Brightness","Battery life"],"ans":1},
  {"q":"Auto Layout / Constraints?","opts":["Fixed positions","Defining UI relative to other parts (responsive layout)","Manual coordinates","Random placement"],"ans":1},
  {"q":"Emulator?","opts":["Real device","Virtual device running on computer to test apps","Physical hardware","Browser"],"ans":1},
  {"q":"Debugging in mobile?","opts":["Formatting","Finding and fixing errors using tools like Logcat or Breakpoints","Writing text","Deploying"],"ans":1},
  {"q":"Gradle?","opts":["Search engine","Build automation system used for Android","A database","A browser"],"ans":1},
  {"q":"CocoaPods?","opts":["Chocolate","Dependency manager for Swift/Objective-C projects","A browser","An OS"],"ans":1},
  {"q":"Responsive Mobile Design?","opts":["Fast design","UI that adapts to different screen sizes and orientations","Animated design","Small design"],"ans":1},
  {"q":"Touch events?","opts":["Keyboard only","Interaction via tap, swipe, pinch, long press","Mouse only","Speech only"],"ans":1},
  {"q":"Accelerometer access?","opts":["Reading text","Detecting movement and device orientation","Screen light","GPS"],"ans":1},
  {"q":"Location services use?","opts":["Only Wi-Fi","GPS, Wi-Fi, and Cell Towers to find device coordinates","Camera","Bluetooth only"],"ans":1},
  {"q":"Deep Linking?","opts":["Secret link","Linking to a specific page/content within an app","Downloading app","Deleting app"],"ans":1},
  {"q":"Jetpack Compose?","opts":["Music tool","Modern declarative UI toolkit for Android","A compiler","A database"],"ans":1},
  {"q":"SwiftUI?","opts":["Browser","Declarative UI framework for all Apple platforms","A language","A database"],"ans":1},
  {"q":"App Store Optimization (ASO)?","opts":["Speeding up app","Improving app visibility in store (search ranking)","Deleting apps","Testing logic"],"ans":1},
  {"q":"Monetization: Freemium?","opts":["Charge initially","Free app with optional paid features","Ad-only app","No cost"],"ans":1},
  {"q":"User Experience (UX)?","opts":["Graphic design","How a user feels and interacts with the app overall","Only colors","Only text"],"ans":1},
  {"q":"Interface Builder?","opts":["Code editor only","Visual tool for designing app interfaces","Database tool","Optimizer"],"ans":1},
  {"q":"WebView?","opts":["Browser app","Component to display web content inside a native app","Camera view","Gallery"],"ans":1},
  {"q":"Async Tasks?","opts":["Synchronous code","Running tasks in background to keep UI thread responsive","User inputs","Fast loops"],"ans":1},
  {"q":"Firebase?","opts":["Browser engine","Google's platform for mobile app infrastructure (Auth, DB, ML)","A virus","An OS"],"ans":1},
  {"q":"Main Thread/UI Thread?","opts":["Background downloads","The thread where all UI interactions and updates happen","Database thread","Network thread"],"ans":1}
],
}

def build_js_block(subject_key, questions):
    lines = [f'  "{subject_key}": [']
    for i, q in enumerate(questions):
        comma = "," if i < len(questions)-1 else ""
        opts = ', '.join(f'"{o}"' for o in q["opts"])
        lines.append(f'    {{')
        lines.append(f'      "question": "{q["q"]}",')
        lines.append(f'      "options": [{opts}],')
        lines.append(f'      "correctAnswer": {q["ans"]}')
        lines.append(f'    }}{comma}')
    lines.append('  ]')
    return '\n'.join(lines)

out_dir = os.path.join(os.path.dirname(__file__), '..', 'frontend', 'assets')
out_file = os.path.join(out_dir, 'quiz_sem6.js')

blocks = []
keys = list(SEM6.keys())
for i, key in enumerate(keys):
    comma = "," if i < len(keys)-1 else ""
    blocks.append(build_js_block(key, SEM6[key]) + comma)

content = 'const quizDataSem6 = {\n' + '\n'.join(blocks) + '\n};\n'
with open(out_file, 'w', encoding='utf-8') as f:
    f.write(content)

for key, qs in SEM6.items():
    assert len(qs) == 50, f"{key} has {len(qs)} questions"
    texts = [q['q'] for q in qs]
    assert len(set(texts)) == 50, f"{key} has duplicate questions"

print(f"[OK] quiz_sem6.js generated with {len(SEM6)} subjects, 50 questions each.")
