import json, os, random

SEM1 = {
"sem1-c-programming": [
  {"q":"Which symbol terminates a statement in C?","opts":[".",";",":","!"],"ans":1},
  {"q":"What does printf() do in C?","opts":["Reads input","Prints output","Allocates memory","Declares variable"],"ans":1},
  {"q":"Which loop is guaranteed to execute at least once?","opts":["for","while","do-while","switch"],"ans":2},
  {"q":"What is the index of the first element in a C array?","opts":["1","0","-1","Undefined"],"ans":1},
  {"q":"Which keyword declares a constant in C?","opts":["const","fixed","static","define"],"ans":0},
  {"q":"What does '%f' format specifier represent in C?","opts":["Integer","Float","Character","String"],"ans":1},
  {"q":"A function that calls itself is called?","opts":["Iteration","Inline","Recursion","Nested"],"ans":2},
  {"q":"Which header is needed for printf and scanf?","opts":["stdlib.h","math.h","stdio.h","string.h"],"ans":2},
  {"q":"Which data type stores a single character in C?","opts":["string","char","text","letter"],"ans":1},
  {"q":"What does scanf() do in C?","opts":["Prints output","Reads input","Declares variable","Loops"],"ans":1},
  {"q":"Which operator is used for pointer dereference in C?","opts":["&","*","->","."],"ans":1},
  {"q":"What is the size of int in C (typical 64-bit)?","opts":["2 bytes","4 bytes","8 bytes","1 byte"],"ans":1},
  {"q":"Which keyword exits a loop early in C?","opts":["exit","return","break","continue"],"ans":2},
  {"q":"What does the 'void' return type mean?","opts":["Returns 0","Returns null","Returns nothing","Returns pointer"],"ans":2},
  {"q":"How do you declare a pointer to int in C?","opts":["int p","int &p","int *p","pointer int p"],"ans":2},
  {"q":"What is a struct in C?","opts":["A function","A loop","A user-defined data type","A pointer"],"ans":2},
  {"q":"Which function frees allocated memory in C?","opts":["delete","free","release","clear"],"ans":1},
  {"q":"What does malloc() return on failure?","opts":["0","-1","NULL","false"],"ans":2},
  {"q":"Which operator gets the address of a variable in C?","opts":["*","&","->","@"],"ans":1},
  {"q":"What is the output of 7 % 3 in C?","opts":["2","1","3","0"],"ans":1},
  {"q":"Which keyword skips to the next loop iteration in C?","opts":["break","skip","next","continue"],"ans":3},
  {"q":"What is the correct way to declare a string in C?","opts":["string s","char s[]","str s","text s"],"ans":1},
  {"q":"Which function compares two strings in C?","opts":["strcmp","strcomp","compare","strequal"],"ans":0},
  {"q":"What does #include do in C?","opts":["Defines a macro","Includes a header file","Declares a function","Starts a loop"],"ans":1},
  {"q":"What is a dangling pointer?","opts":["Uninitialized pointer","Pointer to freed memory","NULL pointer","Wild pointer"],"ans":1},
  {"q":"What is the use of 'static' keyword in C?","opts":["Dynamic allocation","Persists between calls","Extern linkage","Inline function"],"ans":1},
  {"q":"Which sorting algorithm has O(n log n) average time?","opts":["Bubble Sort","Selection Sort","Quick Sort","Linear Sort"],"ans":2},
  {"q":"What does EOF stand for in C?","opts":["End of Function","End of File","Error of File","Exit of Function"],"ans":1},
  {"q":"Which format specifier is used for long int?","opts":["%d","%l","%ld","%li"],"ans":2},
  {"q":"What is the default return type of main() in C?","opts":["void","float","char","int"],"ans":3},
  {"q":"Which function copies a string in C?","opts":["strdup","strcpy","stringcopy","memcpy"],"ans":1},
  {"q":"What does a union differ from a struct in C?","opts":["Unions share memory","Structs share memory","No difference","Unions have more members"],"ans":0},
  {"q":"What is a segmentation fault?","opts":["Syntax error","Invalid memory access","Logic error","Type error"],"ans":1},
  {"q":"Which header contains math functions like sqrt()?","opts":["stdlib.h","stdio.h","math.h","string.h"],"ans":2},
  {"q":"What is the output of sizeof(char) in C?","opts":["2","4","1","8"],"ans":2},
  {"q":"How many times does a for(;;) loop run?","opts":["0","1","10","Infinite"],"ans":3},
  {"q":"Which preprocessor directive defines a macro?","opts":["#include","#macro","#define","#const"],"ans":2},
  {"q":"What does strcat() do in C?","opts":["Compares strings","Copies a string","Concatenates strings","Finds string length"],"ans":2},
  {"q":"What is the value of NULL in C?","opts":["0","-1","1","undefined"],"ans":0},
  {"q":"Which statement passes control to a labelled statement in C?","opts":["jump","skip","goto","pass"],"ans":2},
  {"q":"What is call by value in C?","opts":["Passes address","Passes copy of value","Passes reference","Passes pointer"],"ans":1},
  {"q":"Which function returns the length of a string?","opts":["len()","length()","strlen()","strlength()"],"ans":2},
  {"q":"What is the scope of a local variable?","opts":["Entire program","Current file","Current function/block","Global"],"ans":2},
  {"q":"How do you access a struct member via pointer in C?","opts":["ptr.member","ptr->member","*ptr.member","&ptr.member"],"ans":1},
  {"q":"What does realloc() do?","opts":["Frees memory","Allocates new memory","Resizes allocated memory","Copies memory"],"ans":2},
  {"q":"Which is NOT a valid C data type?","opts":["int","float","bool (C89)","string"],"ans":3},
  {"q":"What is a file pointer in C?","opts":["Pointer to int","FILE* variable","char pointer","void pointer"],"ans":1},
  {"q":"Which function opens a file in C?","opts":["openfile()","fopen()","fileopen()","open()"],"ans":1},
  {"q":"What does fclose() do in C?","opts":["Reads a file","Writes to file","Closes a file","Deletes a file"],"ans":2},
  {"q":"What is a macro in C?","opts":["A function","A variable","A preprocessor substitution","A loop"],"ans":2},
],
"sem1-chemistry": [
  {"q":"What is the atomic number of Carbon?","opts":["4","6","8","12"],"ans":1},
  {"q":"pH of a neutral solution is?","opts":["0","7","14","1"],"ans":1},
  {"q":"Which gas is released when metals react with acids?","opts":["O2","CO2","H2","N2"],"ans":2},
  {"q":"Chemical formula of water?","opts":["H2O","HO2","H2O2","OH"],"ans":0},
  {"q":"Which bond involves sharing of electrons?","opts":["Ionic","Covalent","Metallic","Hydrogen"],"ans":1},
  {"q":"Avogadro's number is approximately?","opts":["6.022×10²³","3.14×10¹⁰","1.6×10⁻¹⁹","9.8×10¹⁰"],"ans":0},
  {"q":"Combustion is an example of which type of reaction?","opts":["Endothermic","Neutralization","Exothermic","Reduction"],"ans":2},
  {"q":"Most abundant element in Earth's crust?","opts":["Iron","Silicon","Oxygen","Aluminum"],"ans":2},
  {"q":"Molar mass of NaCl?","opts":["40 g/mol","58.5 g/mol","74 g/mol","36 g/mol"],"ans":1},
  {"q":"Which is a noble gas?","opts":["Nitrogen","Chlorine","Fluorine","Argon"],"ans":3},
  {"q":"What is the valency of Oxygen?","opts":["1","2","3","4"],"ans":1},
  {"q":"Which law states mass is conserved in reactions?","opts":["Dalton's Law","Boyle's Law","Conservation of Mass","Gay-Lussac's Law"],"ans":2},
  {"q":"Chemical symbol of Gold?","opts":["Go","Gd","Au","Ag"],"ans":2},
  {"q":"Which acid is present in vinegar?","opts":["Citric acid","Acetic acid","Hydrochloric acid","Sulphuric acid"],"ans":1},
  {"q":"Which gas causes global warming?","opts":["O2","N2","CO2","H2"],"ans":2},
  {"q":"Atomic number of Hydrogen?","opts":["1","2","0","3"],"ans":0},
  {"q":"Which element has symbol Fe?","opts":["Fluorine","Fermium","Iron","Francium"],"ans":2},
  {"q":"What is an isotope?","opts":["Same protons, different neutrons","Same neutrons different protons","Same mass number","Different elements"],"ans":0},
  {"q":"Which type of bond forms between Na+ and Cl-?","opts":["Covalent","Metallic","Ionic","Hydrogen"],"ans":2},
  {"q":"Boiling point of water at standard pressure?","opts":["90°C","100°C","110°C","80°C"],"ans":1},
  {"q":"Which gas is used in fire extinguishers?","opts":["O2","N2","CO2","H2"],"ans":2},
  {"q":"What is oxidation?","opts":["Gain of electrons","Loss of electrons","Gain of protons","Loss of protons"],"ans":1},
  {"q":"Which acid is found in the human stomach?","opts":["H2SO4","HNO3","HCl","CH3COOH"],"ans":2},
  {"q":"What is a base?","opts":["Proton donor","Proton acceptor","Salt former","Electron giver"],"ans":1},
  {"q":"Chemical symbol for table salt?","opts":["NaCl","KCl","CaCl2","MgCl2"],"ans":0},
  {"q":"What is the charge of an electron?","opts":["+1","-1","0","0.5"],"ans":1},
  {"q":"Atoms of the same element are called?","opts":["Molecules","Compounds","Isotopes","Allotropes"],"ans":2},
  {"q":"What is sublimation?","opts":["Solid to liquid","Liquid to gas","Solid to gas directly","Gas to solid"],"ans":2},
  {"q":"Which property separates mixtures by boiling points?","opts":["Filtration","Distillation","Crystallization","Evaporation"],"ans":1},
  {"q":"The number of electrons in a neutral atom equals?","opts":["Number of neutrons","Number of protons","Mass number","Atomic weight"],"ans":1},
  {"q":"What is an exothermic reaction?","opts":["Absorbs heat","Releases heat","No heat change","Uses electricity"],"ans":1},
  {"q":"Symbol for Sodium?","opts":["So","Sd","Na","N"],"ans":2},
  {"q":"What is a catalyst?","opts":["Consumed in reaction","Speeds up reaction without being consumed","Slows reaction","Ends reaction"],"ans":1},
  {"q":"Molecular formula of Carbon Dioxide?","opts":["CO","CO2","C2O","CO3"],"ans":1},
  {"q":"Which gas makes up most of Earth's atmosphere?","opts":["Oxygen","Carbon Dioxide","Nitrogen","Argon"],"ans":2},
  {"q":"What is reduction?","opts":["Loss of electrons","Gain of electrons","Loss of protons","Gain of protons"],"ans":1},
  {"q":"Period number in periodic table indicates?","opts":["Number of protons","Number of neutrons","Number of electron shells","Group number"],"ans":2},
  {"q":"Which state of matter has definite volume but no definite shape?","opts":["Solid","Gas","Plasma","Liquid"],"ans":3},
  {"q":"What is the SI unit of amount of substance?","opts":["Gram","Kilogram","Mole","Liter"],"ans":2},
  {"q":"Chemical formula for Ammonia?","opts":["NO3","NH3","N2O","NO2"],"ans":1},
  {"q":"Which element is liquid at room temperature (non-metal)?","opts":["Mercury","Bromine","Gallium","Cesium"],"ans":1},
  {"q":"What is an alloy?","opts":["Pure metal","Mixture of metals","Compound of metals","Metal ore"],"ans":1},
  {"q":"The process of rust formation is called?","opts":["Combustion","Corrosion","Reduction","Sublimation"],"ans":1},
  {"q":"Which vitamin is produced by sunlight on skin?","opts":["Vitamin A","Vitamin B","Vitamin C","Vitamin D"],"ans":3},
  {"q":"Atomic mass of Oxygen?","opts":["14","16","18","12"],"ans":1},
  {"q":"What is electrolysis?","opts":["Chemical decomposition by heat","Chemical decomposition by electricity","Physical separation","Magnetic separation"],"ans":1},
  {"q":"Radioactive decay emits which types of radiation?","opts":["X-rays only","Alpha, Beta, Gamma","UV and IR","Microwaves"],"ans":1},
  {"q":"What is a saturated solution?","opts":["No solute dissolved","Maximum solute dissolved","Less solute dissolved","Heated solution"],"ans":1},
  {"q":"Chemical formula for Glucose?","opts":["C6H12O6","C12H22O11","CH2O","C6H6"],"ans":0},
  {"q":"What is meant by 'mole' in chemistry?","opts":["A unit of mass","6.022×10²³ particles","A unit of volume","A unit of pressure"],"ans":1},
],
"sem1-english": [
  {"q":"Which part of speech describes a noun?","opts":["Verb","Adjective","Adverb","Preposition"],"ans":1},
  {"q":"What is a synonym of 'happy'?","opts":["Sad","Joyful","Angry","Tired"],"ans":1},
  {"q":"What is a simile?","opts":["Direct comparison","Comparison using like or as","Exaggeration","Contradiction"],"ans":1},
  {"q":"Correct plural of 'child'?","opts":["Childs","Childrens","Children","Child's"],"ans":2},
  {"q":"Which tense: 'She was reading a book'?","opts":["Simple past","Past continuous","Past perfect","Present perfect"],"ans":1},
  {"q":"An antonym of 'beautiful' is?","opts":["Pretty","Attractive","Ugly","Graceful"],"ans":2},
  {"q":"What is the subject in: 'The dog barked loudly'?","opts":["dog","barked","loudly","The"],"ans":0},
  {"q":"Which punctuation ends a question?","opts":["!",".","?",";"],"ans":2},
  {"q":"What is a metaphor?","opts":["Comparison using like/as","Direct comparison without like/as","An exaggeration","A rhyme"],"ans":1},
  {"q":"'Quickly' is an example of?","opts":["Adjective","Noun","Adverb","Verb"],"ans":2},
  {"q":"Correct spelling?","opts":["Accomodate","Accommodate","Acommodate","Acomodate"],"ans":1},
  {"q":"What is the passive voice of 'She ate the cake'?","opts":["The cake was eaten by her","She is eating the cake","The cake is eaten","Cake she ate"],"ans":0},
  {"q":"What is a clause?","opts":["A single word","A group of words with subject and verb","A punctuation mark","A type of sentence"],"ans":1},
  {"q":"Which is a compound sentence?","opts":["She ran.","She ran and he walked.","Although she ran.","Running fast."],"ans":1},
  {"q":"What does 'verbose' mean?","opts":["Concise","Using too many words","Silent","Accurate"],"ans":1},
  {"q":"'Flock' is a collective noun for?","opts":["Dogs","Fish","Birds","Cats"],"ans":2},
  {"q":"What is a pronoun?","opts":["Names a place","Replaces a noun","Describes a noun","Shows action"],"ans":1},
  {"q":"Which word is a conjunction?","opts":["Run","Slowly","And","Blue"],"ans":2},
  {"q":"'The sun rose slowly.' What is 'slowly'?","opts":["Adjective","Preposition","Adverb","Noun"],"ans":2},
  {"q":"Identify the correct sentence:","opts":["He don't know.","He doesn't knows.","He doesn't know.","He do not knows."],"ans":2},
  {"q":"Antonym of 'ancient'?","opts":["Old","Modern","Historical","Aged"],"ans":1},
  {"q":"A word that imitates a sound is called?","opts":["Metaphor","Alliteration","Onomatopoeia","Simile"],"ans":2},
  {"q":"Which is a proper noun?","opts":["city","river","London","mountain"],"ans":2},
  {"q":"What is alliteration?","opts":["Rhyming words","Repetition of initial consonant sounds","Comparison","Exaggeration"],"ans":1},
  {"q":"'I have eaten' is in which tense?","opts":["Simple past","Present perfect","Past perfect","Future perfect"],"ans":1},
  {"q":"What is a preposition?","opts":["Shows action","Describes noun","Shows relationship between nouns","Replaces noun"],"ans":2},
  {"q":"Synonym of 'begin'?","opts":["End","Finish","Start","Stop"],"ans":2},
  {"q":"What does 'ambiguous' mean?","opts":["Clear","Having more than one meaning","False","Correct"],"ans":1},
  {"q":"Which is an abstract noun?","opts":["Table","Book","Freedom","Dog"],"ans":2},
  {"q":"'Unless you study, you will fail.' This is a:","opts":["Simple sentence","Compound sentence","Complex sentence","Fragment"],"ans":2},
  {"q":"What is the gerund in: 'Swimming is fun'?","opts":["is","fun","Swimming","None"],"ans":0},
  {"q":"Which sentence uses the Oxford comma?","opts":["I like cats, dogs and birds.","I like cats, dogs, and birds.","I like cats dogs and birds.","I like: cats, dogs, birds."],"ans":1},
  {"q":"What does 'infer' mean?","opts":["State directly","Conclude from evidence","Document facts","Question"],"ans":1},
  {"q":"Which word is an interjection?","opts":["Run","Hello!","Blue","Quickly"],"ans":1},
  {"q":"'She is taller than him.' This uses?","opts":["Superlative","Positive degree","Comparative degree","Absolute degree"],"ans":2},
  {"q":"What is a paragraph?","opts":["A single sentence","A group of related sentences","A chapter","A word"],"ans":1},
  {"q":"What is the tone of a piece of writing?","opts":["The plot","The author's attitude","The setting","The characters"],"ans":1},
  {"q":"'It was raining cats and dogs.' This is a?","opts":["Simile","Metaphor","Idiom","Alliteration"],"ans":2},
  {"q":"What is a thesis statement?","opts":["Concluding remark","Main argument of an essay","An example","A hook"],"ans":1},
  {"q":"'The sun smiled down on us.' This is?","opts":["Simile","Personification","Metaphor","Hyperbole"],"ans":1},
  {"q":"Correct form: 'Each of the students ___ present.'","opts":["are","were","is","have been"],"ans":2},
  {"q":"Which word means 'feeling sad for someone'?","opts":["Antipathy","Sympathy","Apathy","Empathy"],"ans":1},
  {"q":"A word opposite in meaning is called?","opts":["Synonym","Homonym","Antonym","Hypernym"],"ans":2},
  {"q":"Which is a linking verb?","opts":["Run","Jump","Is","Write"],"ans":2},
  {"q":"What does 'context' mean?","opts":["A type of sentence","Surrounding information giving meaning","A character","A setting"],"ans":1},
  {"q":"'Very' is what kind of modifier?","opts":["Adjective","Adverb","Noun","Verb"],"ans":1},
  {"q":"What is a bibliography?","opts":["Table of contents","List of sources used","Summary","Index"],"ans":1},
  {"q":"Which sentence is in future tense?","opts":["She ran.","She runs.","She will run.","She has run."],"ans":2},
  {"q":"A statement that contradicts itself is called?","opts":["Irony","Paradox","Hyperbole","Euphemism"],"ans":1},
  {"q":"What is the objective case of 'I'?","opts":["My","Mine","Me","Myself"],"ans":2},
],
"sem1-linear-algebra": [
  {"q":"What is the determinant of a 2×2 identity matrix?","opts":["0","2","1","-1"],"ans":2},
  {"q":"Which operation is NOT defined for matrices of different dimensions?","opts":["Scalar multiply","Matrix addition","Transpose","Matrix multiply (same cols/rows)"],"ans":1},
  {"q":"The transpose of a matrix A is denoted by?","opts":["A⁻¹","Aᵀ","A*","A|"],"ans":1},
  {"q":"A square matrix equal to its transpose is called?","opts":["Identity","Skew-symmetric","Symmetric","Orthogonal"],"ans":2},
  {"q":"The rank of a matrix is?","opts":["Number of rows","Number of columns","Max number of linearly independent rows","Determinant value"],"ans":2},
  {"q":"For a matrix to have an inverse, its determinant must be?","opts":["0","1","Non-zero","Negative"],"ans":2},
  {"q":"Which of these is a scalar?","opts":["A 1×3 matrix","A 3×1 vector","A single number","A 2×2 matrix"],"ans":2},
  {"q":"The dot product of two perpendicular vectors is?","opts":["1","-1","0","Undefined"],"ans":2},
  {"q":"Eigenvalues satisfy which equation?","opts":["Ax = b","det(A - λI) = 0","AᵀA = I","AA⁻¹ = 0"],"ans":1},
  {"q":"The trace of a matrix is?","opts":["Sum of all elements","Product of diagonal","Sum of diagonal elements","Determinant"],"ans":2},
  {"q":"A vector space must be closed under?","opts":["Multiplication only","Addition and scalar multiplication","Division","Subtraction only"],"ans":1},
  {"q":"What is a null vector?","opts":["A vector of length 1","A vector with all zero components","A unit vector","An orthogonal vector"],"ans":1},
  {"q":"Two vectors are linearly dependent if?","opts":["Their dot product is 0","One is a scalar multiple of the other","They are perpendicular","Their sum is zero"],"ans":1},
  {"q":"The inverse of a 2×2 matrix [a,b;c,d] divided by det is?","opts":["[a,b;c,d]","[d,-b;-c,a]","[-a,b;c,-d]","[d,c;b,a]"],"ans":1},
  {"q":"Which matrix has 1s on diagonal and 0s elsewhere?","opts":["Zero matrix","Diagonal matrix","Identity matrix","Symmetric matrix"],"ans":2},
  {"q":"The column space of a matrix is spanned by?","opts":["Row vectors","Column vectors","Null vectors","Eigen vectors"],"ans":1},
  {"q":"What does RREF stand for?","opts":["Reduced Row Echelon Form","Row and Column Form","Reduced Right Edge Form","Regular Row Expansion Form"],"ans":0},
  {"q":"A matrix A is idempotent if?","opts":["A²=I","A²=A","A=Aᵀ","A⁻¹=Aᵀ"],"ans":1},
  {"q":"The norm of vector [3,4] is?","opts":["7","1","5","12"],"ans":2},
  {"q":"Gaussian elimination is used to solve?","opts":["Eigenvalue problems","Linear systems Ax=b","Differential equations","Integration"],"ans":1},
  {"q":"A matrix with determinant 0 is called?","opts":["Identity","Invertible","Singular","Orthogonal"],"ans":2},
  {"q":"The cross product of two vectors results in?","opts":["A scalar","A vector perpendicular to both","A matrix","A unit vector"],"ans":1},
  {"q":"Which property: A(BC) = (AB)C?","opts":["Commutative","Distributive","Associative","Identity"],"ans":2},
  {"q":"An orthogonal matrix satisfies?","opts":["A=Aᵀ","AᵀA=I","A²=A","det(A)=0"],"ans":1},
  {"q":"What is a basis of a vector space?","opts":["Any set of vectors","Linearly independent spanning set","Orthogonal vectors only","Eigen vectors"],"ans":1},
  {"q":"The dimension of a vector space is?","opts":["Number of vectors","Number of basis vectors","Rank of any matrix","Number of equations"],"ans":1},
  {"q":"What is a linear transformation?","opts":["Any function on vectors","Function preserving addition and scalar mult.","Rotation only","Matrix multiplication"],"ans":1},
  {"q":"Cramer's Rule is used to solve?","opts":["Eigenvalue problems","Systems of linear equations","Matrix inversion","Vector projections"],"ans":1},
  {"q":"The span of a set of vectors is?","opts":["Their dot product","All linear combinations","Their cross product","Their sum"],"ans":1},
  {"q":"An upper triangular matrix has zeros?","opts":["Above diagonal","On diagonal","Below diagonal","Everywhere except diagonal"],"ans":2},
  {"q":"What is a pivot in row reduction?","opts":["Zero element","First non-zero element in a row","Largest element","Diagonal element"],"ans":1},
  {"q":"det(AB) equals?","opts":["det(A)+det(B)","det(A)×det(B)","det(A)-det(B)","det(A)/det(B)"],"ans":1},
  {"q":"Which matrix operation is generally NOT commutative?","opts":["Scalar multiply","Transpose","Matrix addition","Matrix multiplication"],"ans":3},
  {"q":"What is the kernel of a linear transformation?","opts":["Image space","Set mapped to zero vector","Basis of domain","Orthogonal complement"],"ans":1},
  {"q":"The eigenvector of a matrix satisfies?","opts":["Av=0","Av=λv","Av=v","AvᵀA=I"],"ans":1},
  {"q":"How many solutions does Ax=b have if rank(A)<rank([A|b])?","opts":["One","Infinitely many","None","Two"],"ans":2},
  {"q":"A positive definite matrix has eigenvalues that are all?","opts":["Negative","Zero","Positive","Complex"],"ans":2},
  {"q":"The LU decomposition factorizes A into?","opts":["Lower and upper triangular matrices","Left and unit matrices","Least and upper bounds","Linear and uniform matrices"],"ans":0},
  {"q":"What is the adjoint of a matrix?","opts":["Transpose of cofactor matrix","Inverse matrix","Diagonal matrix","Identity matrix"],"ans":0},
  {"q":"If det(A)=0, which is true?","opts":["A is invertible","Ax=b has unique solution","Rows are linearly dependent","A is orthogonal"],"ans":2},
  {"q":"The projection of vector a onto vector b is?","opts":["a·b","(a·b/|b|²)b","|a||b|","a×b"],"ans":1},
  {"q":"Gram-Schmidt process produces?","opts":["Eigenvalues","Orthonormal basis","Matrix inverse","Row echelon form"],"ans":1},
  {"q":"Cayley-Hamilton theorem states?","opts":["A matrix satisfies its own characteristic equation","Every matrix is diagonalizable","det(A)=trace(A)","Eigenvalues are real"],"ans":0},
  {"q":"A diagonal matrix has non-zero entries only?","opts":["In first row","On main diagonal","In last column","In corners"],"ans":1},
  {"q":"The rank-nullity theorem states rank(A)+nullity(A)=?","opts":["Number of rows","Number of columns","det(A)","trace(A)"],"ans":1},
  {"q":"Which decomposition is used for least squares?","opts":["LU","QR","SVD","Cholesky"],"ans":1},
  {"q":"An n×n matrix has at most how many distinct eigenvalues?","opts":["1","n-1","n","2n"],"ans":2},
  {"q":"The characteristic polynomial of A is?","opts":["det(A-λI)","trace(A-λI)","det(A)+λ","A-λI"],"ans":0},
  {"q":"Two matrices are similar if?","opts":["They have same size","A=PBP⁻¹ for invertible P","They have same determinant","They are both symmetric"],"ans":1},
  {"q":"The minimal polynomial of a matrix divides?","opts":["The trace","The characteristic polynomial","The determinant","The rank"],"ans":1},
],
}

def build_js_block(subject_key, questions):
    lines = [f'  "{subject_key}": [']
    for i, q in enumerate(questions):
        comma = "," if i < len(questions)-1 else ""
        opts = ', '.join(f'"{o}"' for o in q["opts"])
        lines.append(f'    {{')
        lines.append(f'      "question": "{q["q"]}",')
        lines.append(f'      "options": [{opts}],')
        lines.append(f'      "correctAnswer": {q["ans"]}')
        lines.append(f'    }}{comma}')
    lines.append('  ]')
    return '\n'.join(lines)

out_dir = os.path.join(os.path.dirname(__file__), '..', 'frontend', 'assets')
out_file = os.path.join(out_dir, 'quiz_sem1.js')

blocks = []
keys = list(SEM1.keys())
for i, key in enumerate(keys):
    comma = "," if i < len(keys)-1 else ""
    blocks.append(build_js_block(key, SEM1[key]) + comma)

content = 'const quizDataSem1 = {\n' + '\n'.join(blocks) + '\n};\n'
with open(out_file, 'w', encoding='utf-8') as f:
    f.write(content)

# verify
for key, qs in SEM1.items():
    assert len(qs) == 50, f"{key} has {len(qs)} questions"
    texts = [q['q'] for q in qs]
    assert len(set(texts)) == 50, f"{key} has duplicate questions"

print(f"[OK] quiz_sem1.js generated with {len(SEM1)} subjects, 50 questions each.")
