import os

SEM7 = {
"sem7-dwm": [
  {"q":"DWM stands for?","opts":["Data Warehousing and Mining","Digital Web Management","Data World Model","Dynamic Web Mining"],"ans":0},
  {"q":"A Data Warehouse is?","opts":["Transactional DB","Subject-oriented, integrated, time-variant, non-volatile collection of data","Only for text files","A local cache"],"ans":1},
  {"q":"OLTP refers to?","opts":["Day-to-day transaction processing","Analytical processing","Data mining","Reporting only"],"ans":0},
  {"q":"OLAP refers to?","opts":["Transaction processing","Complex analysis and multi-dimensional reporting","Data entry","Sorting data"],"ans":1},
  {"q":"Data Mining is?","opts":["Storing data","Extracting hidden patterns/knowledge from large datasets","Deleting data","Backing up data"],"ans":1},
  {"q":"KDD stands for?","opts":["Knowledge Discovery in Databases","Key Data Distribution","Kernel Data Design","Knowledge Delivery Dictionary"],"ans":0},
  {"q":"The first step in KDD process is?","opts":["Cleaning","Selection","Data Integration","Preprocessing"],"ans":1},
  {"q":"ETL in DWM?","opts":["Extract, Transform, Load","Entries for Logic","Every Text Link","Electronic Test Loop"],"ans":0},
  {"q":"Data Cleaning removes?","opts":["All data","Noise and inconsistent data","Important records","Formatting"],"ans":1},
  {"q":"Data Integration combines?","opts":["Two files","Multiple heterogeneous data sources","Logical bits","Hardware ports"],"ans":1},
  {"q":"Data Cube is used in?","opts":["3D graphics","Multi-dimensional data modeling in OLAP","Binary trees","Linear arrays"],"ans":1},
  {"q":"Star Schema?","opts":["A circle","Central fact table connected to multiple dimension tables","Linear list","Chain of tables"],"ans":1},
  {"q":"Snowflake Schema?","opts":["Star with normalized dimension tables","A flat file","A visual diagram","No dimensions"],"ans":0},
  {"q":"Fact Table contains?","opts":["Descriptive text","Quantitative measures (metrics) and foreign keys","Only labels","Usernames"],"ans":1},
  {"q":"Dimension Table contains?","opts":["Numbers only","Descriptive attributes about the facts","Keys only","No data"],"ans":1},
  {"q":"MOLAP?","opts":["Multi-dimensional OLAP (uses cubes)","Memory OLAP","Master OLAP","Manual OLAP"],"ans":0},
  {"q":"ROLAP?","opts":["Relational OLAP (uses RDBMS tables)","Random OLAP","Remote OLAP","Runtime OLAP"],"ans":0},
  {"q":"Data Mart is?","opts":["A large warehouse","A department-specific subset of a data warehouse","A shopping site","A local disk"],"ans":1},
  {"q":"Metadata in DWM?","opts":["Actual data","Data about data (schema, mapping, etc.)","Encrypted data","Lost data"],"ans":1},
  {"q":"Association Rule Mining?","opts":["Sorting rules","Finding frequent patterns and relationships (e.g. Market Basket Analysis)","Deleting rules","Logic check"],"ans":1},
  {"q":"Apriori Algorithm?","opts":["Sorting","Finding frequent itemsets in association rules","Searching","Clustering"],"ans":1},
  {"q":"Clustering is?","opts":["Predicting labels","Grouping similar data points together (unsupervised)","Sorting numerically","Regression"],"ans":1},
  {"q":"K-Means algorithm?","opts":["Classification","Popular centroid-based clustering algorithm","Linear search","Hashing"],"ans":1},
  {"q":"Classification is?","opts":["Grouping points","Predicting discrete labels/categories (supervised)","Adding numbers","Formatting text"],"ans":1},
  {"q":"Decision Tree Induction?","opts":["Clustering","Building a flowchart-like tree for classification","Linear regression","Sorting lists"],"ans":1},
  {"q":"Regression?","opts":["Predicting categories","Predicting continuous numerical values","Grouping items","Deleting files"],"ans":1},
  {"q":"Outlier Analysis?","opts":["Finding average","Identifying data points that significantly deviate from the norm","Finding max","Finding min"],"ans":1},
  {"q":"Data Transformation?","opts":["Deleting data","Converting data into appropriate formats for mining (scaling, encoding)","Formatting drive","Printing data"],"ans":1},
  {"q":"Smoothing?","opts":["Adding noise","Removing noise from data using algorithms like binning or regression","Increasing complexity","Scaling"],"ans":1},
  {"q":"Normalization (Min-Max)?","opts":["Scaling data to [0,1] range","Setting mean to 0","Deleting data","Printing data"],"ans":0},
  {"q":"Granularity?","opts":["Color of data","Level of detail in data (e.g. daily vs monthly)","Data type","File size"],"ans":1},
  {"q":"Slice and Dice?","opts":["Cooking term","OLAP operations to view specific portions of a cube","Sorting rows","Deleting tables"],"ans":1},
  {"q":"Roll-up?","opts":["Breaking down data","Summarizing data by moving up the hierarchy (coarser)","Filing data","Saving data"],"ans":1},
  {"q":"Drill-down?","opts":["Summarizing","Navigating from less detailed to more detailed data","Searching","Deleting data"],"ans":1},
  {"q":"Data Cube aggregate?","opts":["Summing rows","Precomputed summaries across all dimensions","Saving files","One value"],"ans":1},
  {"q":"Concept Hierarchy?","opts":["File tree","Mapping low-level concepts to higher-level ones (City -> State -> Country)","Logic gates","Database index"],"ans":1},
  {"q":"Market Basket Analysis?","opts":["Buying groceries","Finding what products are frequently bought together","Inventory count","Price check"],"ans":1},
  {"q":"Confidence in association rules?","opts":["Total count","Frequency of item Y given item X","Sum of items","Probability of X"],"ans":1},
  {"q":"Lift in association rules?","opts":["Physical lift","Measure of the strength of an association rule","Height of data","Number of items"],"ans":1},
  {"q":"Neural Networks in Data Mining?","opts":["For simple math","Used for complex classification and prediction patterns","For sorting","For lexing"],"ans":1},
  {"q":"Bayesian Classification?","opts":["Logic only","Statistical classification based on Bayes' Theorem","Search only","Random choice"],"ans":1},
  {"q":"Hierarchical Clustering?","opts":["One-step clustering","Building a tree-like hierarchy of clusters (Dendrogram)","Binary search","Hashing"],"ans":1},
  {"q":"DBSCAN?","opts":["Centroid clustering","Density-based clustering algorithm","Linear search","Parsing"],"ans":1},
  {"q":"Data Reduction?","opts":["Deleting important info","Obtaining a reduced representation of data that produces same/similar results","Small files","Lossless compression"],"ans":1},
  {"q":"Feature Selection?","opts":["Picking all data","Selecting a subset of relevant features for model building","Picking random data","Deleting columns"],"ans":1},
  {"q":"Discretization?","opts":["Adding decimals","Reducing number of values of a continuous attribute by grouping into intervals","Scaling","Rounding"],"ans":1},
  {"q":"Temporal Data Mining?","opts":["Searching files","Extracting info from time-varying data","Sorting by name","Encryption"],"ans":1},
  {"q":"Web Content Mining?","opts":["Surfing web","Extracting info from the text/images of web pages","Ranking search results","Deleting sites"],"ans":1},
  {"q":"Enterprise Data Warehouse (EDW)?","opts":["Single DB","Unified, central database containing all business info for an organization","Large HDD","Cloud drive"],"ans":1},
  {"q":"Big Data vs Data Warehouse?","opts":["They are same","DW (structured/historical); Big Data (unstructured/distributed/real-time)","DW is bigger","Big Data is older"],"ans":1}
],
"sem7-nlp": [
  {"q":"NLP stands for?","opts":["Natural Language Processing","Neural Logic Process","Network Link Protocol","Natural Level Print"],"ans":0},
  {"q":"NLP is a field of?","opts":["Physics","Artificial Intelligence and Linguistics","Chemistry","Hardware Engineeering"],"ans":1},
  {"q":"Tokenization?","opts":["Adding coins","Breaking text into individual words or sentences (tokens)","Encryption","Grammar check"],"ans":1},
  {"q":"Stop Words?","opts":["Important keywords","Commonly used words (the, is, in) often removed in preprocessing","Spelling errors","Final words"],"ans":1},
  {"q":"Stemming?","opts":["Adding prefix","Reducing a word to its root/base form (often crude)","Spelling check","Logic check"],"ans":1},
  {"q":"Lemmatization?","opts":["Crude root finding","Reducing word to its lemma (dictionary base) using morphological analysis","Encryption","Sorting"],"ans":1},
  {"q":"POS Tagging?","opts":["Mailing text","Assigning parts of speech (noun, verb, etc.) to each token","Emailing","Saving"],"ans":1},
  {"q":"Named Entity Recognition (NER)?","opts":["Finding text","Identifying and classifying entities (People, Orgs, Locations) in text","Deleting names","Encryption"],"ans":1},
  {"q":"Sentiment Analysis?","opts":["Speed test","Identifying emotional tone or opinion from text (Positive/Negative)","Grammar check","Word count"],"ans":1},
  {"q":"N-gram?","opts":["A weight","Contiguous sequence of N items (words/chars) from a text","Number line","Grammar unit"],"ans":1},
  {"q":"Corpus?","opts":["Dead body","A large collection of text used for linguistic analysis/training","A rule","A dictionary"],"ans":1},
  {"q":"Syntax vs Semantics?","opts":["They are same","Syntax (grammar); Semantics (meaning)","Syntax is logic","Semantics is rules"],"ans":1},
  {"q":"Dependency Parsing?","opts":["Word order","Analyzing the grammatical structure based on relationships between words","Clustering","Lexing"],"ans":1},
  {"q":"Word Embeddings?","opts":["Fonts","Vector representations of words capturing semantic meaning (Word2Vec, GloVe)","Image storage","ASCII codes"],"ans":1},
  {"q":"Word2Vec goal?","opts":["Mapping words to one-hot","Mapping words to dense vectors in low-dimensional space","Encryption","Sorting"],"ans":1},
  {"q":"TF-IDF stands for?","opts":["Term Frequency - Inverse Document Frequency","Text File - Image Data Format","Total Frequency - Internal Data","Terminal File - Inclusion Design"],"ans":0},
  {"q":"TF-IDF measures?","opts":["Word count","Importance of a word in a document relative to a corpus","Writing speed","File size"],"ans":1},
  {"q":"Bag of Words (BoW)?","opts":["Linguistic study","Simple representation of text as a multiset of its words (ignoring grammar/order)","Encryption","Sorted list"],"ans":1},
  {"q":"Language Model?","opts":["A translator","A system that assigns probabilities to sequences of words","A dictionary","A textbook"],"ans":1},
  {"q":"Perplexity?","opts":["Commonness","Measure of how well a probability model predicts a sample (lower is better)","Complexity","Speed"],"ans":1},
  {"q":"Hidden Markov Models (HMM)?","opts":["Logic gates","Statistical models used for sequence labeling like POS tagging","Neural nets","Search trees"],"ans":1},
  {"q":"RNNs in NLP?","opts":["For images","Good for processing sequential data like text","For sorting","For hardware"],"ans":1},
  {"q":"Vanishing Gradient in RNNs?","opts":["Gradients grow","Gradients become too small during long sequence backprop","No error","Fast training"],"ans":1},
  {"q":"Attention Mechanism?","opts":["Looking at all words","Allowing model to focus on relevant words regardless of distance","Deleting words","Scanning"],"ans":1},
  {"q":"Transformer?","opts":["Movie robot","Neural network architecture based on self-attention, replacing RNNs in NLP","A physical generator","A database"],"ans":1},
  {"q":"BERT?","opts":["Simple lexer","Bidirectional Encoder Representations from Transformers","A CNN","Search logic"],"ans":1},
  {"q":"GPT (Generative Pre-trained Transformer)?","opts":["Image generator","Autoregressive model designed for text generation","A file format","A protocol"],"ans":1},
  {"q":"Machine Translation?","opts":["Reading text","Task of automatically translating text from one language to another","Parsing code","Spelling correction"],"ans":1},
  {"q":"Summarization (Abstractive)?","opts":["Copying sentences","Generating new concise text capturing main points","Deleting words","Reordering rows"],"ans":1},
  {"q":"Summarization (Extractive)?","opts":["Re-writing","Selecting specific existing sentences from text to create summary","Writing new text","Deleting vowels"],"ans":1},
  {"q":"Chatbot?","opts":["A physical bot","Software that simulates human conversation via text or voice","A database","A browser"],"ans":1},
  {"q":"Question Answering (QA)?","opts":["User interview","System that provides answers to natural language questions","Database query only","Math solver"],"ans":1},
  {"q":"Morphological Analysis?","opts":["Color study","Study of the structure and formation of words","Grammar only","Logic"],"ans":1},
  {"q":"Parsing?","opts":["Scanning characters","Determining the syntactic structure of a sentence","Sorting","Encrypting"],"ans":1},
  {"q":"Lexical Ambiguity?","opts":["One word, one meaning","One word having multiple meanings (e.g. 'bank')","Grammar error","Spelling error"],"ans":1},
  {"q":"Word Sense Disambiguation (WSD)?","opts":["Finding errors","Identifying which meaning of a word is used in context","Deleting words","Merging words"],"ans":1},
  {"q":"Coreference Resolution?","opts":["Finding nouns","Identifying which expressions refer to the same entity (e.g. 'He' -> 'John')","Sorting names","Encryption"],"ans":1},
  {"q":"Discourse Analysis?","opts":["Word study","Analyzing the relationships between sentences and larger text structure","Sentence count","Logic check"],"ans":1},
  {"q":"BLEU Score?","opts":["Word count","Metric for evaluating quality of machine-translated text","Success rate","Encryption strength"],"ans":1},
  {"q":"Speech Recognition (ASR)?","opts":["Speaking to people","Converting spoken language to text","Text to speech","Translation"],"ans":1},
  {"q":"Tokenization problem?","opts":["Spelling","Handling contractions, punctuation, and multi-word expressions","Word count","Fonts"],"ans":1},
  {"q":"Parsing: CKY Algorithm?","opts":["Search engine","Bottom-up parsing algorithm for CFG in Chomsky Normal Form","Fast sort","Hashing"],"ans":1},
  {"q":"Knowledge Graph?","opts":["A chart","Network of real-world entities and their relationships","File system","B-Tree"],"ans":1},
  {"q":"One-hot Encoding drawbacks?","opts":["Too small","Sparse, high-dimensional, no semantic meaning","Too many numbers","Fast"],"ans":1},
  {"q":"Cosine Similarity?","opts":["Length difference","Measure of similarity between two vectors based on angle (useful for word vectors)","Sum of values","Average"],"ans":1},
  {"q":"ELMo stands for?","opts":["Linguistic Model","Embeddings from Language Models","Extra Logic Module","Electronic Model"],"ans":1},
  {"q":"Zero-shot learning?","opts":["Learning from 10 examples","Model performing a task without any specific training examples","No learning","Random prediction"],"ans":1},
  {"q":"Few-shot learning?","opts":["Learning with no data","Learning from a small number of examples","Massive data learning","No training"],"ans":1},
  {"q":"Fine-tuning in NLP?","opts":["Setting weights to 0","Adapting pre-trained model to specific task with domain data","Deleting layers","Writing scripts"],"ans":1},
  {"q":"The goal of NLP is to?","opts":["Bridge the gap between human communication and computer understanding","Build better CPUs","Replace humans","Speed up typing"],"ans":0}
],
"sem7-bc": [
  {"q":"Blockchain is?","opts":["A central database","Distributed, decentralized ledger that records transactions across many computers","A local file","A payment app"],"ans":1},
  {"q":"The first blockchain was for?","opts":["Ethereum","Bitcoin","Hyperledger","Facebook"],"ans":1},
  {"q":"Who developed the first blockchain?","opts":["Bill Gates","Satoshi Nakamoto","Vitalik Buterin","Mark Zuckerberg"],"ans":1},
  {"q":"Decentralization means?","opts":["One authority","No single point of control or failure","High speed","Many authority centers"],"ans":1},
  {"q":"A 'Block' in blockchain contains?","opts":["Only text","List of transactions, timestamp, and hash of previous block","Usernames only","Passwords"],"ans":1},
  {"q":"Cryptography in BC is used for?","opts":["Speed","Security, privacy, and integrity of transactions","Data size reduction","Visual effects"],"ans":1},
  {"q":"Hashing in BC ensures?","opts":["Speed","Immutability (changing data changes the hash)","Privacy","Storage"],"ans":1},
  {"q":"Immutability?","opts":["Easy to change","Data cannot be modified once written without consensus","Deleting data","Fast updates"],"ans":1},
  {"q":"Consensus Mechanism?","opts":["Voting for CEO","Agreement process among nodes to validate transactions","Searching data","Splitting data"],"ans":1},
  {"q":"Proof of Work (PoW)?","opts":["Easy task","Solving a computationally difficult mathematical puzzle (Mining)","Voting","Ranking"],"ans":1},
  {"q":"Proof of Stake (PoS)?","opts":["Mining","Validating based on the number of coins held","Physical work","Random choice"],"ans":1},
  {"q":"Smart Contract is?","opts":["A paper legal document","Self-executing contract with terms written in code","A secure password","A database query"],"ans":1},
  {"q":"Ethereum introduced?","opts":["Bitcoin","Smart contract functionality and dApps","Mining","Private keys"],"ans":1},
  {"q":"dApp stands for?","opts":["Decentralized Application","Digital App","Daily Application","Distributed Access Port"],"ans":0},
  {"q":"Distributed Ledger Technology (DLT)?","opts":["Central storage","Broad category of systems including blockchain for distributed records","Fast storage","Local disk"],"ans":1},
  {"q":"Public Blockchain?","opts":["Restricted access","Permissionless; anyone can join and participate","Private only","Local network"],"ans":1},
  {"q":"Private Blockchain (Permissioned)?","opts":["Anyone can join","Access restricted to authorized participants only","Publicly visible","No security"],"ans":1},
  {"q":"Consortium Blockchain?","opts":["Single owner","Controlled by a pre-selected group of organizations","Random access","Publicly open"],"ans":1},
  {"q":"Nonce in BC?","opts":["Random text","A number used once in the hashing process to find a valid block","Username","Key"],"ans":1},
  {"q":"Merkle Tree?","opts":["Physical tree","Hierarchical data structure of hashes used for efficient verification","Search index","Sorting list"],"ans":1},
  {"q":"Genesis Block?","opts":["Last block","The first block in a blockchain","Random block","Failed block"],"ans":1},
  {"q":"Wallet in BC?","opts":["Leather wallet","Software to store and manage private and public keys","Physical coin","Bank account"],"ans":1},
  {"q":"Public Key acts like?","opts":["Password","Account address shared for receiving funds","Secret key","Hardware ID"],"ans":1},
  {"q":"Private Key acts like?","opts":["Username","Secret signature to authorize transactions (never share)","Public address","File name"],"ans":1},
  {"q":"Fork in BC?","opts":["Eating tool","A change in protocol that results in a split/divergence","A merge","A bug fix only"],"ans":1},
  {"q":"Soft Fork?","opts":["Backwards incompatible","Backwards compatible update","Brand new chain","Small update"],"ans":1},
  {"q":"Hard Fork?","opts":["Compatible","Backwards incompatible update that splits the chain","Easy update","Logic check"],"ans":1},
  {"q":"Mining rewards?","opts":["Paying to play","Incentives (coins/fees) for miners who validate blocks","No reward","Lowered difficulty"],"ans":1},
  {"q":"Transaction Fee?","opts":["Paid to government","Paid to miners/validators for processing transactions","Subscription","Free"],"ans":1},
  {"q":"51% Attack?","opts":["When half users leave","When one entity controls more than half of the network's hash power","When data is deleted","Small glitch"],"ans":1},
  {"q":"Double Spending?","opts":["Spending twice as much","Risk of spending the same digital currency more than once","High interest","Inflation"],"ans":1},
  {"q":"Hyperledger is?","opts":["A crypto coin","Enterprise-focused private blockchain project by IBM/Linux Foundation","A wallet","A browser plugin"],"ans":1},
  {"q":"Solidity?","opts":["Math term","Programming language for writing Ethereum smart contracts","A database","A hardware part"],"ans":1},
  {"q":"Gas in Ethereum?","opts":["Fuel for cars","Unit measuring the computational effort needed for a transaction","Data size","Internet speed"],"ans":1},
  {"q":"Byzantine Fault Tolerance (BFT)?","opts":["Crashing on error","System's ability to reach consensus despite malicious nodes","Fast speed","Memory efficiency"],"ans":1},
  {"q":"Orphan Block?","opts":["Valid block, but not part of main chain","Corrupt block","Unlinked block","Failed transaction"],"ans":0},
  {"q":"Sharding in BC?","opts":["Merging data","Partitioning the network to handle more transactions (scalability)","Deleting data","Hiding data"],"ans":1},
  {"q":"Stablecoin?","opts":["Volatile coin","Cryptocurrency pegged to a stable asset (e.g. USD)","Bitcoin","Ethereum"],"ans":1},
  {"q":"NFT stands for?","opts":["Non-Fungible Token (unique digital asset)","Network File Transfer","New Fund Type","Natural Form Token"],"ans":0},
  {"q":"Cold Storage?","opts":["Refrigerated server","Storing private keys offline to prevent hacking","Fast RAM","Cloud storage"],"ans":1},
  {"q":"Hot Wallet?","opts":["Warm physical device","Wallet connected to the internet for frequent use","Burned device","Private server"],"ans":1},
  {"q":"ICO stands for?","opts":["Initial Coin Offering (fundraising for crypto)","Internal Code Output","Inbound Coin Origin","Inclusion Command Option"],"ans":0},
  {"q":"Permissionless?","opts":["Restricted","Open for anyone to join (Public BC)","Closed","Authorized only"],"ans":1},
  {"q":"Peer-to-Peer (P2P)?","opts":["Client-Server","Direct communication between nodes without a central server","Broadcast only","Local only"],"ans":1},
  {"q":"Transparency in BC?","opts":["Hidden data","Publicly verifiable transactions on the ledger","Opaque data","Encryption only"],"ans":1},
  {"q":"Mining Difficulty?","opts":["Number of miners","Parameter adjusting the target value for hashes to regulate block time","Hardware cost","Electricity price"],"ans":1},
  {"q":"Delegated Proof of Stake (DPoS)?","opts":["PoW","Token holders vote for delegates to validate transactions","Manual mining","Government control"],"ans":1},
  {"q":"Layer 2 Solutions?","opts":["Hardware upgrade","Protocols built on top of a BC to improve scalability (e.g. Lightning Network)","Binary code","Database index"],"ans":1},
  {"q":"Decentralized Finance (DeFi)?","opts":["Bank loans","Financial services built on blockchain without intermediaries","Stock market","Federal reserve"],"ans":1},
  {"q":"Blockchain scalability trilemma:","opts":["Cost, speed, size","Scalability, Security, Decentralization","Memory, CPU, Disk","User, App, Data"],"ans":1}
],
"sem7-cv": [
  {"q":"Computer Vision allows computers to?","opts":["Speak","See and interpret visual information from images/videos","Type","Calculate math"],"ans":1},
  {"q":"Digital Image is?","opts":["A painting","2D array of pixels (intensity values)","A text file","A physical print"],"ans":1},
  {"q":"Pixel stands for?","opts":["Picture Logic","Picture Element","Process Level","Primary Index"],"ans":1},
  {"q":"Grayscale image has?","opts":["RGB values","Single intensity value (0-255) per pixel","Colors","Binary values only"],"ans":1},
  {"q":"RGB stands for?","opts":["Random Grid Blue","Red, Green, Blue","Right Grey Binary","Real Gradient Blue"],"ans":1},
  {"q":"Convolution in CV involves?","opts":["Saving images","Applying a kernel/filter to an image to extract features","Scaling only","Deleting pixels"],"ans":1},
  {"q":"Edge Detection finds?","opts":["Brightest point","Points where image brightness changes sharply","Average color","Middle of image"],"ans":1},
  {"q":"Sobel Filter is used for?","opts":["Normalization","Edge detection","Clustering","Encryption"],"ans":1},
  {"q":"Gaussian Blur?","opts":["Sharpens image","Smooths image/reduces noise using Gaussian function","Adds random noise","Colors image"],"ans":1},
  {"q":"Thresholding?","opts":["Scaling","Converting grayscale to binary (0 or 1) based on a value","Rotating","Mirroring"],"ans":1},
  {"q":"Histogram in CV shows?","opts":["Object locations","Distribution of pixel intensities","Lines in image","Text in image"],"ans":1},
  {"q":"Morphological operations:","opts":["Erosion and Dilation","Scaling and Rotation","Binary and RGB","Input and Output"],"ans":0},
  {"q":"Erosion?","opts":["Adds pixels to boundaries","Reduces/thins objects in binary image","Smoothens image","Dials pixels"],"ans":1},
  {"q":"Dilation?","opts":["Thins objects","Adds pixels to boundaries/thickens objects","Sharpens","Gaussian blur"],"ans":1},
  {"q":"Feature Extraction?","opts":["Saving image","Identifying key parts/descriptors like corners, blobs, edges","Deleting background","Adding text"],"ans":1},
  {"q":"SIFT stands for?","opts":["Scale-Invariant Feature Transform","Spatial Index File Tool","Standard Image Filter","Signal Inversion Feedback"],"ans":0},
  {"q":"Image Segmentation divide image into?","opts":["Rows only","Meaningful parts or objects","Small squares","Grayscale levels"],"ans":1},
  {"q":"Semantic Segmentation?","opts":["Finding boxes","Classifying each pixel into a category","Finding text","Rotation"],"ans":1},
  {"q":"Instance Segmentation?","opts":["Grouping all cats together","Distinguishing individual instances of the same class","Grayscale change","Edge detection"],"ans":1},
  {"q":"Object Recognition?","opts":["Identifying edges","Identifying what is in an image (Classifying)","Deleting objects","Zooming"],"ans":1},
  {"q":"Object Detection tasks?","opts":["Classification only","Classification + Localization (where is it)","Greyscale only","Rotation only"],"ans":1},
  {"q":"Template Matching?","opts":["Creating a template","Finding a sub-image in a larger image using a template","Drawing circles","Sorting pixels"],"ans":1},
  {"q":"CNNs (Convolutional Neural Networks)?","opts":["For audio mostly","State-of-the-art for image related tasks","For text only","For hardware control"],"ans":1},
  {"q":"Pooling in CNNs?","opts":["Increases size","Down-samples feature maps, providing spatial variance","Adds color","Sharpens edges"],"ans":1},
  {"q":"Transfer Learning in CV?","opts":["Starting from zero","Using pre-trained models (ImageNet) for new tasks","Saving images","Recording video"],"ans":1},
  {"q":"Face Detection?","opts":["Identifying WHO a person is","Finding WHERE a face is in a photo","Identifying hair color","Deleting faces"],"ans":1},
  {"q":"Face Recognition?","opts":["Finding location of face","Identifying THE IDENTITY of the person","Finding where eyes are","Adding filters"],"ans":1},
  {"q":"Optical Flow?","opts":["Colored image","Pattern of apparent motion of objects between consecutive frames","Static image","Flash of light"],"ans":1},
  {"q":"Image Augmentation?","opts":["Deleting data","Applying transformations (rotate, flip) to increase training data","Taking more photos","Printing photos"],"ans":1},
  {"q":"Depth Perception?","opts":["One camera only","Inferring 3D structure from 2D images (Stereo vision)","Finding edges","Color intensity"],"ans":1},
  {"q":"Stereo Vision uses?","opts":["One camera","Two or more cameras to perceive depth","LIDAR only","Radar only"],"ans":1},
  {"q":"Hough Transform?","opts":["Finding colors","Finding shapes like lines and circles in an image","Finding brightness","Finding average"],"ans":1},
  {"q":"Corner Detection (e.g. Harris)?","opts":["Detecting edges","Finding points with high intensity changes in all directions","Finding center","Finding background"],"ans":1},
  {"q":"Blob Detection?","opts":["Finding lines","Finding regions in image that differ in properties from surroundings","Finding text","Finding gradients"],"ans":1},
  {"q":"Active Contours (Snakes)?","opts":["Binary search","Energy-minimizing curves that deform to fit object boundaries","A game","A virus"],"ans":1},
  {"q":"Keypoint descriptors?","opts":["Pixels","Numeric vectors describing local image patches (invariant to rotation/scale)","Text labels","File names"],"ans":1},
  {"q":"Background Subtraction?","opts":["Adding new background","Extracting foreground objects by removing static backplate","Grayscale change","Inverting colors"],"ans":1},
  {"q":"Mean Shift algorithm?","opts":["Finding average","Clustering technique used for object tracking/segmentation","Scaling","Encryption"],"ans":1},
  {"q":"YOLO stands for?","opts":["You Only Look Once (fast object detection)","Yellow Objects Localized Online","Your Own Logic Output","Yield Only Large Objects"],"ans":0},
  {"q":"R-CNN stands for?","opts":["Recurrent CNN","Regions with CNN features","Rectangular CNN","Random CNN"],"ans":1},
  {"q":"Bounding Box?","opts":["Circular area","Rectangular box surrounding a detected object","A shipping box","A pixel"],"ans":1},
  {"q":"IoU (Intersection over Union)?","opts":["Addition","Metric to evaluate overlap between predicted and ground truth boxes","Division","Multiplication"],"ans":1},
  {"q":"Non-Maximum Suppression (NMS)?","opts":["Deleting images","Removing overlapping redundant boxes in object detection","Adding more boxes","Zooming in"],"ans":1},
  {"q":"Image Inpainting?","opts":["Drawing on image","Automatically filling in missing/deleted parts of an image","Deleting images","Changing format"],"ans":1},
  {"q":"OCR stands for?","opts":["Optical Color Recognition","Optical Character Recognition (text from images)","Online Code Review","Object Control Resolution"],"ans":1},
  {"q":"Generative Adversarial Networks (GANs)?","opts":["Text models","Used to generate realistic synthetic images","Logic tools","Compression tools"],"ans":1},
  {"q":"Pose Estimation?","opts":["Finding names","Identifying coordinates of human joints in image/video","Identifying age","Identifying mood"],"ans":1},
  {"q":"LIDAR uses?","opts":["Sound waves","Light pulses to measure distance (3D mapping)","Radio waves","Cables"],"ans":1},
  {"q":"Computer Vision library?","opts":["React","OpenCV","Django","Redux"],"ans":1},
  {"q":"Main challenge in CV?","opts":["Storage","Variation in lighting, viewpoint, occlusion, and scale","Internet speed","File format"],"ans":1}
],
"sem7-devops": [
  {"q":"DevOps integrates?","opts":["Design and testing","Development and Operations teams/processes","Hardware and Software supply","UI and Logic"],"ans":1},
  {"q":"Core goal of DevOps?","opts":["Write code faster","Shorten systems development life cycle and provide continuous high quality","Hire more people","Save disk space"],"ans":1},
  {"q":"CI in CI/CD?","opts":["Continuous Integration","Consistent Interface","Code Improvement","Critical Issue"],"ans":0},
  {"q":"CD in CI/CD?","opts":["Continuous Development","Continuous Delivery or Deployment","Critical Data","Code Delivery"],"ans":1},
  {"q":"Continuous Integration involves?","opts":["Writing code yearly","Frequently merging code changes into a central repository and testing","Offline coding","Manual review only"],"ans":1},
  {"q":"Automation the process of?","opts":["Hiring","Using tools to perform tasks with minimal human intervention","Writing code manually","Watching logs"],"ans":1},
  {"q":"Infrastructure as Code (IaC)?","opts":["Writing code on paper","Managing infrastructure using configuration files/code (e.g. Terraform)","Physical servers only","Manual setup"],"ans":1},
  {"q":"Version Control?","opts":["Deleting old files","Tracking and managing changes to software code (Git)","Encryption","Documentation only"],"ans":1},
  {"q":"Git is?","opts":["Centralized VC","Distributed version control system","Project management tool","Compiler"],"ans":1},
  {"q":"Docker?","opts":["A heavy VM","Platform for building, running, and shipping containers","A language","A database"],"ans":1},
  {"q":"A Container is?","opts":["Physical box","Lightweight, standalone package of software including everything needed to run it","A virtual hard drive","Encrypted file"],"ans":1},
  {"q":"Kubernetes (K8s)?","opts":["Cloud provider","Container orchestration system for automating deployment/scaling","Browser","OS"],"ans":1},
  {"q":"Microservices architecture?","opts":["Single large app","Application built as a collection of small, independent services","Hardware units","Binary files"],"ans":1},
  {"q":"Monolithic architecture?","opts":["Multiple services","Unified, single-tier software application","Cloud only","Docker based"],"ans":1},
  {"q":"Jenkins?","opts":["A database","Open-source automation server for CI/CD pipelines","A text editor","A graphics tool"],"ans":1},
  {"q":"Monitoring in DevOps?","opts":["Checking at the end","Continuous real-time tracking of application/system performance and health","Deleting logs","Manual check weekly"],"ans":1},
  {"q":"Prometheus and Grafana are?","opts":["Databases","Tools for monitoring and observability/visualization","Compilers","Testing frameworks"],"ans":1},
  {"q":"Logging helps to?","opts":["Save space","Collect and analyze system events to troubleshoot issues","Speed up CPU","Hide errors"],"ans":1},
  {"q":"Elastic Stack (ELK)?","opts":["Storage types","Elasticsearch, Logstash, Kibana (for log management)","A CPU design","Web framework"],"ans":1},
  {"q":"Ansible, Chef, Puppet?","opts":["Programming languages","Configuration management tools","Graphics libraries","Browsers"],"ans":1},
  {"q":"Terraform?","opts":["Cloud provider","IaC tool for building and versioning infrastructure","A container engine","A virus"],"ans":1},
  {"q":"Agile and DevOps?","opts":["They are unrelated","DevOps complements Agile by extending iterative development to deployment","DevOps replaces Agile","Agile is for hardware"],"ans":1},
  {"q":"Deployment vs Delivery?","opts":["They are same","Deployment is automatic; Delivery is manual approval to production","Deployment is testing","Delivery is coding"],"ans":1},
  {"q":"Blue-Green Deployment?","opts":["Primary and backup sites","Running two identical production environments to reduce downtime/risk","Mixed colors","Testing only"],"ans":1},
  {"q":"Canary Deployment?","opts":["A bird","Rolling out updates to a small subset of users first","Cloud only","Manual copy"],"ans":1},
  {"q":"Rollback?","opts":["Deleting data","Reverting to a previous stable version after a failed deployment","Updating code","Saving state"],"ans":1},
  {"q":"Build Pipeline?","opts":["Sequence of automated steps (build, test, deploy)","A physical pipe","A file list","Compiler version"],"ans":0},
  {"q":"Artifact?","opts":["Ancient item","Package or file produced during build process (e.g. .jar, .zip, image)","A source file","A bug"],"ans":1},
  {"q":"Registry?","opts":["Physical book","Storage for container images (e.g. Docker Hub)","System settings","Database index"],"ans":1},
  {"q":"Orchestration?","opts":["Music only","Automated arrangement, coordination, and management of complex systems","Deleting files","Manual setup"],"ans":1},
  {"q":"SRE stands for?","opts":["Site Reliability Engineering (applying software engineering to operations)","System Runtime Effort","Soft Reset Engine","Secure Resource Entry"],"ans":0},
  {"q":"Mean Time to Recovery (MTTR)?","opts":["Total time","Average time to restore service after a failure","Time to code","Time to test"],"ans":1},
  {"q":"Mean Time Between Failures (MTBF)?","opts":["Crash count","Average time between system failures","Code speed","Deployment frequency"],"ans":1},
  {"q":"DevSecOps?","opts":["Secret ops","Integrating security practices throughout the DevOps lifecycle","Private DevOps","Encrypted code"],"ans":1},
  {"q":"Shift Left?","opts":["Moving data","Moving tasks (like security/testing) earlier in the development process","Moving to next phase","Deleting code"],"ans":1},
  {"q":"Feedback Loop?","opts":["Infinite loop","Process where output is used as input for improvement (e.g. user reports -> fixes)","Circular error","Recursive function"],"ans":1},
  {"q":"Cloud-Native?","opts":["Local server","Applications specifically designed for cloud environments","OS based","Offline tools"],"ans":1},
  {"q":"Service Mesh (e.g. Istio)?","opts":["Hardware network","Infrastructure layer for handling service-to-service communication","Web hosting","Text editor"],"ans":1},
  {"q":"GitOps?","opts":["Ops on Git","Managing infrastructure and application configurations via Git","Using Git only","Deployment for developers"],"ans":1},
  {"q":"Vagrant is?","opts":["A nomad","Tool for building and managing virtual development environments","A browser","A compiler"],"ans":1},
  {"q":"Sidecar pattern?","opts":["Vehicle","Attaching an auxiliary container to a primary container to provide helper features","Group of users","Isolated pod"],"ans":1},
  {"q":"Config Drift?","opts":["Moving files","When environment configuration deviates from the desired state over time","Slow internet","Deleting configs"],"ans":1},
  {"q":"Chaos Engineering?","opts":["Bad coding","Intentionally injecting failures to test system resilience (e.g. Netflix Chaos Monkey)","Deleting everything","Randomizing code"],"ans":1},
  {"q":"Zero Downtime?","opts":["One hour off","System remains fully available during updates/deployments","Zero latency","No user access"],"ans":1},
  {"q":"Virtualization vs Containerization?","opts":["They are identical","VNs (full Guest OS); Containers (shared OS kernel)","Containers are heavier","VMs are newer"],"ans":1},
  {"q":"YAML?","opts":["A language","Human-readable data-serialization language often used for configs","Encryption type","Binary format"],"ans":1},
  {"q":"Docker Compose?","opts":["Music tool","Tool for defining and running multi-container Docker applications","A code editor","A database"],"ans":1},
  {"q":"Post-mortem?","opts":["Before life","Analysis of a failure after it happened to prevent recurrence","Meeting before start","Testing phase"],"ans":1},
  {"q":"Dark Launch?","opts":["Launch at night","Deploying code to production but keeping it hidden from users for testing","Failed launch","Private release"],"ans":1},
  {"q":"The Five CALMS of DevOps:","opts":["Culture, Automation, Lean, Measurement, Sharing","Code, Access, Logic, Meta, Security","Cost, Accuracy, Level, Main, System"],"ans":0}
],
}

def build_js_block(subject_key, questions):
    lines = [f'  "{subject_key}": [']
    for i, q in enumerate(questions):
        comma = "," if i < len(questions)-1 else ""
        opts = ', '.join(f'"{o}"' for o in q["opts"])
        lines.append(f'    {{')
        lines.append(f'      "question": "{q["q"]}",')
        lines.append(f'      "options": [{opts}],')
        lines.append(f'      "correctAnswer": {q["ans"]}')
        lines.append(f'    }}{comma}')
    lines.append('  ]')
    return '\n'.join(lines)

out_dir = os.path.join(os.path.dirname(__file__), '..', 'frontend', 'assets')
out_file = os.path.join(out_dir, 'quiz_sem7.js')

blocks = []
keys = list(SEM7.keys())
for i, key in enumerate(keys):
    comma = "," if i < len(keys)-1 else ""
    blocks.append(build_js_block(key, SEM7[key]) + comma)

content = 'const quizDataSem7 = {\n' + '\n'.join(blocks) + '\n};\n'
with open(out_file, 'w', encoding='utf-8') as f:
    f.write(content)

for key, qs in SEM7.items():
    assert len(qs) == 50, f"{key} has {len(qs)} questions"
    texts = [q['q'] for q in qs]
    assert len(set(texts)) == 50, f"{key} has duplicate questions"

print(f"[OK] quiz_sem7.js generated with {len(SEM7)} subjects, 50 questions each.")
